<a href="https://colab.research.google.com/github/ammarbadri919-tech/gnss-signal-state-prediction/blob/main/Copy%20_of_main_modeling_ipynb%20v3._test1_new_labeling1%20_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:


import zipfile

zip_path = "/content/drive/MyDrive/Gnns_kaggle_2324/smartphone-decimeter-2023.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    files = z.namelist()


print("Total files:", len(files))
print("\n".join(files[:50]))

Total files: 904
sdc2023/metadata/accumulated_delta_range_state_bit_map.json
sdc2023/metadata/constellation_type_mapping.csv
sdc2023/metadata/raw_state_bit_map.json
sdc2023/sample_submission.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_imu.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/supplemental/gnss_log.txt
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_gnss.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_imu.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/supplemental/gnss_log.txt
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_gnss.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_imu.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/supplemental/gnss_log.txt
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_gnss.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_imu.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/supplemental/gnss_log.txt
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_gnss.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_imu.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/supplemental/gnss_log.txt
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_gnss.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_imu.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/supplemental/gnss_log.txt
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_gnss.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_imu.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/supplemental/gnss_log.txt
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_gnss.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_imu.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/supplemental/gnss_log.txt
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_gnss.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_imu.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_imu.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_imu.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_imu.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_imu.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_gnss.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_imu.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/supplemental/gnss_log.txt
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_gnss.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_imu.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/supplemental/gnss_log.txt
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_gnss.csv

In [7]:
csv_file = [file for file in files if file.endswith(".csv")]
print("CSV FILE FOUND",len(csv_file))
print("\n".join(csv_file[:50]))

CSV FILE FOUND 550
sdc2023/metadata/constellation_type_mapping.csv
sdc2023/sample_submission.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_imu.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_gnss.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_imu.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_gnss.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_imu.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_gnss.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_imu.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_gnss.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_imu.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_gnss.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_imu.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_gnss.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_imu.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_gnss.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_imu.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_gnss.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_imu.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_imu.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_imu.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_imu.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_imu.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_gnss.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_imu.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_gnss.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_imu.csv
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_gnss.csv
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_imu.csv
sdc2023/test/2022-04-04-16-31-us-ca-lax-x/pixel5/device_gnss.csv
sdc2023/test/2022-04-04-16-31-us-ca-lax-x/pixel5/device_imu.csv
sdc2023/test/2022-04-22-20-11-us-ca-ebf-y/pixel5/device_gnss.csv
sdc2023/test/2022-04-22-20-11-us-ca-ebf-y/pixel5/device_imu.csv
sdc2023/test/2022-04-25-21-04-us-ca-ebf-x/mi8/device_gnss.csv
sdc2023/test/2022-04-25-21-04-us-ca-ebf-x/mi8/device_imu.csv
sdc2023/test/2022-04-25-22-36-us-ca-ebf-z/pixel5/device_gnss.csv
sdc2023/test/2022-04-25-22-36-us-ca-ebf-z/pixel5/device_imu.csv
sdc2023/test/2022-04-27-18-16-us-ca-ebf-zz/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-18-16-us-ca-ebf-zz/pixel5/device_imu.csv
sdc2023/test/2022-04-27-19-23-us-ca-ebf-xx/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-19-23-us-ca-ebf-xx/pixel5/device_imu.csv
sdc2023/test/2022-04-27-21-55-us-ca-ebf-ww/mi8/device_gnss.csv
sdc2023/test/2022-04-27-21-55-us-ca-ebf-ww/mi8/device_imu.csv
sdc2023/test/2022-05-12-20-19-us-ca-mtv-pe1/samsunga325g/device_gnss.csv
sdc2023/test/2022-05-12-20-19-us-ca-mtv-pe1/samsunga325g/device_imu.csv

In [8]:
gnss_files =[file for file in csv_file
             if file.endswith("/device_gnss.csv")]
print("GNSS files found",len(gnss_files))
print("\n".join(gnss_files[:50]))

GNSS files found 196
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_gnss.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_gnss.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_gnss.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_gnss.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_gnss.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_gnss.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_gnss.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_gnss.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_gnss.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_gnss.csv
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_gnss.csv
sdc2023/test/2022-04-04-16-31-us-ca-lax-x/pixel5/device_gnss.csv
sdc2023/test/2022-04-22-20-11-us-ca-ebf-y/pixel5/device_gnss.csv
sdc2023/test/2022-04-25-21-04-us-ca-ebf-x/mi8/device_gnss.csv
sdc2023/test/2022-04-25-22-36-us-ca-ebf-z/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-18-16-us-ca-ebf-zz/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-19-23-us-ca-ebf-xx/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-21-55-us-ca-ebf-ww/mi8/device_gnss.csv
sdc2023/test/2022-05-12-20-19-us-ca-mtv-pe1/samsunga325g/device_gnss.csv
sdc2023/test/2022-06-22-20-12-us-ca-lax-hh/samsunga325g/device_gnss.csv
sdc2023/test/2022-06-28-20-56-us-ca-sjc-r/samsunga32/device_gnss.csv
sdc2023/test/2022-07-12-18-37-us-ca-mtv-b/sm-a325f/device_gnss.csv
sdc2023/test/2022-10-06-20-46-us-ca-sjc-r/sm-a205u/device_gnss.csv
sdc2023/test/2023-04-27-19-25-us-ca-mtv-pe1/pixel5/device_gnss.csv
sdc2023/test/2023-04-27-20-55-us-ca-sjc-q/pixel5/device_gnss.csv
sdc2023/test/2023-05-02-19-24-us-ca-sjc-we1/pixel7pro/device_gnss.csv
sdc2023/test/2023-05-02-20-33-us-ca-mtv-xe1/pixel7pro/device_gnss.csv
sdc2023/test/2023-05-09-23-10-us-ca-sjc-r/sm-a505u/device_gnss.csv
sdc2023/test/2023-05-23-21-06-us-ca-mtv-de1/pixel5/device_gnss.csv
sdc2023/test/2023-05-23-22-16-us-ca-mtv-ie2/pixel6pro/device_gnss.csv
sdc2023/test/2023-05-25-17-32-us-ca-pao-j/pixel6pro/device_gnss.csv
sdc2023/test/2023-05-25-21-50-us-ca-sjc-ke2/sm-s908b/device_gnss.csv
sdc2023/test/2023-05-26-21-23-us-ca-sjc-be2/pixel5/device_gnss.csv
sdc2023/test/2023-06-06-22-43-us-ca-sjc-he2/pixel5/device_gnss.csv
sdc2023/test/2023-06-15-18-49-us-ca-sjc-ce1/pixel7pro/device_gnss.csv
sdc2023/train/2020-06-25-00-34-us-ca-mtv-sb-101/pixel4/device_gnss.csv
sdc2023/train/2020-06-25-00-34-us-ca-mtv-sb-101/pixel4xl/device_gnss.csv
sdc2023/train/2020-07-08-22-28-us-ca/pixel4/device_gnss.csv
sdc2023/train/2020-07-08-22-28-us-ca/pixel4xl/device_gnss.csv
sdc2023/train/2020-07-17-22-27-us-ca-mtv-sf-280/pixel4/device_gnss.csv
sdc2023/train/2020-07-17-23-13-us-ca-sf-mtv-280/pixel4/device_gnss.csv
sdc2023/train/2020-07-17-23-13-us-ca-sf-mtv-280/pixel4xl/device_gnss.csv
sdc2023/train/2020-08-04-00-19-us-ca-sb-mtv-101/pixel4/device_gnss.csv
sdc2023/train/2020-08-04-00-20-us-ca-sb-mtv-101/pixel4xl/device_gnss.csv
sdc2023/train/2020-08-04-00-20-us-ca-sb-mtv-101/pixel5/device_gnss.csv

In [9]:
import pandas as pd
import zipfile
sample_file = gnss_files[0]
with zipfile.ZipFile(zip_path, "r") as z:
   sample_df = pd.read_csv(z.open(sample_file), nrows=5)
print("Sample file:", sample_file)
print("Columns:", len(sample_df.columns))
display(sample_df.head())

Sample file: sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
Columns: 58

,MessageType,utcTimeMillis,TimeNanos,LeapSecond,TimeUncertaintyNanos,FullBiasNanos,BiasNanos,BiasUncertaintyNanos,DriftNanosPerSecond,DriftUncertaintyNanosPerSecond,...,SvVelocityYEcefMetersPerSecond,SvVelocityZEcefMetersPerSecond,SvClockBiasMeters,SvClockDriftMetersPerSecond,IsrbMeters,IonosphericDelayMeters,TroposphericDelayMeters,WlsPositionXEcefMeters,WlsPositionYEcefMeters,WlsPositionZEcefMeters
0,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-340.093293,-3183.605736,238953.664854,-0.000900,0.0,3.359449,3.872354,-2.710175e+06,-4.278810e+06,3.863761e+06
1,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-2609.046389,-1041.838400,-8170.672094,-0.003174,0.0,2.412421,2.769697,-2.710175e+06,-4.278810e+06,3.863761e+06
2,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-948.201121,2096.337128,-48995.470518,-0.000954,0.0,3.041131,3.626980,-2.710175e+06,-4.278810e+06,3.863761e+06
3,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-616.523320,3010.480790,-90005.243128,-0.001351,0.0,5.619127,15.589435,-2.710175e+06,-4.278810e+06,3.863761e+06
4,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-936.390309,3013.610651,-74629.512567,-0.002282,0.0,6.382237,10.248850,-2.710175e+06,-4.278810e+06,3.863761e+06

In [10]:
import zipfile
with zipfile.ZipFile(zip_path, "r") as z:

  for file in gnss_files:
    print("Processing ",file)
    df =pd.read_csv(z.open(file))
    print("shape",df.shape)
    break

Processing  sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
shape (44501, 58)

In [11]:
import zipfile
with zipfile.ZipFile(zip_path, "r") as z:

  for file in gnss_files:
    print("Processing ",file)
    df =pd.read_csv(z.open(file))
    print("shape",df.shape)
    print("Memory used:",df.memory_usage(deep=True).sum() / 1024**2,
              "MB")
    break

Processing  sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
shape (44501, 58)
Memory used: 23.67861270904541 MB

In [12]:
print("Memory used",df.memory_usage(deep=True).sum() / 1024**2)
print(df.columns.tolist())

Memory used 23.67861270904541
['MessageType', 'utcTimeMillis', 'TimeNanos', 'LeapSecond', 'TimeUncertaintyNanos', 'FullBiasNanos', 'BiasNanos', 'BiasUncertaintyNanos', 'DriftNanosPerSecond', 'DriftUncertaintyNanosPerSecond', 'HardwareClockDiscontinuityCount', 'Svid', 'TimeOffsetNanos', 'State', 'ReceivedSvTimeNanos', 'ReceivedSvTimeUncertaintyNanos', 'Cn0DbHz', 'PseudorangeRateMetersPerSecond', 'PseudorangeRateUncertaintyMetersPerSecond', 'AccumulatedDeltaRangeState', 'AccumulatedDeltaRangeMeters', 'AccumulatedDeltaRangeUncertaintyMeters', 'CarrierFrequencyHz', 'CarrierCycles', 'CarrierPhase', 'CarrierPhaseUncertainty', 'MultipathIndicator', 'SnrInDb', 'ConstellationType', 'AgcDb', 'BasebandCn0DbHz', 'FullInterSignalBiasNanos', 'FullInterSignalBiasUncertaintyNanos', 'SatelliteInterSignalBiasNanos', 'SatelliteInterSignalBiasUncertaintyNanos', 'CodeType', 'ChipsetElapsedRealtimeNanos', 'ArrivalTimeNanosSinceGpsEpoch', 'RawPseudorangeMeters', 'RawPseudorangeUncertaintyMeters', 'SignalType', 'ReceivedSvTimeNanosSinceGpsEpoch', 'SvPositionXEcefMeters', 'SvPositionYEcefMeters', 'SvPositionZEcefMeters', 'SvElevationDegrees', 'SvAzimuthDegrees', 'SvVelocityXEcefMetersPerSecond', 'SvVelocityYEcefMetersPerSecond', 'SvVelocityZEcefMetersPerSecond', 'SvClockBiasMeters', 'SvClockDriftMetersPerSecond', 'IsrbMeters', 'IonosphericDelayMeters', 'TroposphericDelayMeters', 'WlsPositionXEcefMeters', 'WlsPositionYEcefMeters', 'WlsPositionZEcefMeters']

In [13]:
features = [
    "ConstellationType",
    "Svid",
    "SignalType",
    "utcTimeMillis",
    "Cn0DbHz",
    "RawPseudorangeMeters",
    "PseudorangeRateMetersPerSecond",
    "AccumulatedDeltaRangeMeters",
    "SvElevationDegrees",
    "SvAzimuthDegrees"
]
df = df[features].copy()

print("new shape:", df.shape)

new shape: (44501, 10)

In [14]:

##df =df.sort_values(["Svid","utcTimeMillis"]).reset_index(drop=True)

In [15]:
df["signal_id"] = (
    df["ConstellationType"].astype(str)
    + "_"
    + df["Svid"].astype(str)
    + "_"
    + df["SignalType"].astype(str)
)

print(
    df[
        ["ConstellationType", "Svid", "SignalType", "signal_id"]
    ].head(10)
)

   ConstellationType  Svid SignalType       signal_id
0                  1     1  GPS_L1_CA   1_1_GPS_L1_CA
1                  1     3  GPS_L1_CA   1_3_GPS_L1_CA
2                  1     4  GPS_L1_CA   1_4_GPS_L1_CA
3                  1     9  GPS_L1_CA   1_9_GPS_L1_CA
4                  1    16  GPS_L1_CA  1_16_GPS_L1_CA
5                  1    21  GPS_L1_CA  1_21_GPS_L1_CA
6                  1    22  GPS_L1_CA  1_22_GPS_L1_CA
7                  1    31  GPS_L1_CA  1_31_GPS_L1_CA
8                  1    32  GPS_L1_CA  1_32_GPS_L1_CA
9                  3    10  GLO_G1_CA  3_10_GLO_G1_CA

In [16]:
df = df.sort_values(["signal_id","utcTimeMillis"]).reset_index(drop=True)
print(df[["signal_id","utcTimeMillis"]].head(20))

         signal_id  utcTimeMillis
0   1_16_GPS_L1_CA  1607715055442
1   1_16_GPS_L1_CA  1607715056442
2   1_16_GPS_L1_CA  1607715057442
3   1_16_GPS_L1_CA  1607715058442
4   1_16_GPS_L1_CA  1607715059442
5   1_16_GPS_L1_CA  1607715060442
6   1_16_GPS_L1_CA  1607715061442
7   1_16_GPS_L1_CA  1607715062442
8   1_16_GPS_L1_CA  1607715063442
9   1_16_GPS_L1_CA  1607715064442
10  1_16_GPS_L1_CA  1607715065442
11  1_16_GPS_L1_CA  1607715066442
12  1_16_GPS_L1_CA  1607715067442
13  1_16_GPS_L1_CA  1607715068442
14  1_16_GPS_L1_CA  1607715069442
15  1_16_GPS_L1_CA  1607715070442
16  1_16_GPS_L1_CA  1607715071442
17  1_16_GPS_L1_CA  1607715072442
18  1_16_GPS_L1_CA  1607715073442
19  1_16_GPS_L1_CA  1607715074442

In [17]:
numerica_cols =[ "Cn0DbHz",
    "RawPseudorangeMeters",
    "PseudorangeRateMetersPerSecond",
    "AccumulatedDeltaRangeMeters",
    "SvElevationDegrees",
    "SvAzimuthDegrees"
]

In [18]:
df[numerica_cols]=(df.groupby("signal_id")[numerica_cols].transform( lambda x: x.interpolate(
              method="linear",
              limit=2,
              limit_direction="both")))

In [19]:
df = df.dropna(subset= numerica_cols).reset_index(drop=True)

print("new shape:", df.shape)
print("Remaining NaNs:")
print(df[numerica_cols].isna().sum())

new shape: (44276, 11)
Remaining NaNs:
Cn0DbHz                           0
RawPseudorangeMeters              0
PseudorangeRateMetersPerSecond    0
AccumulatedDeltaRangeMeters       0
SvElevationDegrees                0
SvAzimuthDegrees                  0
dtype: int64

Cn0DbHz = signal strength.

In [20]:
def circular_diff_group(group):
    group = group.copy()
    group["Azimuth_change"] = (
        (group["SvAzimuthDegrees"].diff() + 180) % 360
    ) - 180
    return group

df = (
    df.groupby("signal_id", group_keys=False)
      .apply(circular_diff_group)
      .reset_index(drop=True)
)

df["Azimuth_change"] = df["Azimuth_change"].clip(-180, 180)
print("Azimuth circular diff applied successfully!")

Azimuth circular diff applied successfully!

/tmp/ipykernel_1674/4088929506.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(circular_diff_group)

In [21]:
df["Cn0_change"]=(df.groupby("signal_id")["Cn0DbHz"].diff())

In [22]:
#C/N0 rolling mean
df["Cn0_rolling_mean"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).mean()
      )
)

In [23]:
df["Cn0_trend_mean"]=df.groupby("signal_id")["Cn0_change"].transform(lambda x: x.rolling(window=3,min_periods=1).mean())
print("Cn0_trend_mean")

Cn0_trend_mean

In [24]:
df["is_up"]= df["Cn0_trend_mean"]>0
print("is_up")

is_up

In [25]:
df["up_streak"] = (
    df.groupby("signal_id")["is_up"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

print("up_streak created")

up_streak created

In [26]:
df["is_down"]= df["Cn0_trend_mean"]<0
print("is_down")

is_down

In [27]:
df["down_streak"] = (
    df.groupby("signal_id")["is_down"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

print("down_streak created")

down_streak created

In [28]:
df["Cn0_rolling_std"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).mean()
      )
)

In [29]:
display( df[ [ "signal_id", "Cn0DbHz", "Cn0_rolling_std" ] ].head(15) )

         signal_id  Cn0DbHz  Cn0_rolling_std
0   1_16_GPS_L1_CA     36.4        36.400000
1   1_16_GPS_L1_CA     36.6        36.500000
2   1_16_GPS_L1_CA     36.1        36.366667
3   1_16_GPS_L1_CA     38.2        36.825000
4   1_16_GPS_L1_CA     39.5        37.360000
5   1_16_GPS_L1_CA     38.9        37.860000
6   1_16_GPS_L1_CA     40.0        38.540000
7   1_16_GPS_L1_CA     38.5        39.020000
8   1_16_GPS_L1_CA     35.1        38.400000
9   1_16_GPS_L1_CA     41.4        38.780000
10  1_16_GPS_L1_CA     43.6        39.720000
11  1_16_GPS_L1_CA     40.2        39.760000
12  1_16_GPS_L1_CA     41.2        40.300000
13  1_16_GPS_L1_CA     41.5        41.580000
14  1_16_GPS_L1_CA     41.4        41.580000

In [30]:
df['cn0_slope']=(df.groupby("signal_id")["Cn0DbHz"].transform(lambda x: x. diff(4)/4))
print("cn0_slope")

cn0_slope

In [31]:
display( df[ [ "signal_id", "Cn0DbHz", "cn0_slope" ] ].head(15) )

         signal_id  Cn0DbHz  cn0_slope
0   1_16_GPS_L1_CA     36.4        NaN
1   1_16_GPS_L1_CA     36.6        NaN
2   1_16_GPS_L1_CA     36.1        NaN
3   1_16_GPS_L1_CA     38.2        NaN
4   1_16_GPS_L1_CA     39.5      0.775
5   1_16_GPS_L1_CA     38.9      0.575
6   1_16_GPS_L1_CA     40.0      0.975
7   1_16_GPS_L1_CA     38.5      0.075
8   1_16_GPS_L1_CA     35.1     -1.100
9   1_16_GPS_L1_CA     41.4      0.625
10  1_16_GPS_L1_CA     43.6      0.900
11  1_16_GPS_L1_CA     40.2      0.425
12  1_16_GPS_L1_CA     41.2      1.525
13  1_16_GPS_L1_CA     41.5      0.025
14  1_16_GPS_L1_CA     41.4     -0.550

df["Cn0_acceleration"] = (
    df.groupby("signal_id")["Cn0_slope"]
      .diff()
)

print("Cn0_acceleration created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_slope",
            "Cn0_acceleration"
        ]
    ].head(15)
)

In [32]:
print(df[["signal_id","utcTimeMillis", "Cn0DbHz" , "Cn0_change"]].head(20))

         signal_id  utcTimeMillis  Cn0DbHz  Cn0_change
0   1_16_GPS_L1_CA  1607715055442     36.4         NaN
1   1_16_GPS_L1_CA  1607715056442     36.6         0.2
2   1_16_GPS_L1_CA  1607715057442     36.1        -0.5
3   1_16_GPS_L1_CA  1607715058442     38.2         2.1
4   1_16_GPS_L1_CA  1607715059442     39.5         1.3
5   1_16_GPS_L1_CA  1607715060442     38.9        -0.6
6   1_16_GPS_L1_CA  1607715061442     40.0         1.1
7   1_16_GPS_L1_CA  1607715062442     38.5        -1.5
8   1_16_GPS_L1_CA  1607715063442     35.1        -3.4
9   1_16_GPS_L1_CA  1607715064442     41.4         6.3
10  1_16_GPS_L1_CA  1607715065442     43.6         2.2
11  1_16_GPS_L1_CA  1607715066442     40.2        -3.4
12  1_16_GPS_L1_CA  1607715067442     41.2         1.0
13  1_16_GPS_L1_CA  1607715068442     41.5         0.3
14  1_16_GPS_L1_CA  1607715069442     41.4        -0.1
15  1_16_GPS_L1_CA  1607715070442     40.8        -0.6
16  1_16_GPS_L1_CA  1607715071442     38.7        -2.1
17  1_16_GPS_L1_CA  1607715072442     42.0         3.3
18  1_16_GPS_L1_CA  1607715073442     43.7         1.7
19  1_16_GPS_L1_CA  1607715074442     41.2        -2.5

In [33]:
df["time_gap"] = (
    df.groupby("signal_id")["utcTimeMillis"].diff()
)

print(
    df[
        ["signal_id", "utcTimeMillis", "time_gap"]
    ].head(20)
)

         signal_id  utcTimeMillis  time_gap
0   1_16_GPS_L1_CA  1607715055442       NaN
1   1_16_GPS_L1_CA  1607715056442    1000.0
2   1_16_GPS_L1_CA  1607715057442    1000.0
3   1_16_GPS_L1_CA  1607715058442    1000.0
4   1_16_GPS_L1_CA  1607715059442    1000.0
5   1_16_GPS_L1_CA  1607715060442    1000.0
6   1_16_GPS_L1_CA  1607715061442    1000.0
7   1_16_GPS_L1_CA  1607715062442    1000.0
8   1_16_GPS_L1_CA  1607715063442    1000.0
9   1_16_GPS_L1_CA  1607715064442    1000.0
10  1_16_GPS_L1_CA  1607715065442    1000.0
11  1_16_GPS_L1_CA  1607715066442    1000.0
12  1_16_GPS_L1_CA  1607715067442    1000.0
13  1_16_GPS_L1_CA  1607715068442    1000.0
14  1_16_GPS_L1_CA  1607715069442    1000.0
15  1_16_GPS_L1_CA  1607715070442    1000.0
16  1_16_GPS_L1_CA  1607715071442    1000.0
17  1_16_GPS_L1_CA  1607715072442    1000.0
18  1_16_GPS_L1_CA  1607715073442    1000.0
19  1_16_GPS_L1_CA  1607715074442    1000.0

In [34]:
df["Pseudorange_change"]=(df.groupby("signal_id")["RawPseudorangeMeters"].diff())
print(
    df[
        ["signal_id", "utcTimeMillis","RawPseudorangeMeters","Pseudorange_change"]
    ].head(20)
)

         signal_id  utcTimeMillis  RawPseudorangeMeters  Pseudorange_change
0   1_16_GPS_L1_CA  1607715055442          2.418345e+07                 NaN
1   1_16_GPS_L1_CA  1607715056442          2.418287e+07         -579.199029
2   1_16_GPS_L1_CA  1607715057442          2.418229e+07         -573.802765
3   1_16_GPS_L1_CA  1607715058442          2.418172e+07         -568.706293
4   1_16_GPS_L1_CA  1607715059442          2.418116e+07         -568.406500
5   1_16_GPS_L1_CA  1607715060442          2.418058e+07         -578.599444
6   1_16_GPS_L1_CA  1607715061442          2.418001e+07         -571.704217
7   1_16_GPS_L1_CA  1607715062442          2.417943e+07         -572.603595
8   1_16_GPS_L1_CA  1607715063442          2.417885e+07         -580.997784
9   1_16_GPS_L1_CA  1607715064442          2.417827e+07         -576.800689
10  1_16_GPS_L1_CA  1607715065442          2.417770e+07         -578.899236
11  1_16_GPS_L1_CA  1607715066442          2.417712e+07         -577.100482
12  1_16_GPS_L1_CA  1607715067442          2.417656e+07         -563.609821
13  1_16_GPS_L1_CA  1607715068442          2.417598e+07         -577.400274
14  1_16_GPS_L1_CA  1607715069442          2.417540e+07         -576.800689
15  1_16_GPS_L1_CA  1607715070442          2.417483e+07         -569.905463
16  1_16_GPS_L1_CA  1607715071442          2.417425e+07         -582.796538
17  1_16_GPS_L1_CA  1607715072442          2.417367e+07         -579.498821
18  1_16_GPS_L1_CA  1607715073442          2.417309e+07         -579.498821
19  1_16_GPS_L1_CA  1607715074442          2.417252e+07         -571.404425

In [35]:
df["PseudorangeRate_change"]=(df.groupby("signal_id")["PseudorangeRateMetersPerSecond"].diff())

In [36]:
df["Elevation_change"] = (
    df.groupby("signal_id")["SvElevationDegrees"].diff()
)

print(
    df[
        [
            "signal_id",
            "utcTimeMillis",
            "SvElevationDegrees",
            "Elevation_change"
        ]
    ].head(20)
)

         signal_id  utcTimeMillis  SvElevationDegrees  Elevation_change
0   1_16_GPS_L1_CA  1607715055442           13.900605               NaN
1   1_16_GPS_L1_CA  1607715056442           13.906558          0.005952
2   1_16_GPS_L1_CA  1607715057442           13.912509          0.005952
3   1_16_GPS_L1_CA  1607715058442           13.918452          0.005943
4   1_16_GPS_L1_CA  1607715059442           13.924405          0.005953
5   1_16_GPS_L1_CA  1607715060442           13.930350          0.005946
6   1_16_GPS_L1_CA  1607715061442           13.936303          0.005952
7   1_16_GPS_L1_CA  1607715062442           13.942265          0.005962
8   1_16_GPS_L1_CA  1607715063442           13.948238          0.005973
9   1_16_GPS_L1_CA  1607715064442           13.954199          0.005961
10  1_16_GPS_L1_CA  1607715065442           13.960156          0.005957
11  1_16_GPS_L1_CA  1607715066442           13.966096          0.005940
12  1_16_GPS_L1_CA  1607715067442           13.972024          0.005928
13  1_16_GPS_L1_CA  1607715068442           13.977974          0.005950
14  1_16_GPS_L1_CA  1607715069442           13.983932          0.005959
15  1_16_GPS_L1_CA  1607715070442           13.989877          0.005945
16  1_16_GPS_L1_CA  1607715071442           13.995852          0.005975
17  1_16_GPS_L1_CA  1607715072442           14.001817          0.005965
18  1_16_GPS_L1_CA  1607715073442           14.007796          0.005979
19  1_16_GPS_L1_CA  1607715074442           14.013761          0.005965

In [37]:
df["Azimuth_change"] = (
    df.groupby("signal_id")["SvAzimuthDegrees"].diff()
)

print(
    df[
        [
            "signal_id",
            "utcTimeMillis",
            "SvAzimuthDegrees",
            "Azimuth_change"
        ]
    ].head(20)
)

         signal_id  utcTimeMillis  SvAzimuthDegrees  Azimuth_change
0   1_16_GPS_L1_CA  1607715055442        146.369269             NaN
1   1_16_GPS_L1_CA  1607715056442        146.364709       -0.004561
2   1_16_GPS_L1_CA  1607715057442        146.360131       -0.004578
3   1_16_GPS_L1_CA  1607715058442        146.355562       -0.004569
4   1_16_GPS_L1_CA  1607715059442        146.351011       -0.004552
5   1_16_GPS_L1_CA  1607715060442        146.346451       -0.004559
6   1_16_GPS_L1_CA  1607715061442        146.341907       -0.004544
7   1_16_GPS_L1_CA  1607715062442        146.337359       -0.004548
8   1_16_GPS_L1_CA  1607715063442        146.332837       -0.004522
9   1_16_GPS_L1_CA  1607715064442        146.328280       -0.004556
10  1_16_GPS_L1_CA  1607715065442        146.323744       -0.004536
11  1_16_GPS_L1_CA  1607715066442        146.319193       -0.004551
12  1_16_GPS_L1_CA  1607715067442        146.314620       -0.004574
13  1_16_GPS_L1_CA  1607715068442        146.310061       -0.004559
14  1_16_GPS_L1_CA  1607715069442        146.305497       -0.004564
15  1_16_GPS_L1_CA  1607715070442        146.300930       -0.004567
16  1_16_GPS_L1_CA  1607715071442        146.296357       -0.004573
17  1_16_GPS_L1_CA  1607715072442        146.291796       -0.004561
18  1_16_GPS_L1_CA  1607715073442        146.287215       -0.004580
19  1_16_GPS_L1_CA  1607715074442        146.282652       -0.004564

In [38]:
print(df["Azimuth_change"].describe())

count    44233.000000
mean        -0.002650
std          0.016816
min         -0.652393
25%         -0.006347
50%         -0.004016
75%          0.005328
max          0.811208
Name: Azimuth_change, dtype: float64

In [39]:
print(
    df[
        [
            "Cn0_change",
            "time_gap",
            "Pseudorange_change",
            "PseudorangeRate_change",
            "Elevation_change",
            "Azimuth_change"
        ]
    ].isna().sum()
)

Cn0_change                43
time_gap                  43
Pseudorange_change        43
PseudorangeRate_change    43
Elevation_change          43
Azimuth_change            43
dtype: int64

In [40]:
print(df["Cn0DbHz"].describe())

count    44276.000000
mean        35.110518
std          5.912629
min         20.000000
25%         31.000000
50%         35.700000
75%         39.600000
max         48.800000
Name: Cn0DbHz, dtype: float64

In [41]:
print(
    df[
        ["signal_id", "utcTimeMillis", "Cn0DbHz", "Cn0_change"]
    ]
    .sort_values("Cn0DbHz")
    .head(20)
)

             signal_id  utcTimeMillis  Cn0DbHz  Cn0_change
34124   6_26_GAL_E5A_Q  1607715182442     20.0        -1.3
16664     1_9_GPS_L5_Q  1607715493442     20.0        -2.6
32364   6_21_GAL_E5A_Q  1607715543442     20.0        -5.3
14256    1_6_GPS_L1_CA  1607715097442     20.0         NaN
28047   6_12_GAL_E5A_Q  1607715382442     20.0        -0.9
3722    1_21_GPS_L1_CA  1607715333442     20.0       -14.6
793     1_16_GPS_L1_CA  1607715909442     20.0        -0.5
7667     1_26_GPS_L5_Q  1607715835442     20.1        -4.9
4220    1_21_GPS_L1_CA  1607715838442     20.1        -1.0
13736     1_4_GPS_L5_Q  1607715692442     20.1        -2.2
16884     1_9_GPS_L5_Q  1607715763442     20.1        -9.2
21342   3_23_GLO_G1_CA  1607715624442     20.1        -4.4
32383   6_21_GAL_E5A_Q  1607715573442     20.1        -2.7
2702      1_1_GPS_L5_Q  1607715497442     20.1        -1.3
22312   3_24_GLO_G1_CA  1607715437442     20.1        -4.1
36319   6_27_GAL_E5A_Q  1607715250442     20.1        -1.0
28339   6_12_GAL_E5A_Q  1607715765442     20.1        -2.8
27224  6_12_GAL_E1_C_P  1607715682442     20.1        -3.5
30725   6_19_GAL_E5A_Q  1607716162442     20.1        -5.4
28279   6_12_GAL_E5A_Q  1607715678442     20.1        -0.1

In [42]:
signal = "1_21_GPS_L1_CA"

print(
    df[df["signal_id"] == signal][
        ["utcTimeMillis", "Cn0DbHz", "Cn0_change"]
    ].head(30)
)

      utcTimeMillis  Cn0DbHz  Cn0_change
3447  1607715055442     26.8         NaN
3448  1607715056442     29.0         2.2
3449  1607715057442     29.2         0.2
3450  1607715058442     29.8         0.6
3451  1607715059442     32.4         2.6
3452  1607715060442     27.9        -4.5
3453  1607715061442     33.5         5.6
3454  1607715062442     39.2         5.7
3455  1607715063442     41.9         2.7
3456  1607715064442     44.0         2.1
3457  1607715065442     37.6        -6.4
3458  1607715066442     32.4        -5.2
3459  1607715067442     32.3        -0.1
3460  1607715068442     31.6        -0.7
3461  1607715069442     28.5        -3.1
3462  1607715070442     25.4        -3.1
3463  1607715071442     27.6         2.2
3464  1607715072442     33.5         5.9
3465  1607715073442     30.6        -2.9
3466  1607715074442     37.9         7.3
3467  1607715075442     40.6         2.7
3468  1607715076442     40.5        -0.1
3469  1607715077442     42.3         1.8
3470  1607715078442     40.4        -1.9
3471  1607715079442     41.0         0.6
3472  1607715080442     40.8        -0.2
3473  1607715081442     37.0        -3.8
3474  1607715082442     37.9         0.9
3475  1607715083442     41.1         3.2
3476  1607715084442     34.6        -6.5

In [43]:
df['Cn0_rolling_mean'] = df.groupby('signal_id')['Cn0DbHz'].transform(lambda x: x.rolling(window=5, min_periods=1).mean())

In [44]:
# ============================================================
# EXISTING TEMPORAL FEATURES
# ============================================================

# 1. C/N0 Rolling Mean
df["Cn0_rolling_mean"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).std()
      )
)

# 2. C/N0 Trend
# Current C/N0 - C/N0 from 4 observations ago
df["Cn0_trend"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.diff(4)
      )
)

# 3. C/N0 Trend Mean
# Average of recent 3 C/N0 changes
df["Cn0_trend_mean"] = (
    df.groupby("signal_id")["Cn0_change"]
      .transform(
          lambda x: x.rolling(
              window=3,
              min_periods=1
          ).mean()
      )
)

# 4. Is the signal going UP?
df["is_up"] = (
    df["Cn0_trend_mean"] > 0
)

# 5. Consecutive UP observations
df["up_streak"] = (
    df.groupby("signal_id")["is_up"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

# 6. Is the signal going DOWN?
df["is_down"] = (
    df["Cn0_trend_mean"] < 0
)

# 7. Consecutive DOWN observations
df["down_streak"] = (
    df.groupby("signal_id")["is_down"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

print("All existing temporal features created successfully.")

All existing temporal features created successfully.

In [45]:
display(
    df[
        ["signal_id", "Cn0DbHz", "Cn0_rolling_std"]
    ].head(15)
)

         signal_id  Cn0DbHz  Cn0_rolling_std
0   1_16_GPS_L1_CA     36.4        36.400000
1   1_16_GPS_L1_CA     36.6        36.500000
2   1_16_GPS_L1_CA     36.1        36.366667
3   1_16_GPS_L1_CA     38.2        36.825000
4   1_16_GPS_L1_CA     39.5        37.360000
5   1_16_GPS_L1_CA     38.9        37.860000
6   1_16_GPS_L1_CA     40.0        38.540000
7   1_16_GPS_L1_CA     38.5        39.020000
8   1_16_GPS_L1_CA     35.1        38.400000
9   1_16_GPS_L1_CA     41.4        38.780000
10  1_16_GPS_L1_CA     43.6        39.720000
11  1_16_GPS_L1_CA     40.2        39.760000
12  1_16_GPS_L1_CA     41.2        40.300000
13  1_16_GPS_L1_CA     41.5        41.580000
14  1_16_GPS_L1_CA     41.4        41.580000

In [46]:
# C/N0 Slope
df["Cn0_slope"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(lambda x: x.diff(4) / 4)
)

# C/N0 Acceleration
df["Cn0_acceleration"] = (
    df.groupby("signal_id")["Cn0_slope"]
      .diff()
)

print("Cn0_slope created:", "Cn0_slope" in df.columns)
print("Cn0_acceleration created:", "Cn0_acceleration" in df.columns)

Cn0_slope created: True
Cn0_acceleration created: True

In [47]:
df["Cn0_trend"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(lambda x: x.diff(4))
)

print("Cn0_trend created")

Cn0_trend created

In [48]:
# Feature 4: Minimum C/N0 in recent 5 observations

df["Cn0_min_5"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).min()
      )
)

print("Cn0_min_5 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_min_5"
        ]
    ].head(15)
)

Cn0_min_5 created

         signal_id  Cn0DbHz  Cn0_min_5
0   1_16_GPS_L1_CA     36.4       36.4
1   1_16_GPS_L1_CA     36.6       36.4
2   1_16_GPS_L1_CA     36.1       36.1
3   1_16_GPS_L1_CA     38.2       36.1
4   1_16_GPS_L1_CA     39.5       36.1
5   1_16_GPS_L1_CA     38.9       36.1
6   1_16_GPS_L1_CA     40.0       36.1
7   1_16_GPS_L1_CA     38.5       38.2
8   1_16_GPS_L1_CA     35.1       35.1
9   1_16_GPS_L1_CA     41.4       35.1
10  1_16_GPS_L1_CA     43.6       35.1
11  1_16_GPS_L1_CA     40.2       35.1
12  1_16_GPS_L1_CA     41.2       35.1
13  1_16_GPS_L1_CA     41.5       40.2
14  1_16_GPS_L1_CA     41.4       40.2

In [49]:
# Feature 5: Maximum C/N0 in recent 5 observations

df["Cn0_max_5"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).max()
      )
)

print("Cn0_max_5 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_min_5",
            "Cn0_max_5"
        ]
    ].head(15)
)

Cn0_max_5 created

         signal_id  Cn0DbHz  Cn0_min_5  Cn0_max_5
0   1_16_GPS_L1_CA     36.4       36.4       36.4
1   1_16_GPS_L1_CA     36.6       36.4       36.6
2   1_16_GPS_L1_CA     36.1       36.1       36.6
3   1_16_GPS_L1_CA     38.2       36.1       38.2
4   1_16_GPS_L1_CA     39.5       36.1       39.5
5   1_16_GPS_L1_CA     38.9       36.1       39.5
6   1_16_GPS_L1_CA     40.0       36.1       40.0
7   1_16_GPS_L1_CA     38.5       38.2       40.0
8   1_16_GPS_L1_CA     35.1       35.1       40.0
9   1_16_GPS_L1_CA     41.4       35.1       41.4
10  1_16_GPS_L1_CA     43.6       35.1       43.6
11  1_16_GPS_L1_CA     40.2       35.1       43.6
12  1_16_GPS_L1_CA     41.2       35.1       43.6
13  1_16_GPS_L1_CA     41.5       40.2       43.6
14  1_16_GPS_L1_CA     41.4       40.2       43.6

In [50]:
# Feature 6: C/N0 range in recent 5 observations

df["Cn0_range_5"] = (
    df["Cn0_max_5"] - df["Cn0_min_5"]
)

print("Cn0_range_5 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_min_5",
            "Cn0_max_5",
            "Cn0_range_5"
        ]
    ].head(15)
)

Cn0_range_5 created

         signal_id  Cn0DbHz  Cn0_min_5  Cn0_max_5  Cn0_range_5
0   1_16_GPS_L1_CA     36.4       36.4       36.4          0.0
1   1_16_GPS_L1_CA     36.6       36.4       36.6          0.2
2   1_16_GPS_L1_CA     36.1       36.1       36.6          0.5
3   1_16_GPS_L1_CA     38.2       36.1       38.2          2.1
4   1_16_GPS_L1_CA     39.5       36.1       39.5          3.4
5   1_16_GPS_L1_CA     38.9       36.1       39.5          3.4
6   1_16_GPS_L1_CA     40.0       36.1       40.0          3.9
7   1_16_GPS_L1_CA     38.5       38.2       40.0          1.8
8   1_16_GPS_L1_CA     35.1       35.1       40.0          4.9
9   1_16_GPS_L1_CA     41.4       35.1       41.4          6.3
10  1_16_GPS_L1_CA     43.6       35.1       43.6          8.5
11  1_16_GPS_L1_CA     40.2       35.1       43.6          8.5
12  1_16_GPS_L1_CA     41.2       35.1       43.6          8.5
13  1_16_GPS_L1_CA     41.5       40.2       43.6          3.4
14  1_16_GPS_L1_CA     41.4       40.2       43.6          3.4

In [51]:
# Feature 7: Number of C/N0 decreases in recent 10 observations

df["negative_change_count_10"] = (
    df.groupby("signal_id")["Cn0_change"]
      .transform(
          lambda x: (
              (x < 0)
              .rolling(
                  window=10,
                  min_periods=1
              )
              .sum()
          )
      )
)

print("negative_change_count_10 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_change",
            "negative_change_count_10"
        ]
    ].head(15)
)

negative_change_count_10 created

         signal_id  Cn0DbHz  Cn0_change  negative_change_count_10
0   1_16_GPS_L1_CA     36.4         NaN                       0.0
1   1_16_GPS_L1_CA     36.6         0.2                       0.0
2   1_16_GPS_L1_CA     36.1        -0.5                       1.0
3   1_16_GPS_L1_CA     38.2         2.1                       1.0
4   1_16_GPS_L1_CA     39.5         1.3                       1.0
5   1_16_GPS_L1_CA     38.9        -0.6                       2.0
6   1_16_GPS_L1_CA     40.0         1.1                       2.0
7   1_16_GPS_L1_CA     38.5        -1.5                       3.0
8   1_16_GPS_L1_CA     35.1        -3.4                       4.0
9   1_16_GPS_L1_CA     41.4         6.3                       4.0
10  1_16_GPS_L1_CA     43.6         2.2                       4.0
11  1_16_GPS_L1_CA     40.2        -3.4                       5.0
12  1_16_GPS_L1_CA     41.2         1.0                       4.0
13  1_16_GPS_L1_CA     41.5         0.3                       4.0
14  1_16_GPS_L1_CA     41.4        -0.1                       5.0

In [52]:
# Feature 8: Number of C/N0 increases in recent 10 observations

df["positive_change_count_10"] = (
    df.groupby("signal_id")["Cn0_change"]
      .transform(
          lambda x: (
              (x > 0)
              .rolling(
                  window=10,
                  min_periods=1
              )
              .sum()
          )
      )
)

print("positive_change_count_10 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_change",
            "positive_change_count_10"
        ]
    ].head(15)
)

positive_change_count_10 created

         signal_id  Cn0DbHz  Cn0_change  positive_change_count_10
0   1_16_GPS_L1_CA     36.4         NaN                       0.0
1   1_16_GPS_L1_CA     36.6         0.2                       1.0
2   1_16_GPS_L1_CA     36.1        -0.5                       1.0
3   1_16_GPS_L1_CA     38.2         2.1                       2.0
4   1_16_GPS_L1_CA     39.5         1.3                       3.0
5   1_16_GPS_L1_CA     38.9        -0.6                       3.0
6   1_16_GPS_L1_CA     40.0         1.1                       4.0
7   1_16_GPS_L1_CA     38.5        -1.5                       4.0
8   1_16_GPS_L1_CA     35.1        -3.4                       4.0
9   1_16_GPS_L1_CA     41.4         6.3                       5.0
10  1_16_GPS_L1_CA     43.6         2.2                       6.0
11  1_16_GPS_L1_CA     40.2        -3.4                       5.0
12  1_16_GPS_L1_CA     41.2         1.0                       6.0
13  1_16_GPS_L1_CA     41.5         0.3                       6.0
14  1_16_GPS_L1_CA     41.4        -0.1                       5.0

In [53]:
input_features = [
    # Existing 12
    "Cn0DbHz",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "down_streak",
    "up_streak",
    "PseudorangeRateMetersPerSecond",
    "PseudorangeRate_change",
    "SvElevationDegrees",
    "Elevation_change",
    "SvAzimuthDegrees",
    "Azimuth_change",

    # New 8
    "Cn0_rolling_std",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10"
]

print("Total input features:", len(input_features))
print(input_features)

Total input features: 20
['Cn0DbHz', 'Cn0_change', 'Cn0_trend', 'Cn0_trend_mean', 'down_streak', 'up_streak', 'PseudorangeRateMetersPerSecond', 'PseudorangeRate_change', 'SvElevationDegrees', 'Elevation_change', 'SvAzimuthDegrees', 'Azimuth_change', 'Cn0_rolling_std', 'Cn0_slope', 'Cn0_acceleration', 'Cn0_min_5', 'Cn0_max_5', 'Cn0_range_5', 'negative_change_count_10', 'positive_change_count_10']

In [54]:
missing_fectures =[
    f for f in input_features
    if f not in df.columns

]
print("missing",missing_fectures)

missing []

In [55]:
print("NaN count in 20 input features:")
print(df[input_features].isna().sum())

print("\nTotal NaN values:")
print(df[input_features].isna().sum().sum())

NaN count in 20 input features:
Cn0DbHz                             0
Cn0_change                         43
Cn0_trend                         172
Cn0_trend_mean                     43
down_streak                         0
up_streak                           0
PseudorangeRateMetersPerSecond      0
PseudorangeRate_change             43
SvElevationDegrees                  0
Elevation_change                   43
SvAzimuthDegrees                    0
Azimuth_change                     43
Cn0_rolling_std                     0
Cn0_slope                         172
Cn0_acceleration                  215
Cn0_min_5                           0
Cn0_max_5                           0
Cn0_range_5                         0
negative_change_count_10            0
positive_change_count_10            0
dtype: int64

Total NaN values:
774

In [56]:
df = df.dropna(subset=input_features).reset_index(drop=True)

print("Shape after removing NaNs:", df.shape)

print("\nRemaining NaNs:")
print(df[input_features].isna().sum().sum())

Shape after removing NaNs: (44061, 33)

Remaining NaNs:
0

In [57]:
import os

corrected_dir = "/content/gnss_features_v2"
os.makedirs(corrected_dir, exist_ok=True)

print("Output folder:", corrected_dir)

Output folder: /content/gnss_features_v2

In [58]:
import zipfile
import os

zip_path = "/content/drive/MyDrive/Gnns_kaggle_2324/smartphone-decimeter-2023.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    gnss_files = [
        f for f in z.namelist()
        if f.endswith("/device_gnss.csv")
    ]

print("Total GNSS files found:", len(gnss_files))
print("First file:", gnss_files[0])
print("Last file:", gnss_files[-1])

Total GNSS files found: 196
First file: sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
Last file: sdc2023/train/2023-09-07-22-48-us-ca-routebc2/pixel5a/device_gnss.csv

In [59]:
# ============================================================
# REGENERATE ALL 196 FILES WITH CORRECTED 20 FEATURES
# ============================================================

import os
import zipfile
import pandas as pd
import numpy as np

zip_path = "/content/drive/MyDrive/Gnns_kaggle_2324/smartphone-decimeter-2023.zip"
corrected_dir = "/content/gnss_features_v2"

os.makedirs(corrected_dir, exist_ok=True)

# ------------------------------------------------------------
# 20 MODEL FEATURES
# ------------------------------------------------------------

input_features = [
    "Cn0DbHz",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "down_streak",
    "up_streak",
    "PseudorangeRateMetersPerSecond",
    "PseudorangeRate_change",
    "SvElevationDegrees",
    "Elevation_change",
    "SvAzimuthDegrees",
    "Azimuth_change",
    "Cn0_rolling_std",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10"
]

# ------------------------------------------------------------
# FIND ALL 196 GNSS FILES
# ------------------------------------------------------------

with zipfile.ZipFile(zip_path, "r") as z:

    gnss_files = sorted([
        f for f in z.namelist()
        if f.endswith("/device_gnss.csv")
    ])

print("Total GNSS files:", len(gnss_files))

assert len(gnss_files) == 196, \
    f"Expected 196 files, found {len(gnss_files)}"

# ------------------------------------------------------------
# PROCESS EACH FILE
# ------------------------------------------------------------

for idx, file_path in enumerate(gnss_files, start=1):

    print(f"\n[{idx}/196] Processing:")
    print(file_path)

    # --------------------------------------------------------
    # READ ONE FILE ONLY
    # --------------------------------------------------------

    with zipfile.ZipFile(zip_path, "r") as z:
        df = pd.read_csv(z.open(file_path))

    # --------------------------------------------------------
    # SELECT REQUIRED RAW FEATURES
    # --------------------------------------------------------

    raw_features = [
        "ConstellationType",
        "Svid",
        "SignalType",
        "utcTimeMillis",
        "Cn0DbHz",
        "RawPseudorangeMeters",
        "PseudorangeRateMetersPerSecond",
        "AccumulatedDeltaRangeMeters",
        "SvElevationDegrees",
        "SvAzimuthDegrees"
    ]

    df = df[raw_features].copy()

    # --------------------------------------------------------
    # CREATE SIGNAL ID
    # --------------------------------------------------------

    df["signal_id"] = (
        df["ConstellationType"].astype(str)
        + "_"
        + df["Svid"].astype(str)
        + "_"
        + df["SignalType"].astype(str)
    )

    # --------------------------------------------------------
    # SORT BY SIGNAL + TIME
    # --------------------------------------------------------

    df = df.sort_values(
        ["signal_id", "utcTimeMillis"]
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # INTERPOLATION
    # --------------------------------------------------------

    numeric_cols = [
        "Cn0DbHz",
        "RawPseudorangeMeters",
        "PseudorangeRateMetersPerSecond",
        "AccumulatedDeltaRangeMeters",
        "SvElevationDegrees",
        "SvAzimuthDegrees"
    ]

    df[numeric_cols] = (
        df.groupby("signal_id")[numeric_cols]
          .transform(
              lambda x: x.interpolate(
                  method="linear",
                  limit=2,
                  limit_direction="both"
              )
          )
    )

    df = df.dropna(
        subset=numeric_cols
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # C/N0 CHANGE
    # --------------------------------------------------------

    df["Cn0_change"] = (
        df.groupby("signal_id")["Cn0DbHz"].diff()
    )

    # --------------------------------------------------------
    # C/N0 ROLLING MEAN
    # --------------------------------------------------------

    df["Cn0_rolling_mean"] = (
        df.groupby("signal_id")["Cn0DbHz"]
          .transform(
              lambda x: x.rolling(
                  window=5,
                  min_periods=1
              ).mean()
          )
    )

    # --------------------------------------------------------
    # C/N0 TREND
    # --------------------------------------------------------

    df["Cn0_trend"] = (
        df.groupby("signal_id")["Cn0DbHz"]
          .transform(
              lambda x: x.diff(4)
          )
    )

    # --------------------------------------------------------
    # C/N0 TREND MEAN
    # --------------------------------------------------------

    df["Cn0_trend_mean"] = (
        df.groupby("signal_id")["Cn0_change"]
          .transform(
              lambda x: x.rolling(
                  window=3,
                  min_periods=1
              ).mean()
          )
    )

    # --------------------------------------------------------
    # UP / DOWN
    # --------------------------------------------------------

    df["is_up"] = (
        df["Cn0_trend_mean"] > 0
    )

    df["up_streak"] = (
        df.groupby("signal_id")["is_up"]
          .transform(
              lambda x:
                  x.astype(int)
                   .groupby((x != x.shift()).cumsum())
                   .cumsum()
          )
    )

    df["is_down"] = (
        df["Cn0_trend_mean"] < 0
    )

    df["down_streak"] = (
        df.groupby("signal_id")["is_down"]
          .transform(
              lambda x:
                  x.astype(int)
                   .groupby((x != x.shift()).cumsum())
                   .cumsum()
          )
    )

    # --------------------------------------------------------
    # NEW FEATURE 1: ROLLING STD
    # --------------------------------------------------------

    df["Cn0_rolling_std"] = (
        df.groupby("signal_id")["Cn0DbHz"]
          .transform(
              lambda x: x.rolling(
                  window=5,
                  min_periods=2
              ).std()
          )
    )

    # --------------------------------------------------------
    # NEW FEATURE 2: SLOPE
    # --------------------------------------------------------

    df["Cn0_slope"] = (
        df.groupby("signal_id")["Cn0DbHz"]
          .transform(
              lambda x: x.diff(4) / 4
          )
    )

    # --------------------------------------------------------
    # NEW FEATURE 3: ACCELERATION
    # --------------------------------------------------------

    df["Cn0_acceleration"] = (
        df.groupby("signal_id")["Cn0_slope"].diff()
    )

    # --------------------------------------------------------
    # TIME GAP
    # --------------------------------------------------------

    df["time_gap"] = (
        df.groupby("signal_id")["utcTimeMillis"].diff()
    )

    # --------------------------------------------------------
    # PSEUDORANGE CHANGE
    # --------------------------------------------------------

    df["Pseudorange_change"] = (
        df.groupby("signal_id")[
            "RawPseudorangeMeters"
        ].diff()
    )

    # --------------------------------------------------------
    # PSEUDORANGE RATE CHANGE
    # --------------------------------------------------------

    df["PseudorangeRate_change"] = (
        df.groupby("signal_id")[
            "PseudorangeRateMetersPerSecond"
        ].diff()
    )

    # --------------------------------------------------------
    # ELEVATION CHANGE
    # --------------------------------------------------------

    df["Elevation_change"] = (
        df.groupby("signal_id")[
            "SvElevationDegrees"
        ].diff()
    )

    # --------------------------------------------------------
    # CIRCULAR AZIMUTH CHANGE
    # --------------------------------------------------------

    df["Azimuth_change"] = (
        (
            df.groupby("signal_id")[
                "SvAzimuthDegrees"
            ].diff() + 180
        ) % 360
    ) - 180

    df["Azimuth_change"] = (
        df["Azimuth_change"].clip(-180, 180)
    )

    # --------------------------------------------------------
    # NEW FEATURE 4: MIN
    # --------------------------------------------------------

    df["Cn0_min_5"] = (
        df.groupby("signal_id")["Cn0DbHz"]
          .transform(
              lambda x: x.rolling(
                  window=5,
                  min_periods=1
              ).min()
          )
    )

    # --------------------------------------------------------
    # NEW FEATURE 5: MAX
    # --------------------------------------------------------

    df["Cn0_max_5"] = (
        df.groupby("signal_id")["Cn0DbHz"]
          .transform(
              lambda x: x.rolling(
                  window=5,
                  min_periods=1
              ).max()
          )
    )

    # --------------------------------------------------------
    # NEW FEATURE 6: RANGE
    # --------------------------------------------------------

    df["Cn0_range_5"] = (
        df["Cn0_max_5"] - df["Cn0_min_5"]
    )

    # --------------------------------------------------------
    # NEW FEATURE 7: NEGATIVE COUNT
    # --------------------------------------------------------

    df["negative_change_count_10"] = (
        df.groupby("signal_id")["Cn0_change"]
          .transform(
              lambda x:
                  (x < 0)
                  .rolling(
                      window=10,
                      min_periods=1
                  )
                  .sum()
          )
    )

    # --------------------------------------------------------
    # NEW FEATURE 8: POSITIVE COUNT
    # --------------------------------------------------------

    df["positive_change_count_10"] = (
        df.groupby("signal_id")["Cn0_change"]
          .transform(
              lambda x:
                  (x > 0)
                  .rolling(
                      window=10,
                      min_periods=1
                  )
                  .sum()
          )
    )

    # REMOVE ROWS WHERE 20 FEATURES ARE INCOMPLETE

    df = df.dropna(
        subset=input_features
    ).reset_index(drop=True)


    # VERIFY

    missing_features = [
        f for f in input_features
        if f not in df.columns
    ]

    assert not missing_features, \
        f"Missing features: {missing_features}"

    remaining_nan = (
        df[input_features]
        .isna()
        .sum()
        .sum()
    )

    assert remaining_nan == 0, \
        f"Remaining NaNs: {remaining_nan}"

    output_name = f"gnss_{idx:03d}.parquet"

    output_path = os.path.join(
        corrected_dir,
        output_name
    )

    df.to_parquet(
        output_path,
        index=False
    )

    print(
        f"Saved {output_name} | "
        f"Rows: {len(df)} | "
        f"Columns: {len(df.columns)}"
    )

print("\n========================================")
print("DONE — ALL 196 FILES PROCESSED")
print("========================================")

Total GNSS files: 196

[1/196] Processing:
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
Saved gnss_001.parquet | Rows: 44061 | Columns: 32

[2/196] Processing:
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_gnss.csv
Saved gnss_002.parquet | Rows: 58296 | Columns: 32

[3/196] Processing:
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_003.parquet | Rows: 33592 | Columns: 32

[4/196] Processing:
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_gnss.csv
Saved gnss_004.parquet | Rows: 41353 | Columns: 32

[5/196] Processing:
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_gnss.csv
Saved gnss_005.parquet | Rows: 63764 | Columns: 32

[6/196] Processing:
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_006.parquet | Rows: 81044 | Columns: 32

[7/196] Processing:
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_gnss.csv
Saved gnss_007.parquet | Rows: 42690 | Columns: 32

[8/196] Processing:
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_008.parquet | Rows: 37195 | Columns: 32

[9/196] Processing:
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_gnss.csv
Saved gnss_009.parquet | Rows: 55634 | Columns: 32

[10/196] Processing:
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_gnss.csv
Saved gnss_010.parquet | Rows: 71587 | Columns: 32

[11/196] Processing:
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_gnss.csv
Saved gnss_011.parquet | Rows: 89770 | Columns: 32

[12/196] Processing:
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_gnss.csv
Saved gnss_012.parquet | Rows: 145036 | Columns: 32

[13/196] Processing:
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_gnss.csv
Saved gnss_013.parquet | Rows: 114813 | Columns: 32

[14/196] Processing:
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_014.parquet | Rows: 54988 | Columns: 32

[15/196] Processing:
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_gnss.csv
Saved gnss_015.parquet | Rows: 36985 | Columns: 32

[16/196] Processing:
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_gnss.csv
Saved gnss_016.parquet | Rows: 83179 | Columns: 32

[17/196] Processing:
sdc2023/test/2022-04-04-16-31-us-ca-lax-x/pixel5/device_gnss.csv
Saved gnss_017.parquet | Rows: 79995 | Columns: 32

[18/196] Processing:
sdc2023/test/2022-04-22-20-11-us-ca-ebf-y/pixel5/device_gnss.csv
Saved gnss_018.parquet | Rows: 39580 | Columns: 32

[19/196] Processing:
sdc2023/test/2022-04-25-21-04-us-ca-ebf-x/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_019.parquet | Rows: 62060 | Columns: 32

[20/196] Processing:
sdc2023/test/2022-04-25-22-36-us-ca-ebf-z/pixel5/device_gnss.csv
Saved gnss_020.parquet | Rows: 47890 | Columns: 32

[21/196] Processing:
sdc2023/test/2022-04-27-18-16-us-ca-ebf-zz/pixel5/device_gnss.csv
Saved gnss_021.parquet | Rows: 46486 | Columns: 32

[22/196] Processing:
sdc2023/test/2022-04-27-19-23-us-ca-ebf-xx/pixel5/device_gnss.csv
Saved gnss_022.parquet | Rows: 41761 | Columns: 32

[23/196] Processing:
sdc2023/test/2022-04-27-21-55-us-ca-ebf-ww/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_023.parquet | Rows: 44600 | Columns: 32

[24/196] Processing:
sdc2023/test/2022-05-12-20-19-us-ca-mtv-pe1/samsunga325g/device_gnss.csv
Saved gnss_024.parquet | Rows: 21378 | Columns: 32

[25/196] Processing:
sdc2023/test/2022-06-22-20-12-us-ca-lax-hh/samsunga325g/device_gnss.csv
Saved gnss_025.parquet | Rows: 24188 | Columns: 32

[26/196] Processing:
sdc2023/test/2022-06-28-20-56-us-ca-sjc-r/samsunga32/device_gnss.csv
Saved gnss_026.parquet | Rows: 29360 | Columns: 32

[27/196] Processing:
sdc2023/test/2022-07-12-18-37-us-ca-mtv-b/sm-a325f/device_gnss.csv
Saved gnss_027.parquet | Rows: 40821 | Columns: 32

[28/196] Processing:
sdc2023/test/2022-10-06-20-46-us-ca-sjc-r/sm-a205u/device_gnss.csv
Saved gnss_028.parquet | Rows: 66725 | Columns: 32

[29/196] Processing:
sdc2023/test/2023-04-27-19-25-us-ca-mtv-pe1/pixel5/device_gnss.csv
Saved gnss_029.parquet | Rows: 36562 | Columns: 32

[30/196] Processing:
sdc2023/test/2023-04-27-20-55-us-ca-sjc-q/pixel5/device_gnss.csv
Saved gnss_030.parquet | Rows: 43375 | Columns: 32

[31/196] Processing:
sdc2023/test/2023-05-02-19-24-us-ca-sjc-we1/pixel7pro/device_gnss.csv
Saved gnss_031.parquet | Rows: 54468 | Columns: 32

[32/196] Processing:
sdc2023/test/2023-05-02-20-33-us-ca-mtv-xe1/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_032.parquet | Rows: 55547 | Columns: 32

[33/196] Processing:
sdc2023/test/2023-05-09-23-10-us-ca-sjc-r/sm-a505u/device_gnss.csv
Saved gnss_033.parquet | Rows: 55577 | Columns: 32

[34/196] Processing:
sdc2023/test/2023-05-23-21-06-us-ca-mtv-de1/pixel5/device_gnss.csv
Saved gnss_034.parquet | Rows: 74817 | Columns: 32

[35/196] Processing:
sdc2023/test/2023-05-23-22-16-us-ca-mtv-ie2/pixel6pro/device_gnss.csv
Saved gnss_035.parquet | Rows: 31726 | Columns: 32

[36/196] Processing:
sdc2023/test/2023-05-25-17-32-us-ca-pao-j/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_036.parquet | Rows: 29279 | Columns: 32

[37/196] Processing:
sdc2023/test/2023-05-25-21-50-us-ca-sjc-ke2/sm-s908b/device_gnss.csv
Saved gnss_037.parquet | Rows: 86836 | Columns: 32

[38/196] Processing:
sdc2023/test/2023-05-26-21-23-us-ca-sjc-be2/pixel5/device_gnss.csv
Saved gnss_038.parquet | Rows: 47983 | Columns: 32

[39/196] Processing:
sdc2023/test/2023-06-06-22-43-us-ca-sjc-he2/pixel5/device_gnss.csv
Saved gnss_039.parquet | Rows: 54138 | Columns: 32

[40/196] Processing:
sdc2023/test/2023-06-15-18-49-us-ca-sjc-ce1/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_040.parquet | Rows: 40020 | Columns: 32

[41/196] Processing:
sdc2023/train/2020-06-25-00-34-us-ca-mtv-sb-101/pixel4/device_gnss.csv
Saved gnss_041.parquet | Rows: 46173 | Columns: 32

[42/196] Processing:
sdc2023/train/2020-06-25-00-34-us-ca-mtv-sb-101/pixel4xl/device_gnss.csv
Saved gnss_042.parquet | Rows: 48010 | Columns: 32

[43/196] Processing:
sdc2023/train/2020-07-08-22-28-us-ca/pixel4/device_gnss.csv
Saved gnss_043.parquet | Rows: 69029 | Columns: 32

[44/196] Processing:
sdc2023/train/2020-07-08-22-28-us-ca/pixel4xl/device_gnss.csv
Saved gnss_044.parquet | Rows: 72963 | Columns: 32

[45/196] Processing:
sdc2023/train/2020-07-17-22-27-us-ca-mtv-sf-280/pixel4/device_gnss.csv
Saved gnss_045.parquet | Rows: 63655 | Columns: 32

[46/196] Processing:
sdc2023/train/2020-07-17-23-13-us-ca-sf-mtv-280/pixel4/device_gnss.csv
Saved gnss_046.parquet | Rows: 53364 | Columns: 32

[47/196] Processing:
sdc2023/train/2020-07-17-23-13-us-ca-sf-mtv-280/pixel4xl/device_gnss.csv
Saved gnss_047.parquet | Rows: 33340 | Columns: 32

[48/196] Processing:
sdc2023/train/2020-08-04-00-19-us-ca-sb-mtv-101/pixel4/device_gnss.csv
Saved gnss_048.parquet | Rows: 54494 | Columns: 32

[49/196] Processing:
sdc2023/train/2020-08-04-00-20-us-ca-sb-mtv-101/pixel4xl/device_gnss.csv
Saved gnss_049.parquet | Rows: 52960 | Columns: 32

[50/196] Processing:
sdc2023/train/2020-08-04-00-20-us-ca-sb-mtv-101/pixel5/device_gnss.csv
Saved gnss_050.parquet | Rows: 49181 | Columns: 32

[51/196] Processing:
sdc2023/train/2020-08-13-21-41-us-ca-mtv-sf-280/pixel4/device_gnss.csv
Saved gnss_051.parquet | Rows: 53921 | Columns: 32

[52/196] Processing:
sdc2023/train/2020-08-13-21-41-us-ca-mtv-sf-280/pixel4xl/device_gnss.csv
Saved gnss_052.parquet | Rows: 58318 | Columns: 32

[53/196] Processing:
sdc2023/train/2020-08-13-21-42-us-ca-mtv-sf-280/pixel5/device_gnss.csv
Saved gnss_053.parquet | Rows: 55319 | Columns: 32

[54/196] Processing:
sdc2023/train/2020-12-10-22-17-us-ca-sjc-c/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_054.parquet | Rows: 50518 | Columns: 32

[55/196] Processing:
sdc2023/train/2020-12-10-22-52-us-ca-sjc-c/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_055.parquet | Rows: 47763 | Columns: 32

[56/196] Processing:
sdc2023/train/2020-12-10-22-52-us-ca-sjc-c/pixel4/device_gnss.csv
Saved gnss_056.parquet | Rows: 45210 | Columns: 32

[57/196] Processing:
sdc2023/train/2020-12-10-22-52-us-ca-sjc-c/pixel4xl/device_gnss.csv
Saved gnss_057.parquet | Rows: 45510 | Columns: 32

[58/196] Processing:
sdc2023/train/2020-12-10-22-52-us-ca-sjc-c/pixel5/device_gnss.csv
Saved gnss_058.parquet | Rows: 42338 | Columns: 32

[59/196] Processing:
sdc2023/train/2021-01-04-21-50-us-ca-e1highway280driveroutea/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_059.parquet | Rows: 65967 | Columns: 32

[60/196] Processing:
sdc2023/train/2021-01-04-21-50-us-ca-e1highway280driveroutea/pixel4/device_gnss.csv
Saved gnss_060.parquet | Rows: 71088 | Columns: 32

[61/196] Processing:
sdc2023/train/2021-01-04-21-50-us-ca-e1highway280driveroutea/pixel5/device_gnss.csv
Saved gnss_061.parquet | Rows: 75536 | Columns: 32

[62/196] Processing:
sdc2023/train/2021-01-04-22-40-us-ca-mtv-a/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_062.parquet | Rows: 61872 | Columns: 32

[63/196] Processing:
sdc2023/train/2021-01-04-22-40-us-ca-mtv-a/pixel4/device_gnss.csv
Saved gnss_063.parquet | Rows: 68841 | Columns: 32

[64/196] Processing:
sdc2023/train/2021-01-04-22-40-us-ca-mtv-a/pixel5/device_gnss.csv
Saved gnss_064.parquet | Rows: 74374 | Columns: 32

[65/196] Processing:
sdc2023/train/2021-01-05-21-12-us-ca-mtv-d/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_065.parquet | Rows: 42800 | Columns: 32

[66/196] Processing:
sdc2023/train/2021-01-05-21-12-us-ca-mtv-d/pixel4/device_gnss.csv
Saved gnss_066.parquet | Rows: 47646 | Columns: 32

[67/196] Processing:
sdc2023/train/2021-01-05-21-52-us-ca-mtv-d/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_067.parquet | Rows: 37272 | Columns: 32

[68/196] Processing:
sdc2023/train/2021-01-05-21-52-us-ca-mtv-d/pixel4/device_gnss.csv
Saved gnss_068.parquet | Rows: 43191 | Columns: 32

[69/196] Processing:
sdc2023/train/2021-03-10-23-13-us-ca-mtv-h/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_069.parquet | Rows: 43334 | Columns: 32

[70/196] Processing:
sdc2023/train/2021-03-10-23-13-us-ca-mtv-h/pixel5/device_gnss.csv
Saved gnss_070.parquet | Rows: 50008 | Columns: 32

[71/196] Processing:
sdc2023/train/2021-03-16-18-59-us-ca-mtv-a/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_071.parquet | Rows: 68198 | Columns: 32

[72/196] Processing:
sdc2023/train/2021-03-16-18-59-us-ca-mtv-a/pixel5/device_gnss.csv
Saved gnss_072.parquet | Rows: 86760 | Columns: 32

[73/196] Processing:
sdc2023/train/2021-03-16-18-59-us-ca-mtv-a/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_073.parquet | Rows: 69467 | Columns: 32

[74/196] Processing:
sdc2023/train/2021-03-16-19-00-us-ca-mtv-a/pixel4xl/device_gnss.csv
Saved gnss_074.parquet | Rows: 86324 | Columns: 32

[75/196] Processing:
sdc2023/train/2021-03-16-20-40-us-ca-mtv-b/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_075.parquet | Rows: 49210 | Columns: 32

[76/196] Processing:
sdc2023/train/2021-03-16-20-40-us-ca-mtv-b/pixel4xl/device_gnss.csv
Saved gnss_076.parquet | Rows: 63091 | Columns: 32

[77/196] Processing:
sdc2023/train/2021-03-16-20-40-us-ca-mtv-b/pixel5/device_gnss.csv
Saved gnss_077.parquet | Rows: 61109 | Columns: 32

[78/196] Processing:
sdc2023/train/2021-04-02-20-43-us-ca-mtv-f/mi8/device_gnss.csv
Saved gnss_078.parquet | Rows: 75003 | Columns: 32

[79/196] Processing:
sdc2023/train/2021-04-02-20-43-us-ca-mtv-f/pixel5/device_gnss.csv
Saved gnss_079.parquet | Rows: 97130 | Columns: 32

[80/196] Processing:
sdc2023/train/2021-04-02-20-43-us-ca-mtv-f/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_080.parquet | Rows: 79160 | Columns: 32

[81/196] Processing:
sdc2023/train/2021-04-08-21-28-us-ca-mtv-k/pixel5/device_gnss.csv
Saved gnss_081.parquet | Rows: 34112 | Columns: 32

[82/196] Processing:
sdc2023/train/2021-04-08-21-28-us-ca-mtv-k/sm-g988b/device_gnss.csv
Saved gnss_082.parquet | Rows: 32222 | Columns: 32

[83/196] Processing:
sdc2023/train/2021-04-26-23-38-us-ca-mtv-h/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_083.parquet | Rows: 98315 | Columns: 32

[84/196] Processing:
sdc2023/train/2021-04-26-23-38-us-ca-mtv-h/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_084.parquet | Rows: 97052 | Columns: 32

[85/196] Processing:
sdc2023/train/2021-07-14-20-50-us-ca-mtv-e/pixel4/device_gnss.csv
Saved gnss_085.parquet | Rows: 42344 | Columns: 32

[86/196] Processing:
sdc2023/train/2021-07-14-20-50-us-ca-mtv-e/pixel5/device_gnss.csv
Saved gnss_086.parquet | Rows: 49887 | Columns: 32

[87/196] Processing:
sdc2023/train/2021-07-14-20-50-us-ca-mtv-e/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_087.parquet | Rows: 38755 | Columns: 32

[88/196] Processing:
sdc2023/train/2021-07-19-20-49-us-ca-mtv-a/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_088.parquet | Rows: 62022 | Columns: 32

[89/196] Processing:
sdc2023/train/2021-07-19-20-49-us-ca-mtv-a/pixel4/device_gnss.csv
Saved gnss_089.parquet | Rows: 66969 | Columns: 32

[90/196] Processing:
sdc2023/train/2021-07-19-20-49-us-ca-mtv-a/pixel5/device_gnss.csv
Saved gnss_090.parquet | Rows: 78520 | Columns: 32

[91/196] Processing:
sdc2023/train/2021-07-19-20-49-us-ca-mtv-a/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_091.parquet | Rows: 61784 | Columns: 32

[92/196] Processing:
sdc2023/train/2021-07-27-19-49-us-ca-mtv-b/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_092.parquet | Rows: 57393 | Columns: 32

[93/196] Processing:
sdc2023/train/2021-07-27-19-49-us-ca-mtv-b/pixel4/device_gnss.csv
Saved gnss_093.parquet | Rows: 73664 | Columns: 32

[94/196] Processing:
sdc2023/train/2021-07-27-19-49-us-ca-mtv-b/pixel5/device_gnss.csv
Saved gnss_094.parquet | Rows: 76472 | Columns: 32

[95/196] Processing:
sdc2023/train/2021-08-04-20-40-us-ca-sjc-c/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_095.parquet | Rows: 48443 | Columns: 32

[96/196] Processing:
sdc2023/train/2021-08-24-20-32-us-ca-mtv-h/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_096.parquet | Rows: 99903 | Columns: 32

[97/196] Processing:
sdc2023/train/2021-08-24-20-32-us-ca-mtv-h/pixel4/device_gnss.csv
Saved gnss_097.parquet | Rows: 100011 | Columns: 32

[98/196] Processing:
sdc2023/train/2021-08-24-20-32-us-ca-mtv-h/pixel5/device_gnss.csv
Saved gnss_098.parquet | Rows: 111562 | Columns: 32

[99/196] Processing:
sdc2023/train/2021-08-24-20-32-us-ca-mtv-h/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_099.parquet | Rows: 98256 | Columns: 32

[100/196] Processing:
sdc2023/train/2021-12-07-19-22-us-ca-lax-d/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_100.parquet | Rows: 53631 | Columns: 32

[101/196] Processing:
sdc2023/train/2021-12-07-19-22-us-ca-lax-d/pixel5/device_gnss.csv
Saved gnss_101.parquet | Rows: 55129 | Columns: 32

[102/196] Processing:
sdc2023/train/2021-12-07-19-22-us-ca-lax-d/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_102.parquet | Rows: 53538 | Columns: 32

[103/196] Processing:
sdc2023/train/2021-12-07-19-22-us-ca-lax-d/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_103.parquet | Rows: 55377 | Columns: 32

[104/196] Processing:
sdc2023/train/2021-12-07-22-21-us-ca-lax-g/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_104.parquet | Rows: 46463 | Columns: 32

[105/196] Processing:
sdc2023/train/2021-12-07-22-21-us-ca-lax-g/pixel5/device_gnss.csv
Saved gnss_105.parquet | Rows: 47220 | Columns: 32

[106/196] Processing:
sdc2023/train/2021-12-07-22-21-us-ca-lax-g/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_106.parquet | Rows: 45386 | Columns: 32

[107/196] Processing:
sdc2023/train/2021-12-07-22-21-us-ca-lax-g/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_107.parquet | Rows: 44889 | Columns: 32

[108/196] Processing:
sdc2023/train/2021-12-08-17-22-us-ca-lax-a/pixel5/device_gnss.csv
Saved gnss_108.parquet | Rows: 50403 | Columns: 32

[109/196] Processing:
sdc2023/train/2021-12-08-17-22-us-ca-lax-a/pixel6pro/device_gnss.csv
Saved gnss_109.parquet | Rows: 50897 | Columns: 32

[110/196] Processing:
sdc2023/train/2021-12-08-18-52-us-ca-lax-b/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_110.parquet | Rows: 44455 | Columns: 32

[111/196] Processing:
sdc2023/train/2021-12-08-18-52-us-ca-lax-b/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_111.parquet | Rows: 45778 | Columns: 32

[112/196] Processing:
sdc2023/train/2021-12-08-20-28-us-ca-lax-c/pixel5/device_gnss.csv
Saved gnss_112.parquet | Rows: 26545 | Columns: 32

[113/196] Processing:
sdc2023/train/2021-12-08-20-28-us-ca-lax-c/pixel6pro/device_gnss.csv
Saved gnss_113.parquet | Rows: 25821 | Columns: 32

[114/196] Processing:
sdc2023/train/2021-12-08-20-28-us-ca-lax-c/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_114.parquet | Rows: 25563 | Columns: 32

[115/196] Processing:
sdc2023/train/2021-12-09-17-06-us-ca-lax-e/pixel5/device_gnss.csv
Saved gnss_115.parquet | Rows: 38670 | Columns: 32

[116/196] Processing:
sdc2023/train/2021-12-09-17-06-us-ca-lax-e/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_116.parquet | Rows: 38551 | Columns: 32

[117/196] Processing:
sdc2023/train/2022-01-11-18-48-us-ca-mtv-n/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_117.parquet | Rows: 28759 | Columns: 32

[118/196] Processing:
sdc2023/train/2022-01-11-18-48-us-ca-mtv-n/pixel5/device_gnss.csv
Saved gnss_118.parquet | Rows: 28350 | Columns: 32

[119/196] Processing:
sdc2023/train/2022-01-11-18-48-us-ca-mtv-n/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_119.parquet | Rows: 26007 | Columns: 32

[120/196] Processing:
sdc2023/train/2022-01-26-20-02-us-ca-mtv-pe1/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_120.parquet | Rows: 56675 | Columns: 32

[121/196] Processing:
sdc2023/train/2022-01-26-20-02-us-ca-mtv-pe1/pixel5/device_gnss.csv
Saved gnss_121.parquet | Rows: 54488 | Columns: 32

[122/196] Processing:
sdc2023/train/2022-01-26-20-02-us-ca-mtv-pe1/sm-g988b/device_gnss.csv
Saved gnss_122.parquet | Rows: 55082 | Columns: 32

[123/196] Processing:
sdc2023/train/2022-02-24-18-29-us-ca-lax-o/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_123.parquet | Rows: 76934 | Columns: 32

[124/196] Processing:
sdc2023/train/2022-02-24-18-29-us-ca-lax-o/pixel5/device_gnss.csv
Saved gnss_124.parquet | Rows: 75146 | Columns: 32

[125/196] Processing:
sdc2023/train/2022-02-24-18-29-us-ca-lax-o/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_125.parquet | Rows: 65232 | Columns: 32

[126/196] Processing:
sdc2023/train/2022-04-01-18-22-us-ca-lax-t/mi8/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_126.parquet | Rows: 46264 | Columns: 32

[127/196] Processing:
sdc2023/train/2022-04-01-18-22-us-ca-lax-t/pixel5/device_gnss.csv
Saved gnss_127.parquet | Rows: 50474 | Columns: 32

[128/196] Processing:
sdc2023/train/2022-04-01-18-22-us-ca-lax-t/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_128.parquet | Rows: 43322 | Columns: 32

[129/196] Processing:
sdc2023/train/2022-05-13-20-57-us-ca-mtv-pe1/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_129.parquet | Rows: 57878 | Columns: 32

[130/196] Processing:
sdc2023/train/2022-05-13-20-57-us-ca-mtv-pe1/samsungs21ultra/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_130.parquet | Rows: 66291 | Columns: 32

[131/196] Processing:
sdc2023/train/2022-05-13-20-57-us-ca-mtv-pe1/sm-g988b/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_131.parquet | Rows: 69556 | Columns: 32

[132/196] Processing:
sdc2023/train/2022-07-26-21-01-us-ca-sjc-s/pixel5/device_gnss.csv
Saved gnss_132.parquet | Rows: 49714 | Columns: 32

[133/196] Processing:
sdc2023/train/2022-07-26-21-01-us-ca-sjc-s/samsunga325g/device_gnss.csv
Saved gnss_133.parquet | Rows: 25800 | Columns: 32

[134/196] Processing:
sdc2023/train/2022-08-04-20-07-us-ca-sjc-q/mi8/device_gnss.csv
Saved gnss_134.parquet | Rows: 47451 | Columns: 32

[135/196] Processing:
sdc2023/train/2022-08-04-20-07-us-ca-sjc-q/pixel5/device_gnss.csv
Saved gnss_135.parquet | Rows: 49079 | Columns: 32

[136/196] Processing:
sdc2023/train/2022-08-04-20-07-us-ca-sjc-q/sm-a325f/device_gnss.csv
Saved gnss_136.parquet | Rows: 22339 | Columns: 32

[137/196] Processing:
sdc2023/train/2022-10-06-21-51-us-ca-mtv-n/sm-a205u/device_gnss.csv
Saved gnss_137.parquet | Rows: 44967 | Columns: 32

[138/196] Processing:
sdc2023/train/2022-10-06-21-51-us-ca-mtv-n/sm-a217m/device_gnss.csv
Saved gnss_138.parquet | Rows: 33248 | Columns: 32

[139/196] Processing:
sdc2023/train/2022-10-06-21-51-us-ca-mtv-n/sm-a325f/device_gnss.csv
Saved gnss_139.parquet | Rows: 19113 | Columns: 32

[140/196] Processing:
sdc2023/train/2022-11-15-00-53-us-ca-mtv-a/pixel5/device_gnss.csv
Saved gnss_140.parquet | Rows: 36959 | Columns: 32

[141/196] Processing:
sdc2023/train/2022-11-15-00-53-us-ca-mtv-a/pixel7/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_141.parquet | Rows: 34486 | Columns: 32

[142/196] Processing:
sdc2023/train/2022-11-15-00-53-us-ca-mtv-a/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_142.parquet | Rows: 33713 | Columns: 32

[143/196] Processing:
sdc2023/train/2023-03-08-21-34-us-ca-mtv-u/pixel5/device_gnss.csv
Saved gnss_143.parquet | Rows: 35186 | Columns: 32

[144/196] Processing:
sdc2023/train/2023-03-08-21-34-us-ca-mtv-u/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_144.parquet | Rows: 30875 | Columns: 32

[145/196] Processing:
sdc2023/train/2023-03-08-21-34-us-ca-mtv-u/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_145.parquet | Rows: 32014 | Columns: 32

[146/196] Processing:
sdc2023/train/2023-05-09-21-32-us-ca-mtv-pe1/pixel5/device_gnss.csv
Saved gnss_146.parquet | Rows: 67101 | Columns: 32

[147/196] Processing:
sdc2023/train/2023-05-09-21-32-us-ca-mtv-pe1/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_147.parquet | Rows: 61228 | Columns: 32

[148/196] Processing:
sdc2023/train/2023-05-09-21-32-us-ca-mtv-pe1/samsungs22ultra/device_gnss.csv
Saved gnss_148.parquet | Rows: 92570 | Columns: 32

[149/196] Processing:
sdc2023/train/2023-05-16-19-54-us-ca-mtv-xe1/pixel5/device_gnss.csv
Saved gnss_149.parquet | Rows: 61706 | Columns: 32

[150/196] Processing:
sdc2023/train/2023-05-16-19-55-us-ca-mtv-xe1/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_150.parquet | Rows: 58152 | Columns: 32

[151/196] Processing:
sdc2023/train/2023-05-19-20-10-us-ca-mtv-ie2/pixel5/device_gnss.csv
Saved gnss_151.parquet | Rows: 30861 | Columns: 32

[152/196] Processing:
sdc2023/train/2023-05-19-20-10-us-ca-mtv-ie2/pixel7pro/device_gnss.csv
Saved gnss_152.parquet | Rows: 29786 | Columns: 32

[153/196] Processing:
sdc2023/train/2023-05-19-20-10-us-ca-mtv-ie2/sm-s908b/device_gnss.csv
Saved gnss_153.parquet | Rows: 55997 | Columns: 32

[154/196] Processing:
sdc2023/train/2023-05-23-19-16-us-ca-mtv-ie2/pixel5/device_gnss.csv
Saved gnss_154.parquet | Rows: 24812 | Columns: 32

[155/196] Processing:
sdc2023/train/2023-05-23-19-16-us-ca-mtv-ie2/sm-s908b/device_gnss.csv
Saved gnss_155.parquet | Rows: 45574 | Columns: 32

[156/196] Processing:
sdc2023/train/2023-05-23-19-56-us-ca-mtv-ie2/sm-a226b/device_gnss.csv
Saved gnss_156.parquet | Rows: 16098 | Columns: 32

[157/196] Processing:
sdc2023/train/2023-05-23-19-56-us-ca-mtv-ie2/sm-a505g/device_gnss.csv
Saved gnss_157.parquet | Rows: 26244 | Columns: 32

[158/196] Processing:
sdc2023/train/2023-05-23-19-56-us-ca-mtv-ie2/sm-a600t/device_gnss.csv
Saved gnss_158.parquet | Rows: 30038 | Columns: 32

[159/196] Processing:
sdc2023/train/2023-05-24-20-26-us-ca-sjc-ge2/pixel5/device_gnss.csv
Saved gnss_159.parquet | Rows: 36159 | Columns: 32

[160/196] Processing:
sdc2023/train/2023-05-24-20-26-us-ca-sjc-ge2/pixel7pro/device_gnss.csv
Saved gnss_160.parquet | Rows: 41875 | Columns: 32

[161/196] Processing:
sdc2023/train/2023-05-25-19-10-us-ca-sjc-be2/pixel5/device_gnss.csv
Saved gnss_161.parquet | Rows: 33171 | Columns: 32

[162/196] Processing:
sdc2023/train/2023-05-25-19-10-us-ca-sjc-be2/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_162.parquet | Rows: 39044 | Columns: 32

[163/196] Processing:
sdc2023/train/2023-05-25-19-10-us-ca-sjc-be2/sm-s908b/device_gnss.csv
Saved gnss_163.parquet | Rows: 61488 | Columns: 32

[164/196] Processing:
sdc2023/train/2023-05-25-20-11-us-ca-sjc-he2/pixel5/device_gnss.csv
Saved gnss_164.parquet | Rows: 32582 | Columns: 32

[165/196] Processing:
sdc2023/train/2023-05-25-20-11-us-ca-sjc-he2/pixel7pro/device_gnss.csv
Saved gnss_165.parquet | Rows: 38439 | Columns: 32

[166/196] Processing:
sdc2023/train/2023-05-25-20-11-us-ca-sjc-he2/sm-s908b/device_gnss.csv
Saved gnss_166.parquet | Rows: 57880 | Columns: 32

[167/196] Processing:
sdc2023/train/2023-05-26-18-50-us-ca-sjc-ge2/sm-s908b/device_gnss.csv
Saved gnss_167.parquet | Rows: 67168 | Columns: 32

[168/196] Processing:
sdc2023/train/2023-05-26-18-51-us-ca-sjc-ge2/pixel5/device_gnss.csv
Saved gnss_168.parquet | Rows: 38958 | Columns: 32

[169/196] Processing:
sdc2023/train/2023-05-26-18-51-us-ca-sjc-ge2/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_169.parquet | Rows: 39892 | Columns: 32

[170/196] Processing:
sdc2023/train/2023-06-06-23-26-us-ca-sjc-he2/sm-a226b/device_gnss.csv
Saved gnss_170.parquet | Rows: 23704 | Columns: 32

[171/196] Processing:
sdc2023/train/2023-09-05-20-13-us-ca/pixel5/device_gnss.csv
Saved gnss_171.parquet | Rows: 63968 | Columns: 32

[172/196] Processing:
sdc2023/train/2023-09-05-20-13-us-ca/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_172.parquet | Rows: 61998 | Columns: 32

[173/196] Processing:
sdc2023/train/2023-09-05-20-59-us-ca/pixel4xl/device_gnss.csv
Saved gnss_173.parquet | Rows: 46796 | Columns: 32

[174/196] Processing:
sdc2023/train/2023-09-05-20-59-us-ca/pixel5a/device_gnss.csv
Saved gnss_174.parquet | Rows: 32981 | Columns: 32

[175/196] Processing:
sdc2023/train/2023-09-05-23-07-us-ca-routen/pixel5/device_gnss.csv
Saved gnss_175.parquet | Rows: 66025 | Columns: 32

[176/196] Processing:
sdc2023/train/2023-09-05-23-07-us-ca-routen/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_176.parquet | Rows: 62083 | Columns: 32

[177/196] Processing:
sdc2023/train/2023-09-06-00-01-us-ca-routen/pixel4xl/device_gnss.csv
Saved gnss_177.parquet | Rows: 59506 | Columns: 32

[178/196] Processing:
sdc2023/train/2023-09-06-00-01-us-ca-routen/pixel5a/device_gnss.csv
Saved gnss_178.parquet | Rows: 40268 | Columns: 32

[179/196] Processing:
sdc2023/train/2023-09-06-00-01-us-ca-routen/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_179.parquet | Rows: 60906 | Columns: 32

[180/196] Processing:
sdc2023/train/2023-09-06-00-01-us-ca-routen/sm-g955f/device_gnss.csv
Saved gnss_180.parquet | Rows: 22518 | Columns: 32

[181/196] Processing:
sdc2023/train/2023-09-06-18-04-us-ca/pixel5/device_gnss.csv
Saved gnss_181.parquet | Rows: 54260 | Columns: 32

[182/196] Processing:
sdc2023/train/2023-09-06-18-04-us-ca/pixel7pro/device_gnss.csv
Saved gnss_182.parquet | Rows: 50453 | Columns: 32

[183/196] Processing:
sdc2023/train/2023-09-06-18-04-us-ca/sm-s908b/device_gnss.csv
Saved gnss_183.parquet | Rows: 58956 | Columns: 32

[184/196] Processing:
sdc2023/train/2023-09-06-18-47-us-ca/pixel4xl/device_gnss.csv
Saved gnss_184.parquet | Rows: 45739 | Columns: 32

[185/196] Processing:
sdc2023/train/2023-09-06-18-47-us-ca/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_185.parquet | Rows: 49216 | Columns: 32

[186/196] Processing:
sdc2023/train/2023-09-06-22-49-us-ca-routebb1/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_186.parquet | Rows: 64642 | Columns: 32

[187/196] Processing:
sdc2023/train/2023-09-06-22-49-us-ca-routebb1/sm-s908b/device_gnss.csv
Saved gnss_187.parquet | Rows: 80911 | Columns: 32

[188/196] Processing:
sdc2023/train/2023-09-07-18-59-us-ca/pixel5/device_gnss.csv
Saved gnss_188.parquet | Rows: 43635 | Columns: 32

[189/196] Processing:
sdc2023/train/2023-09-07-18-59-us-ca/pixel7pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_189.parquet | Rows: 39419 | Columns: 32

[190/196] Processing:
sdc2023/train/2023-09-07-19-33-us-ca/pixel4xl/device_gnss.csv
Saved gnss_190.parquet | Rows: 33331 | Columns: 32

[191/196] Processing:
sdc2023/train/2023-09-07-19-33-us-ca/pixel5a/device_gnss.csv
Saved gnss_191.parquet | Rows: 22010 | Columns: 32

[192/196] Processing:
sdc2023/train/2023-09-07-19-33-us-ca/pixel6pro/device_gnss.csv
Saved gnss_192.parquet | Rows: 34904 | Columns: 32

[193/196] Processing:
sdc2023/train/2023-09-07-19-33-us-ca/sm-g955f/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_193.parquet | Rows: 21960 | Columns: 32

[194/196] Processing:
sdc2023/train/2023-09-07-22-47-us-ca-routebc2/pixel6pro/device_gnss.csv

/tmp/ipykernel_1674/1249174917.py:72: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(z.open(file_path))

Saved gnss_194.parquet | Rows: 76452 | Columns: 32

[195/196] Processing:
sdc2023/train/2023-09-07-22-48-us-ca-routebc2/pixel4xl/device_gnss.csv
Saved gnss_195.parquet | Rows: 77200 | Columns: 32

[196/196] Processing:
sdc2023/train/2023-09-07-22-48-us-ca-routebc2/pixel5a/device_gnss.csv
Saved gnss_196.parquet | Rows: 51748 | Columns: 32

========================================
DONE — ALL 196 FILES PROCESSED
========================================

In [60]:
import os
import numpy as np
import pandas as pd

In [61]:
import os

files = sorted([
    f for f in os.listdir("/content/gnss_features_v2")
    if f.endswith(".parquet")
])

print("check the files:", len(files))
print(files[:3])
print(files[-3:])

check the files: 196
['gnss_001.parquet', 'gnss_002.parquet', 'gnss_003.parquet']
['gnss_194.parquet', 'gnss_195.parquet', 'gnss_196.parquet']

In [62]:
files = sorted([
    f for f in os.listdir("/content/gnss_features_v2")
    if f.endswith(".parquet")
])

print("Total:", len(files))
print("Last 10 files:")
print(files[-10:])

Total: 196
Last 10 files:
['gnss_187.parquet', 'gnss_188.parquet', 'gnss_189.parquet', 'gnss_190.parquet', 'gnss_191.parquet', 'gnss_192.parquet', 'gnss_193.parquet', 'gnss_194.parquet', 'gnss_195.parquet', 'gnss_196.parquet']

In [63]:
import os
import pandas as pd
import numpy as np

corrected_dir = "/content/gnss_features_v2"

train_files = [
    f"gnss_{i:03d}.parquet"
    for i in range(1, 138)
]

analysis_features = [
    "Cn0DbHz",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "down_streak",
    "up_streak",
    "Cn0_rolling_std",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10"
]

stats_list = []

for i, file_name in enumerate(train_files, 1):

    path = os.path.join(corrected_dir, file_name)

    df_train = pd.read_parquet(
        path,
        columns=analysis_features
    )

    stats = df_train.describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95]
    ).T

    stats["file"] = file_name

    stats_list.append(stats)

    print(f"[{i}/137] {file_name}")

all_stats = pd.concat(
    stats_list,
    ignore_index=False
)

print("\nTraining statistical analysis completed.")

[1/137] gnss_001.parquet
[2/137] gnss_002.parquet
[3/137] gnss_003.parquet
[4/137] gnss_004.parquet
[5/137] gnss_005.parquet
[6/137] gnss_006.parquet
[7/137] gnss_007.parquet
[8/137] gnss_008.parquet
[9/137] gnss_009.parquet
[10/137] gnss_010.parquet
[11/137] gnss_011.parquet
[12/137] gnss_012.parquet
[13/137] gnss_013.parquet
[14/137] gnss_014.parquet
[15/137] gnss_015.parquet
[16/137] gnss_016.parquet
[17/137] gnss_017.parquet
[18/137] gnss_018.parquet
[19/137] gnss_019.parquet
[20/137] gnss_020.parquet
[21/137] gnss_021.parquet
[22/137] gnss_022.parquet
[23/137] gnss_023.parquet
[24/137] gnss_024.parquet
[25/137] gnss_025.parquet
[26/137] gnss_026.parquet
[27/137] gnss_027.parquet
[28/137] gnss_028.parquet
[29/137] gnss_029.parquet
[30/137] gnss_030.parquet
[31/137] gnss_031.parquet
[32/137] gnss_032.parquet
[33/137] gnss_033.parquet
[34/137] gnss_034.parquet
[35/137] gnss_035.parquet
[36/137] gnss_036.parquet
[37/137] gnss_037.parquet
[38/137] gnss_038.parquet
[39/137] gnss_039.parquet
[40/137] gnss_040.parquet
[41/137] gnss_041.parquet
[42/137] gnss_042.parquet
[43/137] gnss_043.parquet
[44/137] gnss_044.parquet
[45/137] gnss_045.parquet
[46/137] gnss_046.parquet
[47/137] gnss_047.parquet
[48/137] gnss_048.parquet
[49/137] gnss_049.parquet
[50/137] gnss_050.parquet
[51/137] gnss_051.parquet
[52/137] gnss_052.parquet
[53/137] gnss_053.parquet
[54/137] gnss_054.parquet
[55/137] gnss_055.parquet
[56/137] gnss_056.parquet
[57/137] gnss_057.parquet
[58/137] gnss_058.parquet
[59/137] gnss_059.parquet
[60/137] gnss_060.parquet
[61/137] gnss_061.parquet
[62/137] gnss_062.parquet
[63/137] gnss_063.parquet
[64/137] gnss_064.parquet
[65/137] gnss_065.parquet
[66/137] gnss_066.parquet
[67/137] gnss_067.parquet
[68/137] gnss_068.parquet
[69/137] gnss_069.parquet
[70/137] gnss_070.parquet
[71/137] gnss_071.parquet
[72/137] gnss_072.parquet
[73/137] gnss_073.parquet
[74/137] gnss_074.parquet
[75/137] gnss_075.parquet
[76/137] gnss_076.parquet
[77/137] gnss_077.parquet
[78/137] gnss_078.parquet
[79/137] gnss_079.parquet
[80/137] gnss_080.parquet
[81/137] gnss_081.parquet
[82/137] gnss_082.parquet
[83/137] gnss_083.parquet
[84/137] gnss_084.parquet
[85/137] gnss_085.parquet
[86/137] gnss_086.parquet
[87/137] gnss_087.parquet
[88/137] gnss_088.parquet
[89/137] gnss_089.parquet
[90/137] gnss_090.parquet
[91/137] gnss_091.parquet
[92/137] gnss_092.parquet
[93/137] gnss_093.parquet
[94/137] gnss_094.parquet
[95/137] gnss_095.parquet
[96/137] gnss_096.parquet
[97/137] gnss_097.parquet
[98/137] gnss_098.parquet
[99/137] gnss_099.parquet
[100/137] gnss_100.parquet
[101/137] gnss_101.parquet
[102/137] gnss_102.parquet
[103/137] gnss_103.parquet
[104/137] gnss_104.parquet
[105/137] gnss_105.parquet
[106/137] gnss_106.parquet
[107/137] gnss_107.parquet
[108/137] gnss_108.parquet
[109/137] gnss_109.parquet
[110/137] gnss_110.parquet
[111/137] gnss_111.parquet
[112/137] gnss_112.parquet
[113/137] gnss_113.parquet
[114/137] gnss_114.parquet
[115/137] gnss_115.parquet
[116/137] gnss_116.parquet
[117/137] gnss_117.parquet
[118/137] gnss_118.parquet
[119/137] gnss_119.parquet
[120/137] gnss_120.parquet
[121/137] gnss_121.parquet
[122/137] gnss_122.parquet
[123/137] gnss_123.parquet
[124/137] gnss_124.parquet
[125/137] gnss_125.parquet
[126/137] gnss_126.parquet
[127/137] gnss_127.parquet
[128/137] gnss_128.parquet
[129/137] gnss_129.parquet
[130/137] gnss_130.parquet
[131/137] gnss_131.parquet
[132/137] gnss_132.parquet
[133/137] gnss_133.parquet
[134/137] gnss_134.parquet
[135/137] gnss_135.parquet
[136/137] gnss_136.parquet
[137/137] gnss_137.parquet

Training statistical analysis completed.

In [64]:
print(all_stats[[
    "mean",
    "std",
    "min",
    "25%",
    "50%",
    "75%",
    "90%",
    "95%",
    "max"
]].groupby(level=0).mean())

                               mean       std        min        25%  \
Cn0DbHz                   33.410970  5.834876  20.015627  29.014849
Cn0_acceleration          -0.000268  0.710161  -5.722750  -0.292804
Cn0_change                -0.000887  1.965988 -16.358090  -0.747551
Cn0_max_5                 35.014670  5.312872  20.823445  31.060253
Cn0_min_5                 31.641151  6.151684  20.015614  26.702411
Cn0_range_5                3.373519  2.842370   0.032225   1.245378
Cn0_rolling_std            1.390373  1.188884   0.013745   0.507187
Cn0_slope                 -0.000469  0.838754  -5.108634  -0.348195
Cn0_trend                 -0.001874  3.355014 -20.434538  -1.392780
Cn0_trend_mean            -0.000595  1.025110  -6.525509  -0.411322
down_streak                1.585546  2.373183   0.000000   0.000000
negative_change_count_10   4.913082  1.472948   0.000000   3.905109
positive_change_count_10   4.734689  1.433792   0.000000   3.875912
up_streak                  1.446090  2.205422   0.000000   0.000000

                                50%        75%        90%        95%  \
Cn0DbHz                   33.650684  37.915750  41.009166  42.598328
Cn0_acceleration          -0.003601   0.283365   0.765873   1.160732
Cn0_change                -0.011374   0.696254   1.967210   3.124317
Cn0_max_5                 35.298135  39.072571  41.876978  43.327128
Cn0_min_5                 31.645407  36.444443  39.916570  41.669373
Cn0_range_5                2.519768   4.683469   7.314397   9.127447
Cn0_rolling_std            1.032627   1.921580   3.014040   3.783686
Cn0_slope                 -0.002222   0.340970   0.913145   1.391097
Cn0_trend                 -0.008889   1.363880   3.652579   5.564387
Cn0_trend_mean            -0.002861   0.399626   1.097541   1.686390
down_streak                0.452555   2.496350   4.802920   6.408759
negative_change_count_10   4.941606   6.007299   6.693431   7.364964
positive_change_count_10   4.883212   5.897810   6.547445   7.021898
up_streak                  0.036496   2.138686   4.353285   5.832117

                                max
Cn0DbHz                   48.134789
Cn0_acceleration           6.125728
Cn0_change                18.912121
Cn0_max_5                 48.134789
Cn0_min_5                 47.372289
Cn0_range_5               22.232260
Cn0_rolling_std           10.286235
Cn0_slope                  5.365581
Cn0_trend                 21.462322
Cn0_trend_mean             7.044439
down_streak               24.284672
negative_change_count_10   9.985401
positive_change_count_10   9.905109
up_streak                 23.737226

In [65]:
from pathlib import Path
import numpy as np
import pandas as pd
import pyarrow.parquet as pq

corrected_dir = Path("/content/gnss_features_v2")
output_dir = Path("/content/gnss_training_statistics")
output_dir.mkdir(parents=True, exist_ok=True)

analysis_features = [

    "Cn0DbHz",
    "Cn0_trend",
    "Cn0_trend_mean",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_rolling_std",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10",
    "up_streak",
    "down_streak",
]

training_paths = [
    corrected_dir / f"gnss_{i:03d}.parquet"
    for i in range(1, 138)
]

print("Training files:", len(training_paths))
print("First:", training_paths[0])
print("Last:", training_paths[-1])
print("Features:", len(analysis_features))

Training files: 137
First: /content/gnss_features_v2/gnss_001.parquet
Last: /content/gnss_features_v2/gnss_137.parquet
Features: 13

In [66]:
missing_features = {}

for i in range(1, 138):

    file_name = f"gnss_{i:03d}.parquet"
    path = corrected_dir / file_name

    df = pd.read_parquet(
        path,
        columns=analysis_features
    )

    missing = [
        feature
        for feature in analysis_features
        if feature not in df.columns
    ]

    if missing:
        missing_features[file_name] = missing

print("Files checked:", 137)

if missing_features:
    print("Missing features found:")
    print(missing_features)
else:
    print(" All 13 labeling features exist in all 137 files.")

Files checked: 137
 All 13 labeling features exist in all 137 files.

In [67]:

total_nan = 0
total_inf = 0

files_with_nan = []
files_with_inf = []

for i in range(1, 138):

    file_name = f"gnss_{i:03d}.parquet"
    path = corrected_dir / file_name

    df = pd.read_parquet(
        path,
        columns=analysis_features
    )

    nan_count = int(df[analysis_features].isna().sum().sum())

    inf_count = int(
        np.isinf(df[analysis_features].to_numpy()).sum()
    )

    total_nan += nan_count
    total_inf += inf_count

    if nan_count > 0:
        files_with_nan.append(
            (file_name, nan_count)
        )

    if inf_count > 0:
        files_with_inf.append(
            (file_name, inf_count)
        )

print("Total NaN values:", total_nan)
print("Total infinite values:", total_inf)

print("\nFiles with NaN:", len(files_with_nan))
print("Files with Inf:", len(files_with_inf))

if files_with_nan:
    print("\nNaN details:")
    print(files_with_nan[:10])

if files_with_inf:
    print("\nInf details:")
    print(files_with_inf[:10])

Total NaN values: 0
Total infinite values: 0

Files with NaN: 0
Files with Inf: 0

In [68]:
count_features = [
    "negative_change_count_10",
    "positive_change_count_10",
    "up_streak",
    "down_streak"
]

check_results = []

for i in range(1, 138):

    file_name = f"gnss_{i:03d}.parquet"
    path = corrected_dir / file_name

    df = pd.read_parquet(
        path,
        columns=count_features
    )

    for feature in count_features:

        values = df[feature].to_numpy(dtype=np.float64)

        negative_count = int((values < 0).sum())

        non_integer_count = int(
            (
                ~np.isclose(
                    values,
                    np.rint(values),
                    rtol=0,
                    atol=1e-8
                )
            ).sum()
        )

        check_results.append({
            "file": file_name,
            "feature": feature,
            "negative_count": negative_count,
            "non_integer_count": non_integer_count,
            "min": values.min(),
            "max": values.max()
        })

count_check_table = pd.DataFrame(check_results)

print("Total negative values:",
      count_check_table["negative_count"].sum())

print("Total non-integer values:",
      count_check_table["non_integer_count"].sum())

display(
    count_check_table[
        [
            "feature",
            "negative_count",
            "non_integer_count",
            "min",
            "max"
        ]
    ]
    .groupby("feature")
    .agg({
        "negative_count": "sum",
        "non_integer_count": "sum",
        "min": "min",
        "max": "max"
    })
)

Total negative values: 0
Total non-integer values: 0

                          negative_count  non_integer_count  min   max
feature
down_streak                            0                  0  0.0  98.0
negative_change_count_10               0                  0  0.0  10.0
positive_change_count_10               0                  0  0.0  10.0
up_streak                              0                  0  0.0  86.0

In [69]:

from pathlib import Path
import numpy as np
import pandas as pd
import pyarrow.parquet as pq

corrected_dir = Path("/content/gnss_features_v2")

analysis_features = [
    "Cn0DbHz",
    "Cn0_trend",
    "Cn0_trend_mean",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_rolling_std",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10",
    "up_streak",
    "down_streak",
]

sample_size_per_feature = 50_000
batch_size = 32_768
rng = np.random.default_rng(42)

reservoirs = {
    feature: []
    for feature in analysis_features
}

for i in range(1, 138):

    path = corrected_dir / f"gnss_{i:03d}.parquet"

    parquet_file = pq.ParquetFile(path)

    try:
        for batch in parquet_file.iter_batches(
            batch_size=batch_size,
            columns=analysis_features,
            use_threads=False
        ):

            for feature in analysis_features:

                column = batch.column(
                    batch.schema.get_field_index(feature)
                )

                values = np.asarray(
                    column.to_numpy(
                        zero_copy_only=False
                    ),
                    dtype=np.float64
                )

                values = values[
                    np.isfinite(values)
                ]

                if values.size == 0:
                    continue

                reservoirs[feature].extend(
                    values.tolist()
                )

                # Keep memory bounded
                if len(reservoirs[feature]) > sample_size_per_feature:

                    selected = rng.choice(
                        len(reservoirs[feature]),
                        size=sample_size_per_feature,
                        replace=False
                    )

                    reservoirs[feature] = [
                        reservoirs[feature][j]
                        for j in selected
                    ]

    finally:
        parquet_file.close()

    print(f"[{i}/137] processed")


# PERCENTILE TABLE

percentile_table = pd.DataFrame(
    index=analysis_features,
    columns=[
        "p10",
        "p25",
        "p50",
        "p75",
        "p90",
        "p95"
    ],
    dtype=float
)

for feature in analysis_features:

    values = np.asarray(
        reservoirs[feature],
        dtype=np.float64
    )

    percentile_table.loc[feature] = np.percentile(
        values,
        [10, 25, 50, 75, 90, 95]
    )


print("TRAINING FEATURE DISTRIBUTIONS")

display(
    percentile_table.round(4)
)

[1/137] processed
[2/137] processed
[3/137] processed
[4/137] processed
[5/137] processed
[6/137] processed
[7/137] processed
[8/137] processed
[9/137] processed
[10/137] processed
[11/137] processed
[12/137] processed
[13/137] processed
[14/137] processed
[15/137] processed
[16/137] processed
[17/137] processed
[18/137] processed
[19/137] processed
[20/137] processed
[21/137] processed
[22/137] processed
[23/137] processed
[24/137] processed
[25/137] processed
[26/137] processed
[27/137] processed
[28/137] processed
[29/137] processed
[30/137] processed
[31/137] processed
[32/137] processed
[33/137] processed
[34/137] processed
[35/137] processed
[36/137] processed
[37/137] processed
[38/137] processed
[39/137] processed
[40/137] processed
[41/137] processed
[42/137] processed
[43/137] processed
[44/137] processed
[45/137] processed
[46/137] processed
[47/137] processed
[48/137] processed
[49/137] processed
[50/137] processed
[51/137] processed
[52/137] processed
[53/137] processed
[54/137] processed
[55/137] processed
[56/137] processed
[57/137] processed
[58/137] processed
[59/137] processed
[60/137] processed
[61/137] processed
[62/137] processed
[63/137] processed
[64/137] processed
[65/137] processed
[66/137] processed
[67/137] processed
[68/137] processed
[69/137] processed
[70/137] processed
[71/137] processed
[72/137] processed
[73/137] processed
[74/137] processed
[75/137] processed
[76/137] processed
[77/137] processed
[78/137] processed
[79/137] processed
[80/137] processed
[81/137] processed
[82/137] processed
[83/137] processed
[84/137] processed
[85/137] processed
[86/137] processed
[87/137] processed
[88/137] processed
[89/137] processed
[90/137] processed
[91/137] processed
[92/137] processed
[93/137] processed
[94/137] processed
[95/137] processed
[96/137] processed
[97/137] processed
[98/137] processed
[99/137] processed
[100/137] processed
[101/137] processed
[102/137] processed
[103/137] processed
[104/137] processed
[105/137] processed
[106/137] processed
[107/137] processed
[108/137] processed
[109/137] processed
[110/137] processed
[111/137] processed
[112/137] processed
[113/137] processed
[114/137] processed
[115/137] processed
[116/137] processed
[117/137] processed
[118/137] processed
[119/137] processed
[120/137] processed
[121/137] processed
[122/137] processed
[123/137] processed
[124/137] processed
[125/137] processed
[126/137] processed
[127/137] processed
[128/137] processed
[129/137] processed
[130/137] processed
[131/137] processed
[132/137] processed
[133/137] processed
[134/137] processed
[135/137] processed
[136/137] processed
[137/137] processed
TRAINING FEATURE DISTRIBUTIONS

                              p10      p25      p50      p75      p90      p95
Cn0DbHz                   25.6030  29.7951  34.8000  38.9000  42.0000  43.5000
Cn0_trend                 -2.3760  -0.5000   0.0000   0.4000   2.4941   4.5000
Cn0_trend_mean            -0.6667  -0.1333   0.0000   0.1000   0.7195   1.3333
Cn0_slope                 -0.5927  -0.1250   0.0000   0.0870   0.6032   1.1250
Cn0_acceleration          -0.4728  -0.0310   0.0000   0.0250   0.4534   0.9250
Cn0_rolling_std            0.0310   0.0548   0.2864   1.2598   2.5338   3.4096
Cn0_min_5                 23.7000  28.0000  33.8000  38.4000  41.7000  43.2000
Cn0_max_5                 27.5437  31.3000  35.6000  39.4000  42.2300  43.7876
Cn0_range_5                0.0770   0.1330   0.7000   3.0000   6.0000   8.1000
negative_change_count_10   0.0000   1.0000   4.0000   6.0000   8.0000   9.0000
positive_change_count_10   0.0000   0.0000   3.0000   5.0000   6.0000   7.0000
up_streak                  0.0000   0.0000   0.0000   2.0000   5.0000   9.0000
down_streak                0.0000   0.0000   0.0000   3.0000  13.0000  23.0000

In [70]:
##

In [71]:
label_analysis_features = [
    "Cn0DbHz",
    "Cn0_trend",
    "Cn0_trend_mean",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_rolling_std",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10",
    "up_streak",
    "down_streak"
]

print("Features for labeling analysis:")
for feature in label_analysis_features:
    print(feature)

Features for labeling analysis:
Cn0DbHz
Cn0_trend
Cn0_trend_mean
Cn0_slope
Cn0_acceleration
Cn0_rolling_std
Cn0_range_5
negative_change_count_10
positive_change_count_10
up_streak
down_streak

In [72]:
import numpy as np

cn0_values = np.asarray(
    reservoirs["Cn0DbHz"],
    dtype=np.float64
) if "reservoirs" in globals() else None

print("Cn0 reservoir available:", cn0_values is not None)

Cn0 reservoir available: True

In [73]:
print(percentile_table.loc["Cn0DbHz"])

p10    25.602962
p25    29.795079
p50    34.799999
p75    38.900002
p90    42.000000
p95    43.500000
Name: Cn0DbHz, dtype: float64

In [74]:
p25 = percentile_table.loc["Cn0DbHz", "p25"]
p50 = percentile_table.loc["Cn0DbHz", "p50"]
p75 = percentile_table.loc["Cn0DbHz", "p75"]

print("C/N0 analysis boundaries:")
print("P25:", p25)
print("P50:", p50)
print("P75:", p75)

C/N0 analysis boundaries:
P25: 29.795079231262203
P50: 34.79999923706055
P75: 38.900001525878906

In [75]:
df = pd.read_parquet(
    corrected_dir / "gnss_001.parquet",
    columns=["Cn0DbHz", "Cn0_slope"]
)

print(df.columns.tolist())

['Cn0DbHz', 'Cn0_slope']

In [76]:
df["region"] = pd.cut(
    df["Cn0DbHz"],
    bins=[-np.inf, p25, p50, p75, np.inf],
    labels=["LOW", "LOW_MID", "HIGH_MID", "HIGH"]
)

In [77]:
slope_region_table=reggion_tabel=(
      df.groupby("region",observed=False)["Cn0_slope"]
      .agg(["count", "mean", "median", "min", "max"])
      .reset_index()
)

display(slope_region_table.round(4))

     region  count    mean  median   min    max
0       LOW   8666 -0.6754  -0.475 -6.40  2.375
1   LOW_MID  10961 -0.0227  -0.025 -3.75  3.525
2  HIGH_MID  11693  0.1943   0.050 -2.70  4.525
3      HIGH  12741  0.2954   0.100 -1.70  5.950

In [78]:
slope_results = []

for i in range(1, 138):

    path = corrected_dir / f"gnss_{i:03d}.parquet"

    df = pd.read_parquet(
        path,
        columns=["Cn0DbHz", "Cn0_slope"]
    )

    df["region"] = pd.cut(
        df["Cn0DbHz"],
        bins=[-np.inf, p25, p50, p75, np.inf],
        labels=["LOW", "LOW_MID", "HIGH_MID", "HIGH"],
        include_lowest=True
    )

    grouped = (
        df.groupby("region", observed=False)
        .agg(
            count=("Cn0_slope", "count"),
            mean_slope=("Cn0_slope", "mean")
        )
        .reset_index()
    )

    slope_results.append(grouped)

slope_all = (
    pd.concat(slope_results, ignore_index=True)
    .groupby("region", observed=False)
    .agg(
        count=("count", "sum")
    )
    .reset_index()
)

# Calculate weighted mean properly
weighted_sum = (
    pd.concat(slope_results, ignore_index=True)
    .assign(
        slope_sum=lambda x:
        x["count"] * x["mean_slope"]
    )
    .groupby("region", observed=False)["slope_sum"]
    .sum()
)

slope_all["mean_slope"] = (
    weighted_sum.values /
    slope_all["count"].values
)

display(
    slope_all[
        ["region", "count", "mean_slope"]
    ].round(4)
)

     region    count  mean_slope
0       LOW  2244649     -0.3378
1   LOW_MID  2150382      0.0563
2  HIGH_MID  1762558      0.1747
3      HIGH  1526827      0.2135

In [79]:
trend_results = []

for i in range(1, 138):

    path = corrected_dir / f"gnss_{i:03d}.parquet"

    df = pd.read_parquet(
        path,
        columns=["Cn0DbHz", "Cn0_trend_mean"]
    )

    df["region"] = pd.cut(
        df["Cn0DbHz"],
        bins=[-np.inf, p25, p50, p75, np.inf],
        labels=["LOW", "LOW_MID", "HIGH_MID", "HIGH"],
        include_lowest=True
    )

    grouped = (
        df.groupby("region", observed=False)["Cn0_trend_mean"]
        .agg(
            count="count",
            trend_sum="sum"
        )
        .reset_index()
    )

    trend_results.append(grouped)

trend_all = (
    pd.concat(trend_results, ignore_index=True)
    .groupby("region", observed=False)
    .agg(
        count=("count", "sum"),
        trend_sum=("trend_sum", "sum")
    )
    .reset_index()
)

trend_all["mean_trend"] = (
    trend_all["trend_sum"] /
    trend_all["count"]
)

print("Total rows represented:", trend_all["count"].sum())

display(
    trend_all[
        ["region", "count", "mean_trend"]
    ].round(4)
)

Total rows represented: 7684416

     region    count  mean_trend
0       LOW  2244649     -0.3825
1   LOW_MID  2150382      0.0716
2  HIGH_MID  1762558      0.1963
3      HIGH  1526827      0.2320

In [81]:
import numpy as np
import pandas as pd

all_features = [
    "Cn0DbHz",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "down_streak",
    "up_streak",
    "PseudorangeRateMetersPerSecond",
    "PseudorangeRate_change",
    "SvElevationDegrees",
    "Elevation_change",
    "SvAzimuthDegrees",
    "Azimuth_change",
    "Cn0_rolling_std",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10"
]

regions = ["LOW", "LOW_MID", "HIGH_MID", "HIGH"]

# ---------------------------------------------------------
# Storage
# ---------------------------------------------------------

stats = {}

for feature in all_features:
    for region in regions:
        stats[(feature, region)] = {
            "count": 0,
            "sum": 0.0,
            "sum_sq": 0.0,
            "min": np.inf,
            "max": -np.inf,
            "negative_count": 0,
            "positive_count": 0
        }

# ---------------------------------------------------------
# Process all 137 training files
# ---------------------------------------------------------

for i in range(1, 138):

    path = corrected_dir / f"gnss_{i:03d}.parquet"

    df = pd.read_parquet(
        path,
        columns=all_features
    )

    # C/N0 defines the regions
    valid_cn0 = np.isfinite(df["Cn0DbHz"])

    df = df.loc[valid_cn0].copy()

    df["region"] = pd.cut(
        df["Cn0DbHz"],
        bins=[-np.inf, p25, p50, p75, np.inf],
        labels=regions,
        include_lowest=True
    )

    # -----------------------------------------------------
    # Collect statistics for every feature in every region
    # -----------------------------------------------------

    for region in regions:

        region_df = df[df["region"] == region]

        if region_df.empty:
            continue

        for feature in all_features:

            values = region_df[feature].to_numpy(
                dtype=np.float64
            )

            values = values[np.isfinite(values)]

            if values.size == 0:
                continue

            s = stats[(feature, region)]

            s["count"] += values.size
            s["sum"] += values.sum()
            s["sum_sq"] += np.square(values).sum()
            s["min"] = min(s["min"], values.min())
            s["max"] = max(s["max"], values.max())

            s["negative_count"] += int(
                (values < 0).sum()
            )

            s["positive_count"] += int(
                (values > 0).sum()
            )

    if i % 10 == 0 or i == 137:
        print(f"[{i}/137] processed")


# ---------------------------------------------------------
# Build ONE combined 80-row table
# ---------------------------------------------------------

rows = []

for feature in all_features:

    for region in regions:

        s = stats[(feature, region)]
        count = s["count"]

        if count == 0:
            continue

        mean = s["sum"] / count

        variance = (
            s["sum_sq"] / count
            - mean ** 2
        )

        variance = max(variance, 0.0)

        std = np.sqrt(variance)

        rows.append({
            "region": region,
            "feature": feature,
            "count": count,
            "mean": mean,
            "std": std,
            "min": s["min"],
            "max": s["max"],
            "negative_pct": (
                s["negative_count"] / count * 100
            ),
            "positive_pct": (
                s["positive_count"] / count * 100
            )
        })

master_behavior_table = pd.DataFrame(rows)

print("\n==============================================")
print("COMBINED MULTI-FEATURE BEHAVIOR TABLE")
print("TRAINING FILES 001–137")
print("==============================================")

print(
    "Rows in final table:",
    len(master_behavior_table)
)

display(
    master_behavior_table.round(4)
)

[10/137] processed
[20/137] processed
[30/137] processed
[40/137] processed
[50/137] processed
[60/137] processed
[70/137] processed
[80/137] processed
[90/137] processed
[100/137] processed
[110/137] processed
[120/137] processed
[130/137] processed
[137/137] processed

==============================================
COMBINED MULTI-FEATURE BEHAVIOR TABLE
TRAINING FILES 001–137
==============================================
Rows in final table: 80

,region,feature,count,mean,std,min,max,negative_pct,positive_pct
0,LOW,Cn0DbHz,2244649,26.1162,2.4983,19.9000,29.7951,0.000,100.0000
1,LOW_MID,Cn0DbHz,2150382,32.3388,1.4403,29.7951,34.8000,0.000,100.0000
2,HIGH_MID,Cn0DbHz,1762558,36.7801,1.1930,34.8000,38.9000,0.000,100.0000
3,HIGH,Cn0DbHz,1526827,41.8229,2.2305,38.9000,52.8634,0.000,100.0000
4,LOW,Cn0_change,2244649,-0.4858,2.3428,-23.6000,9.8000,57.197,40.9127
...,...,...,...,...,...,...,...,...,...
75,HIGH,negative_change_count_10,1526827,4.4027,1.6093,0.0000,10.0000,0.000,97.9594
76,LOW,positive_change_count_10,2244649,4.4120,1.3980,0.0000,10.0000,0.000,98.9417
77,LOW_MID,positive_change_count_10,2150382,4.7424,1.4930,0.0000,10.0000,0.000,98.6950
78,HIGH_MID,positive_change_count_10,1762558,4.8738,1.5527,0.0000,10.0000,0.000,98.5419
79,HIGH,positive_change_count_10,1526827,4.9985,1.6707,0.0000,10.0000,0.000,97.9877

In [82]:
stats = {}

for feature in all_features:
    for region in regions:
        stats[(feature, region)] = {
            "count": 0,
            "sum": 0.0,
            "sum_sq": 0.0,
            "min": np.inf,
            "max": -np.inf,
            "negative_count": 0,
            "positive_count": 0
        }

In [85]:

results = []

for i in range(1, 138):

    path = corrected_dir / f"gnss_{i:03d}.parquet"

    df = pd.read_parquet(
        path,
        columns=remaining_features
    )

    df["region"] = pd.cut(
        df["Cn0DbHz"],
        bins=[-np.inf, p25, p50, p75, np.inf],
        labels=region_labels,
        include_lowest=True
    )

    for region in region_labels:

        region_df = df[df["region"] == region]

        if len(region_df) == 0:
            continue

        for feature in remaining_features:

            values = region_df[feature].to_numpy(
                dtype=np.float64
            )

            values = values[np.isfinite(values)]

            if len(values) == 0:
                continue

            results.append({
                "region": region,
                "feature": feature,
                "count": len(values),
                "mean": values.mean(),
                "std": values.std(),
                "min": values.min(),
                "max": values.max(),
                "negative_pct": (values < 0).mean() * 100,
                "positive_pct": (values > 0).mean() * 100
            })

    if i % 10 == 0 or i == 137:
        print(f"[{i}/137] processed")

master_table = pd.DataFrame(results)

print("ALL REMAINING FEATURES — TRAINING DATA")

display(
    master_table.round(4)
)

[10/137] processed
[20/137] processed
[30/137] processed
[40/137] processed
[50/137] processed
[60/137] processed
[70/137] processed
[80/137] processed
[90/137] processed
[100/137] processed
[110/137] processed
[120/137] processed
[130/137] processed
[137/137] processed
ALL REMAINING FEATURES — TRAINING DATA

,region,feature,count,mean,std,min,max,negative_pct,positive_pct
0,LOW,Cn0DbHz,8666,26.2521,2.4462,20.0,29.7,0.0000,100.0000
1,LOW,Cn0_change,8666,-1.1241,3.2759,-21.9,9.0,60.9624,37.2606
2,LOW,Cn0_trend,8666,-2.7017,4.6690,-25.6,9.5,70.2862,28.7330
3,LOW,down_streak,8666,2.0880,2.2658,0.0,19.0,0.0000,68.6360
4,LOW,up_streak,8666,0.6358,1.2149,0.0,10.0,0.0000,30.2100
...,...,...,...,...,...,...,...,...,...
9859,HIGH,Cn0_min_5,17126,41.7198,2.5309,22.1,48.2,0.0000,100.0000
9860,HIGH,Cn0_max_5,17126,42.2164,2.1440,39.0,49.9,0.0000,100.0000
9861,HIGH,Cn0_range_5,17126,0.4966,1.4276,0.0,20.6,0.0000,74.8686
9862,HIGH,negative_change_count_10,17126,1.8435,2.4455,0.0,10.0,0.0000,57.9645
9863,HIGH,positive_change_count_10,17126,1.3856,1.6503,0.0,5.0,0.0000,53.2115

In [86]:
combined_18 = (
    master_table
    .groupby(["region", "feature"], observed=False)
    .agg({
        "count": "sum",
        "mean": "mean",
        "std": "mean",
        "min": "min",
        "max": "max",
        "negative_pct": "mean",
        "positive_pct": "mean"
    })
    .reset_index()
)

print("Rows:", len(combined_18))
display(combined_18.head(20).round(4))

Rows: 72

,region,feature,count,mean,std,min,max,negative_pct,positive_pct
0,HIGH,Azimuth_change,1526827,0.0019,0.0579,-124.7766,124.7541,42.4876,56.7862
1,HIGH,Cn0DbHz,1526827,41.5139,1.8599,38.9000,52.8634,0.0000,100.0000
2,HIGH,Cn0_acceleration,1526827,0.0366,0.5487,-7.3953,11.1000,47.9533,49.3035
3,HIGH,Cn0_change,1526827,0.2905,1.3766,-9.0000,26.9656,41.6529,53.0524
4,HIGH,Cn0_max_5,1526827,42.0605,1.9047,38.9000,52.8634,0.0000,100.0000
5,HIGH,Cn0_min_5,1526827,39.7591,3.4146,20.0000,52.6052,0.0000,100.0000
6,HIGH,Cn0_range_5,1526827,2.3014,2.7049,0.0000,28.9979,0.0000,99.5113
7,HIGH,Cn0_rolling_std,1526827,0.9537,1.1439,0.0000,14.3849,0.0000,99.5113
8,HIGH,Cn0_trend,1526827,0.9345,2.6503,-13.0000,25.7793,37.7539,59.5295
9,HIGH,Elevation_change,1526827,0.0003,0.0290,-54.2212,54.2053,46.6574,52.6164
10,HIGH,PseudorangeRateMetersPerSecond,1526827,-47.7208,364.6106,-2172.7631,962.9221,52.8123,47.1877
11,HIGH,PseudorangeRate_change,1526827,0.0569,0.7964,-456.5812,460.2777,41.9643,57.2598
12,HIGH,SvAzimuthDegrees,1526827,178.8447,103.5321,0.0004,359.9992,0.0000,100.0000
13,HIGH,SvElevationDegrees,1526827,46.2822,16.9328,-5.8850,89.0450,0.0000,100.0000
14,HIGH,down_streak,1526827,1.1076,1.9549,0.0000,65.0000,0.0000,38.7475
15,HIGH,negative_change_count_10,1526827,4.3947,1.4658,0.0000,10.0000,0.0000,98.6084
16,HIGH,positive_change_count_10,1526827,5.0851,1.4873,0.0000,10.0000,0.0000,98.7736
17,HIGH,up_streak,1526827,2.0256,2.7167,0.0000,86.0000,0.0000,58.1353
18,HIGH_MID,Azimuth_change,1762558,0.0014,0.0312,-90.0036,85.5052,46.4819,52.7892
19,HIGH_MID,Cn0DbHz,1762558,36.7781,1.1884,34.8000,38.9000,0.0000,100.0000

In [87]:
combined_18 = (
    master_table
    .groupby(
        ["region", "feature"],
        observed=False
    )
    .apply(
        lambda g: pd.Series({
            "count": g["count"].sum(),

            "mean": (
                (g["mean"] * g["count"]).sum()
                / g["count"].sum()
            ),

            "min": g["min"].min(),
            "max": g["max"].max(),

            "negative_pct": (
                (g["negative_pct"] * g["count"]).sum()
                / g["count"].sum()
            ),

            "positive_pct": (
                (g["positive_pct"] * g["count"]).sum()
                / g["count"].sum()
            )
        })
    )
    .reset_index()
)

print("Rows:", len(combined_18))
display(combined_18.head(20).round(4))

Rows: 72

/tmp/ipykernel_1674/4247996763.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

,region,feature,count,mean,min,max,negative_pct,positive_pct
0,HIGH,Azimuth_change,1526827.0,0.0019,-124.7766,124.7541,42.8141,55.8264
1,HIGH,Cn0DbHz,1526827.0,41.8229,38.9000,52.8634,0.0000,100.0000
2,HIGH,Cn0_acceleration,1526827.0,0.0296,-7.3953,11.1000,47.8942,48.6507
3,HIGH,Cn0_change,1526827.0,0.2542,-9.0000,26.9656,42.1054,51.8495
4,HIGH,Cn0_max_5,1526827.0,42.3992,38.9000,52.8634,0.0000,100.0000
5,HIGH,Cn0_min_5,1526827.0,40.1535,20.0000,52.6052,0.0000,100.0000
6,HIGH,Cn0_range_5,1526827.0,2.2457,0.0000,28.9979,0.0000,99.1389
7,HIGH,Cn0_rolling_std,1526827.0,0.9301,0.0000,14.3849,0.0000,99.1389
8,HIGH,Cn0_trend,1526827.0,0.8542,-13.0000,25.7793,38.9639,58.1811
9,HIGH,Elevation_change,1526827.0,0.0002,-54.2212,54.2053,47.1912,51.4493
10,HIGH,PseudorangeRateMetersPerSecond,1526827.0,-7.9805,-2172.7631,962.9221,50.1561,49.8439
11,HIGH,PseudorangeRate_change,1526827.0,0.0587,-456.5812,460.2777,40.7398,57.8553
12,HIGH,SvAzimuthDegrees,1526827.0,179.2171,0.0004,359.9992,0.0000,100.0000
13,HIGH,SvElevationDegrees,1526827.0,45.7857,-5.8850,89.0450,0.0001,99.9999
14,HIGH,down_streak,1526827.0,1.1813,0.0000,65.0000,0.0000,39.8194
15,HIGH,negative_change_count_10,1526827.0,4.4027,0.0000,10.0000,0.0000,97.9594
16,HIGH,positive_change_count_10,1526827.0,4.9985,0.0000,10.0000,0.0000,97.9877
17,HIGH,up_streak,1526827.0,1.9779,0.0000,86.0000,0.0000,56.8368
18,HIGH_MID,Azimuth_change,1762558.0,0.0014,-90.0036,85.5052,46.5270,52.6713
19,HIGH_MID,Cn0DbHz,1762558.0,36.7801,34.8000,38.9000,0.0000,100.0000

In [88]:
slope_add = slope_all[
    ["region", "count", "mean_slope"]
].copy()

slope_add["feature"] = "Cn0_slope"
slope_add = slope_add.rename(
    columns={"mean_slope": "mean"}
)

slope_add["std"] = np.nan
slope_add["min"] = np.nan
slope_add["max"] = np.nan
slope_add["negative_pct"] = np.nan
slope_add["positive_pct"] = np.nan

slope_add = slope_add[
    [
        "region",
        "feature",
        "count",
        "mean",
        "std",
        "min",
        "max",
        "negative_pct",
        "positive_pct"
    ]
]

print("Cn0_slope rows:", len(slope_add))
display(slope_add)

Cn0_slope rows: 4

,region,feature,count,mean,std,min,max,negative_pct,positive_pct
0,LOW,Cn0_slope,2244649,-0.337808,NaN,NaN,NaN,NaN,NaN
1,LOW_MID,Cn0_slope,2150382,0.056286,NaN,NaN,NaN,NaN,NaN
2,HIGH_MID,Cn0_slope,1762558,0.174672,NaN,NaN,NaN,NaN,NaN
3,HIGH,Cn0_slope,1526827,0.213542,NaN,NaN,NaN,NaN,NaN

In [89]:
trend_add = trend_all[
    ["region", "count", "mean_trend"]
].copy()

trend_add["feature"] = "Cn0_trend_mean"

trend_add = trend_add.rename(
    columns={"mean_trend": "mean"}
)

trend_add["std"] = np.nan
trend_add["min"] = np.nan
trend_add["max"] = np.nan
trend_add["negative_pct"] = np.nan
trend_add["positive_pct"] = np.nan

trend_add = trend_add[
    [
        "region",
        "feature",
        "count",
        "mean",
        "std",
        "min",
        "max",
        "negative_pct",
        "positive_pct"
    ]
]

print("Cn0_trend_mean rows:", len(trend_add))
display(trend_add)

Cn0_trend_mean rows: 4

,region,feature,count,mean,std,min,max,negative_pct,positive_pct
0,LOW,Cn0_trend_mean,2244649,-0.382458,NaN,NaN,NaN,NaN,NaN
1,LOW_MID,Cn0_trend_mean,2150382,0.071620,NaN,NaN,NaN,NaN,NaN
2,HIGH_MID,Cn0_trend_mean,1762558,0.196334,NaN,NaN,NaN,NaN,NaN
3,HIGH,Cn0_trend_mean,1526827,0.231965,NaN,NaN,NaN,NaN,NaN

In [90]:
final_behavior_table = pd.concat(
    [
        combined_18,
        slope_add,
        trend_add
    ],
    ignore_index=True
)

print("Total rows:", len(final_behavior_table))
print("Total features:", final_behavior_table["feature"].nunique())
print("Total regions:", final_behavior_table["region"].nunique())

display(
    final_behavior_table.round(4)
)

Total rows: 80
Total features: 20
Total regions: 4

,region,feature,count,mean,min,max,negative_pct,positive_pct,std
0,HIGH,Azimuth_change,1526827.0,0.0019,-124.7766,124.7541,42.8141,55.8264,NaN
1,HIGH,Cn0DbHz,1526827.0,41.8229,38.9000,52.8634,0.0000,100.0000,NaN
2,HIGH,Cn0_acceleration,1526827.0,0.0296,-7.3953,11.1000,47.8942,48.6507,NaN
3,HIGH,Cn0_change,1526827.0,0.2542,-9.0000,26.9656,42.1054,51.8495,NaN
4,HIGH,Cn0_max_5,1526827.0,42.3992,38.9000,52.8634,0.0000,100.0000,NaN
...,...,...,...,...,...,...,...,...,...
75,HIGH,Cn0_slope,1526827.0,0.2135,NaN,NaN,NaN,NaN,NaN
76,LOW,Cn0_trend_mean,2244649.0,-0.3825,NaN,NaN,NaN,NaN,NaN
77,LOW_MID,Cn0_trend_mean,2150382.0,0.0716,NaN,NaN,NaN,NaN,NaN
78,HIGH_MID,Cn0_trend_mean,1762558.0,0.1963,NaN,NaN,NaN,NaN,NaN
79,HIGH,Cn0_trend_mean,1526827.0,0.2320,NaN,NaN,NaN,NaN,NaN

In [ ]:
comibined_18=(master_table.groupby(["region", "feature"],observed=False).apply(lambda g:["count","mean","std","min","max","negative_pct","positive_pct"])
.reset_inde

In [84]:

    grouped = (
        df.groupby("region", observed=False)["Cn0_slope"]
        .agg(["count", "sum"])
        .reset_index()
    )

KeyError: 'Column not found: Cn0_slope'

In [91]:
mean_matrix = (
    final_behavior_table
    .pivot(
        index="feature",
        columns="region",
        values="mean"
    )
    .reindex(columns=[
        "LOW",
        "LOW_MID",
        "HIGH_MID",
        "HIGH"
    ])
)

display(
    mean_matrix.round(4)
)

region                               LOW   LOW_MID  HIGH_MID      HIGH
feature
Azimuth_change                   -0.0000    0.0008    0.0014    0.0019
Cn0DbHz                          26.1162   32.3388   36.7801   41.8229
Cn0_acceleration                 -0.0810    0.0307    0.0389    0.0296
Cn0_change                       -0.4858    0.1246    0.2428    0.2542
Cn0_max_5                        28.9169   33.8521   37.7546   42.3992
Cn0_min_5                        24.7302   30.3356   34.8233   40.1535
Cn0_range_5                       4.1867    3.5165    2.9313    2.2457
Cn0_rolling_std                   1.7220    1.4452    1.2090    0.9301
Cn0_slope                        -0.3378    0.0563    0.1747    0.2135
Cn0_trend                        -1.3512    0.2251    0.6987    0.8542
Cn0_trend_mean                   -0.3825    0.0716    0.1963    0.2320
Elevation_change                 -0.0001    0.0000    0.0001    0.0002
PseudorangeRateMetersPerSecond  -16.0593  -13.0597  -12.3336   -7.9805
PseudorangeRate_change            0.0585    0.0589    0.0569    0.0587
SvAzimuthDegrees                186.0727  183.1456  180.1924  179.2171
SvElevationDegrees               30.1794   36.2509   40.8786   45.7857
down_streak                       2.0563    1.5634    1.3598    1.1813
negative_change_count_10          5.3752    4.9524    4.6971    4.4027
positive_change_count_10          4.4120    4.7424    4.8738    4.9985
up_streak                         0.8981    1.4109    1.6667    1.9779

In [92]:
comparison_table = mean_matrix.copy()

comparison_table["LOW_to_HIGH_change"] = (
    comparison_table["HIGH"]
    - comparison_table["LOW"]
)

comparison_table["absolute_change"] = (
    comparison_table["LOW_to_HIGH_change"]
    .abs()
)

comparison_table["direction"] = np.where(
    comparison_table["LOW_to_HIGH_change"] > 0,
    "INCREASING",
    np.where(
        comparison_table["LOW_to_HIGH_change"] < 0,
        "DECREASING",
        "FLAT"
    )
)

display(
    comparison_table.round(4)
)

region,LOW,LOW_MID,HIGH_MID,HIGH,LOW_to_HIGH_change,absolute_change,direction
feature,,,,,,,
Azimuth_change,-0.0000,0.0008,0.0014,0.0019,0.0019,0.0019,INCREASING
Cn0DbHz,26.1162,32.3388,36.7801,41.8229,15.7067,15.7067,INCREASING
Cn0_acceleration,-0.0810,0.0307,0.0389,0.0296,0.1106,0.1106,INCREASING
Cn0_change,-0.4858,0.1246,0.2428,0.2542,0.7400,0.7400,INCREASING
Cn0_max_5,28.9169,33.8521,37.7546,42.3992,13.4824,13.4824,INCREASING
Cn0_min_5,24.7302,30.3356,34.8233,40.1535,15.4233,15.4233,INCREASING
Cn0_range_5,4.1867,3.5165,2.9313,2.2457,-1.9409,1.9409,DECREASING
Cn0_rolling_std,1.7220,1.4452,1.2090,0.9301,-0.7919,0.7919,DECREASING
Cn0_slope,-0.3378,0.0563,0.1747,0.2135,0.5514,0.5514,INCREASING
Cn0_trend,-1.3512,0.2251,0.6987,0.8542,2.2054,2.2054,INCREASING
Cn0_trend_mean,-0.3825,0.0716,0.1963,0.2320,0.6144,0.6144,INCREASING
Elevation_change,-0.0001,0.0000,0.0001,0.0002,0.0003,0.0003,INCREASING
PseudorangeRateMetersPerSecond,-16.0593,-13.0597,-12.3336,-7.9805,8.0788,8.0788,INCREASING
PseudorangeRate_change,0.0585,0.0589,0.0569,0.0587,0.0002,0.0002,INCREASING
SvAzimuthDegrees,186.0727,183.1456,180.1924,179.2171,-6.8556,6.8556,DECREASING
SvElevationDegrees,30.1794,36.2509,40.8786,45.7857,15.6062,15.6062,INCREASING
down_streak,2.0563,1.5634,1.3598,1.1813,-0.8750,0.8750,DECREASING
negative_change_count_10,5.3752,4.9524,4.6971,4.4027,-0.9725,0.9725,DECREASING
positive_change_count_10,4.4120,4.7424,4.8738,4.9985,0.5864,0.5864,INCREASING
up_streak,0.8981,1.4109,1.6667,1.9779,1.0797,1.0797,INCREASING

In [93]:
feature_change = comparison_table[
    ["LOW", "LOW_MID", "HIGH_MID", "HIGH",
     "LOW_to_HIGH_change", "absolute_change", "direction"]
].sort_values(
    "absolute_change",
    ascending=False
)

display(
    feature_change.round(4)
)

region,LOW,LOW_MID,HIGH_MID,HIGH,LOW_to_HIGH_change,absolute_change,direction
feature,,,,,,,
Cn0DbHz,26.1162,32.3388,36.7801,41.8229,15.7067,15.7067,INCREASING
SvElevationDegrees,30.1794,36.2509,40.8786,45.7857,15.6062,15.6062,INCREASING
Cn0_min_5,24.7302,30.3356,34.8233,40.1535,15.4233,15.4233,INCREASING
Cn0_max_5,28.9169,33.8521,37.7546,42.3992,13.4824,13.4824,INCREASING
PseudorangeRateMetersPerSecond,-16.0593,-13.0597,-12.3336,-7.9805,8.0788,8.0788,INCREASING
SvAzimuthDegrees,186.0727,183.1456,180.1924,179.2171,-6.8556,6.8556,DECREASING
Cn0_trend,-1.3512,0.2251,0.6987,0.8542,2.2054,2.2054,INCREASING
Cn0_range_5,4.1867,3.5165,2.9313,2.2457,-1.9409,1.9409,DECREASING
up_streak,0.8981,1.4109,1.6667,1.9779,1.0797,1.0797,INCREASING
negative_change_count_10,5.3752,4.9524,4.6971,4.4027,-0.9725,0.9725,DECREASING
down_streak,2.0563,1.5634,1.3598,1.1813,-0.8750,0.8750,DECREASING
Cn0_rolling_std,1.7220,1.4452,1.2090,0.9301,-0.7919,0.7919,DECREASING
Cn0_change,-0.4858,0.1246,0.2428,0.2542,0.7400,0.7400,INCREASING
Cn0_trend_mean,-0.3825,0.0716,0.1963,0.2320,0.6144,0.6144,INCREASING
positive_change_count_10,4.4120,4.7424,4.8738,4.9985,0.5864,0.5864,INCREASING
Cn0_slope,-0.3378,0.0563,0.1747,0.2135,0.5514,0.5514,INCREASING
Cn0_acceleration,-0.0810,0.0307,0.0389,0.0296,0.1106,0.1106,INCREASING
Azimuth_change,-0.0000,0.0008,0.0014,0.0019,0.0019,0.0019,INCREASING
Elevation_change,-0.0001,0.0000,0.0001,0.0002,0.0003,0.0003,INCREASING
PseudorangeRate_change,0.0585,0.0589,0.0569,0.0587,0.0002,0.0002,INCREASING

In [94]:
normalized_features = mean_matrix.copy()


normalized_features = normalized_features.apply(
    lambda row: (
        (row - row.mean()) /
        row.std()
        if row.std() != 0 else row * 0
    ),
    axis=1
)

display(
    normalized_features.round(3)
)

region                            LOW  LOW_MID  HIGH_MID   HIGH
feature
Azimuth_change                 -1.233   -0.293     0.425  1.101
Cn0DbHz                        -1.221   -0.289     0.377  1.133
Cn0_acceleration               -1.496    0.456     0.601  0.439
Cn0_change                     -1.479    0.258     0.594  0.627
Cn0_max_5                      -1.189   -0.328     0.353  1.164
Cn0_min_5                      -1.186   -0.332     0.353  1.165
Cn0_range_5                     1.168    0.358    -0.349 -1.177
Cn0_rolling_std                 1.172    0.352    -0.348 -1.175
Cn0_slope                      -1.446    0.118     0.587  0.741
Cn0_trend                      -1.446    0.118     0.587  0.741
Cn0_trend_mean                 -1.455    0.149     0.590  0.716
Elevation_change               -1.167   -0.421     0.477  1.111
PseudorangeRateMetersPerSecond -1.110   -0.210     0.007  1.313
PseudorangeRate_change          0.299    0.708    -1.479  0.471
SvAzimuthDegrees                1.264    0.319    -0.634 -0.949
SvElevationDegrees             -1.216   -0.304     0.391  1.129
down_streak                     1.366    0.061    -0.477 -0.950
negative_change_count_10        1.258    0.232    -0.388 -1.102
positive_change_count_10       -1.365   -0.056     0.464  0.958
up_streak                      -1.292   -0.170     0.390  1.072

In [95]:
region_order = {
    "LOW": 0,
    "LOW_MID": 1,
    "HIGH_MID": 2,
    "HIGH": 3
}

rank_table = mean_matrix.copy()

rank_results = []

for feature, row in rank_table.iterrows():

    values = row[["LOW", "LOW_MID", "HIGH_MID", "HIGH"]].values.astype(float)

    increasing = all(
        values[i] <= values[i + 1]
        for i in range(3)
    )

    decreasing = all(
        values[i] >= values[i + 1]
        for i in range(3)
    )

    raw_change = values[-1] - values[0]

    rank_results.append({
        "feature": feature,
        "raw_change": raw_change,
        "absolute_change": abs(raw_change),
        "pattern": (
            "INCREASING"
            if increasing
            else "DECREASING"
            if decreasing
            else "NON_MONOTONIC"
        )
    })

feature_pattern_table = (
    pd.DataFrame(rank_results)
    .sort_values(
        "absolute_change",
        ascending=False
    )
)

display(
    feature_pattern_table.round(4)
)

                           feature  raw_change  absolute_change        pattern
1                          Cn0DbHz     15.7067          15.7067     INCREASING
15              SvElevationDegrees     15.6062          15.6062     INCREASING
5                        Cn0_min_5     15.4233          15.4233     INCREASING
4                        Cn0_max_5     13.4824          13.4824     INCREASING
12  PseudorangeRateMetersPerSecond      8.0788           8.0788     INCREASING
14                SvAzimuthDegrees     -6.8556           6.8556     DECREASING
9                        Cn0_trend      2.2054           2.2054     INCREASING
6                      Cn0_range_5     -1.9409           1.9409     DECREASING
19                       up_streak      1.0797           1.0797     INCREASING
17        negative_change_count_10     -0.9725           0.9725     DECREASING
16                     down_streak     -0.8750           0.8750     DECREASING
7                  Cn0_rolling_std     -0.7919           0.7919     DECREASING
3                       Cn0_change      0.7400           0.7400     INCREASING
10                  Cn0_trend_mean      0.6144           0.6144     INCREASING
18        positive_change_count_10      0.5864           0.5864     INCREASING
8                        Cn0_slope      0.5514           0.5514     INCREASING
2                 Cn0_acceleration      0.1106           0.1106  NON_MONOTONIC
0                   Azimuth_change      0.0019           0.0019     INCREASING
11                Elevation_change      0.0003           0.0003     INCREASING
13          PseudorangeRate_change      0.0002           0.0002  NON_MONOTONIC

In [96]:
from scipy.stats import spearmanr

region_order = {
    "LOW": 0,
    "LOW_MID": 1,
    "HIGH_MID": 2,
    "HIGH": 3
}

scores = []

for feature in mean_matrix.index:

    values = mean_matrix.loc[
        feature,
        ["LOW", "LOW_MID", "HIGH_MID", "HIGH"]
    ].values.astype(float)

    rho, p_value = spearmanr(
        [0, 1, 2, 3],
        values
    )

    scores.append({
        "feature": feature,
        "spearman_rho": rho,
        "p_value": p_value
    })

feature_consistency = (
    pd.DataFrame(scores)
    .sort_values(
        "spearman_rho",
        key=lambda x: x.abs(),
        ascending=False
    )
)

display(
    feature_consistency.round(4)
)

                           feature  spearman_rho  p_value
0                   Azimuth_change           1.0      0.0
1                          Cn0DbHz           1.0      0.0
3                       Cn0_change           1.0      0.0
4                        Cn0_max_5           1.0      0.0
12  PseudorangeRateMetersPerSecond           1.0      0.0
5                        Cn0_min_5           1.0      0.0
6                      Cn0_range_5          -1.0      0.0
7                  Cn0_rolling_std          -1.0      0.0
8                        Cn0_slope           1.0      0.0
9                        Cn0_trend           1.0      0.0
10                  Cn0_trend_mean           1.0      0.0
11                Elevation_change           1.0      0.0
18        positive_change_count_10           1.0      0.0
14                SvAzimuthDegrees          -1.0      0.0
15              SvElevationDegrees           1.0      0.0
16                     down_streak          -1.0      0.0
19                       up_streak           1.0      0.0
17        negative_change_count_10          -1.0      0.0
2                 Cn0_acceleration           0.4      0.6
13          PseudorangeRate_change           0.0      1.0

In [97]:
feature_role_table = pd.DataFrame({
    "feature": [
        "Cn0DbHz",
        "Cn0_min_5",
        "Cn0_max_5",
        "Cn0_change",
        "Cn0_trend",
        "Cn0_trend_mean",
        "Cn0_slope",
        "Cn0_acceleration",
        "down_streak",
        "up_streak",
        "negative_change_count_10",
        "positive_change_count_10",
        "Cn0_rolling_std",
        "Cn0_range_5",
        "PseudorangeRateMetersPerSecond",
        "PseudorangeRate_change",
        "SvElevationDegrees",
        "Elevation_change",
        "SvAzimuthDegrees",
        "Azimuth_change"
    ],

    "role": [
        "Signal strength",
        "Recent minimum strength",
        "Recent maximum strength",
        "Short-term strength change",
        "Recent strength direction",
        "Smoothed strength direction",
        "Rate of strength change",
        "Change in slope",
        "Downward persistence",
        "Upward persistence",
        "Recent negative changes",
        "Recent positive changes",
        "Signal variability",
        "Short-term signal range",
        "Pseudorange-rate behavior",
        "Pseudorange-rate change",
        "Satellite elevation",
        "Elevation movement",
        "Satellite azimuth",
        "Azimuth movement"
    ]
})

display(feature_role_table)

                           feature                         role
0                          Cn0DbHz              Signal strength
1                        Cn0_min_5      Recent minimum strength
2                        Cn0_max_5      Recent maximum strength
3                       Cn0_change   Short-term strength change
4                        Cn0_trend    Recent strength direction
5                   Cn0_trend_mean  Smoothed strength direction
6                        Cn0_slope      Rate of strength change
7                 Cn0_acceleration              Change in slope
8                      down_streak         Downward persistence
9                        up_streak           Upward persistence
10        negative_change_count_10      Recent negative changes
11        positive_change_count_10      Recent positive changes
12                 Cn0_rolling_std           Signal variability
13                     Cn0_range_5      Short-term signal range
14  PseudorangeRateMetersPerSecond    Pseudorange-rate behavior
15          PseudorangeRate_change      Pseudorange-rate change
16              SvElevationDegrees          Satellite elevation
17                Elevation_change           Elevation movement
18                SvAzimuthDegrees            Satellite azimuth
19                  Azimuth_change             Azimuth movement

In [98]:
# Show the feature-role table together with region means

state_evidence_table = mean_matrix.copy()

state_evidence_table = state_evidence_table.merge(
    feature_role_table,
    on="feature",
    how="left"
)

state_evidence_table = state_evidence_table[
    ["feature", "role", "LOW", "LOW_MID", "HIGH_MID", "HIGH"]
]

display(state_evidence_table)

,feature,role,LOW,LOW_MID,HIGH_MID,HIGH
0,Azimuth_change,Azimuth movement,-0.000007,0.000768,0.001360,0.001918
1,Cn0DbHz,Signal strength,26.116206,32.338838,36.780083,41.822886
2,Cn0_acceleration,Change in slope,-0.080985,0.030660,0.038918,0.029640
3,Cn0_change,Short-term strength change,-0.485791,0.124587,0.242764,0.254206
4,Cn0_max_5,Recent maximum strength,28.916852,33.852104,37.754648,42.399239
5,Cn0_min_5,Recent minimum strength,24.730198,30.335637,34.823332,40.153506
6,Cn0_range_5,Short-term signal range,4.186654,3.516466,2.931316,2.245733
7,Cn0_rolling_std,Signal variability,1.721982,1.445235,1.208992,0.930058
8,Cn0_slope,Rate of strength change,-0.337808,0.056286,0.174672,0.213542
9,Cn0_trend,Recent strength direction,-1.351233,0.225145,0.698688,0.854169
10,Cn0_trend_mean,Smoothed strength direction,-0.382458,0.071620,0.196334,0.231965
11,Elevation_change,Elevation movement,-0.000089,0.000001,0.000110,0.000186
12,PseudorangeRateMetersPerSecond,Pseudorange-rate behavior,-16.059342,-13.059655,-12.333614,-7.980537
13,PseudorangeRate_change,Pseudorange-rate change,0.058508,0.058883,0.056876,0.058666
14,SvAzimuthDegrees,Satellite azimuth,186.072685,183.145557,180.192425,179.217125
15,SvElevationDegrees,Satellite elevation,30.179449,36.250919,40.878631,45.785683
16,down_streak,Downward persistence,2.056269,1.563386,1.359799,1.181264
17,negative_change_count_10,Recent negative changes,5.375244,4.952391,4.697114,4.402729
18,positive_change_count_10,Recent positive changes,4.412038,4.742445,4.873766,4.998463
19,up_streak,Upward persistence,0.898133,1.410913,1.666673,1.977872

In [100]:
decision_tabel = feature_role_table.merge(feature_pattern_table[["feature", "raw_change", "absolute_change", "pattern"]],
    on="feature",
    how="left")

In [104]:
decision_table = decision_tabel[
    ["feature", "role", "pattern", "raw_change", "absolute_change"]
]

display(decision_table)

,feature,role,pattern,raw_change,absolute_change
0,Cn0DbHz,Signal strength,INCREASING,15.706680,15.706680
1,Cn0_min_5,Recent minimum strength,INCREASING,15.423308,15.423308
2,Cn0_max_5,Recent maximum strength,INCREASING,13.482388,13.482388
3,Cn0_change,Short-term strength change,INCREASING,0.739996,0.739996
4,Cn0_trend,Recent strength direction,INCREASING,2.205402,2.205402
5,Cn0_trend_mean,Smoothed strength direction,INCREASING,0.614423,0.614423
6,Cn0_slope,Rate of strength change,INCREASING,0.551350,0.551350
7,Cn0_acceleration,Change in slope,NON_MONOTONIC,0.110625,0.110625
8,down_streak,Downward persistence,DECREASING,-0.875005,0.875005
9,up_streak,Upward persistence,INCREASING,1.079740,1.079740
10,negative_change_count_10,Recent negative changes,DECREASING,-0.972516,0.972516
11,positive_change_count_10,Recent positive changes,INCREASING,0.586425,0.586425
12,Cn0_rolling_std,Signal variability,DECREASING,-0.791924,0.791924
13,Cn0_range_5,Short-term signal range,DECREASING,-1.940920,1.940920
14,PseudorangeRateMetersPerSecond,Pseudorange-rate behavior,INCREASING,8.078806,8.078806
15,PseudorangeRate_change,Pseudorange-rate change,NON_MONOTONIC,0.000158,0.000158
16,SvElevationDegrees,Satellite elevation,INCREASING,15.606234,15.606234
17,Elevation_change,Elevation movement,INCREASING,0.000275,0.000275
18,SvAzimuthDegrees,Satellite azimuth,DECREASING,-6.855559,6.855559
19,Azimuth_change,Azimuth movement,INCREASING,0.001924,0.001924

In [105]:
feature_family_table = pd.DataFrame({
    "feature": [
        "Cn0DbHz",
        "Cn0_min_5",
        "Cn0_max_5",
        "Cn0_change",
        "Cn0_trend",
        "Cn0_trend_mean",
        "Cn0_slope",
        "Cn0_acceleration",
        "down_streak",
        "up_streak",
        "negative_change_count_10",
        "positive_change_count_10",
        "Cn0_rolling_std",
        "Cn0_range_5",
        "PseudorangeRateMetersPerSecond",
        "PseudorangeRate_change",
        "SvElevationDegrees",
        "Elevation_change",
        "SvAzimuthDegrees",
        "Azimuth_change"
    ],
    "family": [
        "Signal strength",
        "Signal strength",
        "Signal strength",
        "Direction",
        "Direction",
        "Direction",
        "Direction",
        "Direction",
        "Persistence",
        "Persistence",
        "Persistence",
        "Persistence",
        "Instability",
        "Instability",
        "Pseudorange-rate",
        "Pseudorange-rate",
        "Satellite geometry",
        "Satellite geometry",
        "Satellite geometry",
        "Satellite geometry"
    ]
})

display(feature_family_table)

                           feature              family
0                          Cn0DbHz     Signal strength
1                        Cn0_min_5     Signal strength
2                        Cn0_max_5     Signal strength
3                       Cn0_change           Direction
4                        Cn0_trend           Direction
5                   Cn0_trend_mean           Direction
6                        Cn0_slope           Direction
7                 Cn0_acceleration           Direction
8                      down_streak         Persistence
9                        up_streak         Persistence
10        negative_change_count_10         Persistence
11        positive_change_count_10         Persistence
12                 Cn0_rolling_std         Instability
13                     Cn0_range_5         Instability
14  PseudorangeRateMetersPerSecond    Pseudorange-rate
15          PseudorangeRate_change    Pseudorange-rate
16              SvElevationDegrees  Satellite geometry
17                Elevation_change  Satellite geometry
18                SvAzimuthDegrees  Satellite geometry
19                  Azimuth_change  Satellite geometry

In [106]:
state_rule_worksheet = pd.DataFrame({
    "state": [
        "BAD",
        "DEGRADING",
        "RECOVERY",
        "GOOD"
    ],
    "signal_strength": [
        "LOW",
        "LOW/MEDIUM",
        "MEDIUM",
        "HIGH"
    ],
    "direction": [
        "NEGATIVE",
        "NEGATIVE",
        "POSITIVE",
        "POSITIVE/NEUTRAL"
    ],
    "persistence": [
        "DOWN",
        "DOWN",
        "UP",
        "UP/LOW DOWN"
    ],
    "instability": [
        "HIGH",
        "MEDIUM/HIGH",
        "MEDIUM/LOW",
        "LOW"
    ]
})

display(state_rule_worksheet)

       state signal_strength         direction  persistence  instability
0        BAD             LOW          NEGATIVE         DOWN         HIGH
1  DEGRADING      LOW/MEDIUM          NEGATIVE         DOWN  MEDIUM/HIGH
2   RECOVERY          MEDIUM          POSITIVE           UP   MEDIUM/LOW
3       GOOD            HIGH  POSITIVE/NEUTRAL  UP/LOW DOWN          LOW

In [108]:
signal_features = [
    "Cn0DbHz",
    "Cn0_min_5",
    "Cn0_max_5"
]

signal_threshold_candidates = []

for feature in signal_features:
    row = mean_matrix.loc[feature]

    signal_threshold_candidates.append({
        "feature": feature,
        "LOW_region": row["LOW"],
        "LOW_MID_region": row["LOW_MID"],
        "HIGH_MID_region": row["HIGH_MID"],
        "HIGH_region": row["HIGH"]
    })

signal_threshold_candidates = pd.DataFrame(signal_threshold_candidates)

display(signal_threshold_candidates)

     feature  LOW_region  LOW_MID_region  HIGH_MID_region  HIGH_region
0    Cn0DbHz   26.116206       32.338838        36.780083    41.822886
1  Cn0_min_5   24.730198       30.335637        34.823332    40.153506
2  Cn0_max_5   28.916852       33.852104        37.754648    42.399239

In [110]:
# Direction feature values from the existing 20-feature mean table

direction_features = [
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "Cn0_slope"
]

direction_threshold_candidates = mean_matrix.loc[
    direction_features,
    ["LOW", "LOW_MID", "HIGH_MID", "HIGH"]
].copy()

direction_threshold_candidates.index.name = "feature"

display(direction_threshold_candidates)

region               LOW   LOW_MID  HIGH_MID      HIGH
feature
Cn0_change     -0.485791  0.124587  0.242764  0.254206
Cn0_trend      -1.351233  0.225145  0.698688  0.854169
Cn0_trend_mean -0.382458  0.071620  0.196334  0.231965
Cn0_slope      -0.337808  0.056286  0.174672  0.213542

In [111]:
print("RUNNING PERSISTENCE ANALYSIS")

persistence_features = [
    "down_streak",
    "up_streak",
    "negative_change_count_10",
    "positive_change_count_10"
]

persistence_table = mean_matrix.loc[
    persistence_features,
    ["LOW", "LOW_MID", "HIGH_MID", "HIGH"]
].copy()

persistence_table.index.name = "feature"

display(persistence_table)

RUNNING PERSISTENCE ANALYSIS

region                         LOW   LOW_MID  HIGH_MID      HIGH
feature
down_streak               2.056269  1.563386  1.359799  1.181264
up_streak                 0.898133  1.410913  1.666673  1.977872
negative_change_count_10  5.375244  4.952391  4.697114  4.402729
positive_change_count_10  4.412038  4.742445  4.873766  4.998463

In [112]:
# Instability feature values

instability_features = [
    "Cn0_rolling_std",
    "Cn0_range_5"
]

instability_table = mean_matrix.loc[
    instability_features,
    ["LOW", "LOW_MID", "HIGH_MID", "HIGH"]
].copy()

instability_table.index.name = "feature"

display(instability_table)

region                LOW   LOW_MID  HIGH_MID      HIGH
feature
Cn0_rolling_std  1.721982  1.445235  1.208992  0.930058
Cn0_range_5      4.186654  3.516466  2.931316  2.245733

In [113]:
# Core features available for final state rules

core_features = {
    "signal_strength": [
        "Cn0DbHz",
        "Cn0_min_5",
        "Cn0_max_5"
    ],

    "direction": [
        "Cn0_change",
        "Cn0_trend",
        "Cn0_trend_mean",
        "Cn0_slope"
    ],

    "persistence": [
        "down_streak",
        "up_streak",
        "negative_change_count_10",
        "positive_change_count_10"
    ],

    "instability": [
        "Cn0_rolling_std",
        "Cn0_range_5"
    ]
}

for family, features in core_features.items():
    print(f"\n{family.upper()}")
    for feature in features:
        print(" -", feature)

SIGNAL_STRENGTH
 - Cn0DbHz
 - Cn0_min_5
 - Cn0_max_5

DIRECTION
 - Cn0_change
 - Cn0_trend
 - Cn0_trend_mean
 - Cn0_slope

PERSISTENCE
 - down_streak
 - up_streak
 - negative_change_count_10
 - positive_change_count_10

INSTABILITY
 - Cn0_rolling_std
 - Cn0_range_5

In [114]:
import os
import glob
import pandas as pd
import numpy as np

feature_dir = "/content/gnss_features_v2"

core_features = [
    "Cn0DbHz",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "Cn0_slope",
    "down_streak",
    "up_streak",
    "negative_change_count_10",
    "positive_change_count_10",
    "Cn0_rolling_std",
    "Cn0_range_5"
]

# Find feature files
files = sorted(
    glob.glob(os.path.join(feature_dir, "*"))
)

# Keep training files 001–137
train_files = []

for f in files:
    name = os.path.basename(f)

    if "gnss_" in name:
        try:
            num = int(name.split("gnss_")[1].split(".")[0])
            if 1 <= num <= 137:
                train_files.append(f)
        except:
            pass

print("Training files found:", len(train_files))

# Collect a sample from each file
samples = []

for f in train_files:
    try:
        if f.endswith(".parquet"):
            df = pd.read_parquet(f, columns=core_features)
        else:
            df = pd.read_csv(f, usecols=core_features)

        # Sample up to 5000 rows per training file
        n = min(5000, len(df))
        samples.append(df.sample(n=n, random_state=42))

    except Exception as e:
        print("Skipped:", os.path.basename(f), e)

sampled_data = pd.concat(samples, ignore_index=True)

print("Total sampled rows:", len(sampled_data))

# Calculate percentile candidates
percentile_table = sampled_data[core_features].quantile(
    [0.10, 0.25, 0.50, 0.75, 0.90]
).T

percentile_table.columns = [
    "P10", "P25", "P50", "P75", "P90"
]

percentile_table.index.name = "feature"

display(percentile_table)

Training files found: 137
Total sampled rows: 685000

,P10,P25,P50,P75,P90
feature,,,,,
Cn0DbHz,25.100000,28.900000,33.599863,37.915117,41.313380
Cn0_min_5,22.953144,26.558365,31.600000,36.500000,40.229045
Cn0_max_5,27.500000,30.984103,35.200000,39.100000,42.218030
Cn0_change,-2.000000,-0.700000,0.000000,0.691422,2.000000
Cn0_trend,-3.700000,-1.357722,0.000000,1.300000,3.700000
Cn0_trend_mean,-1.121681,-0.400000,0.000000,0.387726,1.100000
Cn0_slope,-0.925000,-0.339430,0.000000,0.325000,0.925000
down_streak,0.000000,0.000000,0.000000,2.000000,4.000000
up_streak,0.000000,0.000000,0.000000,2.000000,4.000000
negative_change_count_10,3.000000,4.000000,5.000000,6.000000,7.000000
positive_change_count_10,3.000000,4.000000,5.000000,6.000000,7.000000
Cn0_rolling_std,0.240832,0.477493,1.007472,1.942421,3.097903
Cn0_range_5,0.600000,1.195234,2.487286,4.707198,7.500000

In [115]:
# Threshold selection worksheet

threshold_worksheet = percentile_table.copy()

threshold_worksheet["role"] = threshold_worksheet.index.map(
    feature_role_table.set_index("feature")["role"]
)

threshold_worksheet["family"] = threshold_worksheet.index.map(
    feature_family_table.set_index("feature")["family"]
)

threshold_worksheet["behavior"] = threshold_worksheet.index.map(
    decision_table.set_index("feature")["pattern"]
)

threshold_worksheet = threshold_worksheet[
    [
        "family",
        "role",
        "behavior",
        "P10",
        "P25",
        "P50",
        "P75",
        "P90"
    ]
]

display(threshold_worksheet)

,family,role,behavior,P10,P25,P50,P75,P90
feature,,,,,,,,
Cn0DbHz,Signal strength,Signal strength,INCREASING,25.100000,28.900000,33.599863,37.915117,41.313380
Cn0_min_5,Signal strength,Recent minimum strength,INCREASING,22.953144,26.558365,31.600000,36.500000,40.229045
Cn0_max_5,Signal strength,Recent maximum strength,INCREASING,27.500000,30.984103,35.200000,39.100000,42.218030
Cn0_change,Direction,Short-term strength change,INCREASING,-2.000000,-0.700000,0.000000,0.691422,2.000000
Cn0_trend,Direction,Recent strength direction,INCREASING,-3.700000,-1.357722,0.000000,1.300000,3.700000
Cn0_trend_mean,Direction,Smoothed strength direction,INCREASING,-1.121681,-0.400000,0.000000,0.387726,1.100000
Cn0_slope,Direction,Rate of strength change,INCREASING,-0.925000,-0.339430,0.000000,0.325000,0.925000
down_streak,Persistence,Downward persistence,DECREASING,0.000000,0.000000,0.000000,2.000000,4.000000
up_streak,Persistence,Upward persistence,INCREASING,0.000000,0.000000,0.000000,2.000000,4.000000
negative_change_count_10,Persistence,Recent negative changes,DECREASING,3.000000,4.000000,5.000000,6.000000,7.000000
positive_change_count_10,Persistence,Recent positive changes,INCREASING,3.000000,4.000000,5.000000,6.000000,7.000000
Cn0_rolling_std,Instability,Signal variability,DECREASING,0.240832,0.477493,1.007472,1.942421,3.097903
Cn0_range_5,Instability,Short-term signal range,DECREASING,0.600000,1.195234,2.487286,4.707198,7.500000

In [116]:
# Candidate numeric bands for the 4 states
# P25 / P50 / P75 are candidates only.

increasing_features = [
    "Cn0DbHz",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "Cn0_slope",
    "up_streak",
    "positive_change_count_10"
]

decreasing_features = [
    "down_streak",
    "negative_change_count_10",
    "Cn0_rolling_std",
    "Cn0_range_5"
]

rows = []

for feature in increasing_features:
    p25 = percentile_table.loc[feature, "P25"]
    p50 = percentile_table.loc[feature, "P50"]
    p75 = percentile_table.loc[feature, "P75"]

    rows.extend([
        {"feature": feature, "state": "BAD",       "candidate_band": f"<= {p25:.4f}"},
        {"feature": feature, "state": "DEGRADING", "candidate_band": f"{p25:.4f} to {p50:.4f}"},
        {"feature": feature, "state": "RECOVERY",  "candidate_band": f"{p50:.4f} to {p75:.4f}"},
        {"feature": feature, "state": "GOOD",      "candidate_band": f">= {p75:.4f}"}
    ])

for feature in decreasing_features:
    p25 = percentile_table.loc[feature, "P25"]
    p50 = percentile_table.loc[feature, "P50"]
    p75 = percentile_table.loc[feature, "P75"]

    rows.extend([
        {"feature": feature, "state": "BAD",       "candidate_band": f">= {p75:.4f}"},
        {"feature": feature, "state": "DEGRADING", "candidate_band": f"{p50:.4f} to {p75:.4f}"},
        {"feature": feature, "state": "RECOVERY",  "candidate_band": f"{p25:.4f} to {p50:.4f}"},
        {"feature": feature, "state": "GOOD",      "candidate_band": f"<= {p25:.4f}"}
    ])

state_band_candidates = pd.DataFrame(rows)

display(state_band_candidates)

                     feature      state      candidate_band
0                    Cn0DbHz        BAD          <= 28.9000
1                    Cn0DbHz  DEGRADING  28.9000 to 33.5999
2                    Cn0DbHz   RECOVERY  33.5999 to 37.9151
3                    Cn0DbHz       GOOD          >= 37.9151
4                  Cn0_min_5        BAD          <= 26.5584
5                  Cn0_min_5  DEGRADING  26.5584 to 31.6000
6                  Cn0_min_5   RECOVERY  31.6000 to 36.5000
7                  Cn0_min_5       GOOD          >= 36.5000
8                  Cn0_max_5        BAD          <= 30.9841
9                  Cn0_max_5  DEGRADING  30.9841 to 35.2000
10                 Cn0_max_5   RECOVERY  35.2000 to 39.1000
11                 Cn0_max_5       GOOD          >= 39.1000
12                Cn0_change        BAD          <= -0.7000
13                Cn0_change  DEGRADING   -0.7000 to 0.0000
14                Cn0_change   RECOVERY    0.0000 to 0.6914
15                Cn0_change       GOOD           >= 0.6914
16                 Cn0_trend        BAD          <= -1.3577
17                 Cn0_trend  DEGRADING   -1.3577 to 0.0000
18                 Cn0_trend   RECOVERY    0.0000 to 1.3000
19                 Cn0_trend       GOOD           >= 1.3000
20            Cn0_trend_mean        BAD          <= -0.4000
21            Cn0_trend_mean  DEGRADING   -0.4000 to 0.0000
22            Cn0_trend_mean   RECOVERY    0.0000 to 0.3877
23            Cn0_trend_mean       GOOD           >= 0.3877
24                 Cn0_slope        BAD          <= -0.3394
25                 Cn0_slope  DEGRADING   -0.3394 to 0.0000
26                 Cn0_slope   RECOVERY    0.0000 to 0.3250
27                 Cn0_slope       GOOD           >= 0.3250
28                 up_streak        BAD           <= 0.0000
29                 up_streak  DEGRADING    0.0000 to 0.0000
30                 up_streak   RECOVERY    0.0000 to 2.0000
31                 up_streak       GOOD           >= 2.0000
32  positive_change_count_10        BAD           <= 4.0000
33  positive_change_count_10  DEGRADING    4.0000 to 5.0000
34  positive_change_count_10   RECOVERY    5.0000 to 6.0000
35  positive_change_count_10       GOOD           >= 6.0000
36               down_streak        BAD           >= 2.0000
37               down_streak  DEGRADING    0.0000 to 2.0000
38               down_streak   RECOVERY    0.0000 to 0.0000
39               down_streak       GOOD           <= 0.0000
40  negative_change_count_10        BAD           >= 6.0000
41  negative_change_count_10  DEGRADING    5.0000 to 6.0000
42  negative_change_count_10   RECOVERY    4.0000 to 5.0000
43  negative_change_count_10       GOOD           <= 4.0000
44           Cn0_rolling_std        BAD           >= 1.9424
45           Cn0_rolling_std  DEGRADING    1.0075 to 1.9424
46           Cn0_rolling_std   RECOVERY    0.4775 to 1.0075
47           Cn0_rolling_std       GOOD           <= 0.4775
48               Cn0_range_5        BAD           >= 4.7072
49               Cn0_range_5  DEGRADING    2.4873 to 4.7072
50               Cn0_range_5   RECOVERY    1.1952 to 2.4873
51               Cn0_range_5       GOOD           <= 1.1952

In [117]:
# Build candidate state bands

rows = []

# Increasing features:
# higher values move toward GOOD
increasing_features = [
    "Cn0DbHz",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "Cn0_slope",
    "up_streak",
    "positive_change_count_10"
]

# Decreasing features:
# higher values move toward BAD
decreasing_features = [
    "down_streak",
    "negative_change_count_10",
    "Cn0_rolling_std",
    "Cn0_range_5"
]

for feature in increasing_features:
    p25 = percentile_table.loc[feature, "P25"]
    p50 = percentile_table.loc[feature, "P50"]
    p75 = percentile_table.loc[feature, "P75"]

    rows += [
        [feature, "BAD",       p25],
        [feature, "DEGRADING", p50],
        [feature, "RECOVERY",  p75],
        [feature, "GOOD",      p75]
    ]

for feature in decreasing_features:
    p25 = percentile_table.loc[feature, "P25"]
    p50 = percentile_table.loc[feature, "P50"]
    p75 = percentile_table.loc[feature, "P75"]

    rows += [
        [feature, "BAD",       p75],
        [feature, "DEGRADING", p50],
        [feature, "RECOVERY",  p25],
        [feature, "GOOD",      p25]
    ]

state_band_candidates = pd.DataFrame(
    rows,
    columns=["feature", "state", "candidate_value"]
)

display(state_band_candidates)

                     feature      state  candidate_value
0                    Cn0DbHz        BAD        28.900000
1                    Cn0DbHz  DEGRADING        33.599863
2                    Cn0DbHz   RECOVERY        37.915117
3                    Cn0DbHz       GOOD        37.915117
4                  Cn0_min_5        BAD        26.558365
5                  Cn0_min_5  DEGRADING        31.600000
6                  Cn0_min_5   RECOVERY        36.500000
7                  Cn0_min_5       GOOD        36.500000
8                  Cn0_max_5        BAD        30.984103
9                  Cn0_max_5  DEGRADING        35.200000
10                 Cn0_max_5   RECOVERY        39.100000
11                 Cn0_max_5       GOOD        39.100000
12                Cn0_change        BAD        -0.700000
13                Cn0_change  DEGRADING         0.000000
14                Cn0_change   RECOVERY         0.691422
15                Cn0_change       GOOD         0.691422
16                 Cn0_trend        BAD        -1.357722
17                 Cn0_trend  DEGRADING         0.000000
18                 Cn0_trend   RECOVERY         1.300000
19                 Cn0_trend       GOOD         1.300000
20            Cn0_trend_mean        BAD        -0.400000
21            Cn0_trend_mean  DEGRADING         0.000000
22            Cn0_trend_mean   RECOVERY         0.387726
23            Cn0_trend_mean       GOOD         0.387726
24                 Cn0_slope        BAD        -0.339430
25                 Cn0_slope  DEGRADING         0.000000
26                 Cn0_slope   RECOVERY         0.325000
27                 Cn0_slope       GOOD         0.325000
28                 up_streak        BAD         0.000000
29                 up_streak  DEGRADING         0.000000
30                 up_streak   RECOVERY         2.000000
31                 up_streak       GOOD         2.000000
32  positive_change_count_10        BAD         4.000000
33  positive_change_count_10  DEGRADING         5.000000
34  positive_change_count_10   RECOVERY         6.000000
35  positive_change_count_10       GOOD         6.000000
36               down_streak        BAD         2.000000
37               down_streak  DEGRADING         0.000000
38               down_streak   RECOVERY         0.000000
39               down_streak       GOOD         0.000000
40  negative_change_count_10        BAD         6.000000
41  negative_change_count_10  DEGRADING         5.000000
42  negative_change_count_10   RECOVERY         4.000000
43  negative_change_count_10       GOOD         4.000000
44           Cn0_rolling_std        BAD         1.942421
45           Cn0_rolling_std  DEGRADING         1.007472
46           Cn0_rolling_std   RECOVERY         0.477493
47           Cn0_rolling_std       GOOD         0.477493
48               Cn0_range_5        BAD         4.707198
49               Cn0_range_5  DEGRADING         2.487286
50               Cn0_range_5   RECOVERY         1.195234
51               Cn0_range_5       GOOD         1.195234

In [118]:

band_rows = []

for feature in increasing_features:
    p25 = percentile_table.loc[feature, "P25"]
    p50 = percentile_table.loc[feature, "P50"]
    p75 = percentile_table.loc[feature, "P75"]

    band_rows.append({
        "feature": feature,
        "BAD": f"<= {p25:.4f}",
        "DEGRADING": f"{p25:.4f} to {p50:.4f}",
        "RECOVERY": f"{p50:.4f} to {p75:.4f}",
        "GOOD": f">= {p75:.4f}"
    })

for feature in decreasing_features:
    p25 = percentile_table.loc[feature, "P25"]
    p50 = percentile_table.loc[feature, "P50"]
    p75 = percentile_table.loc[feature, "P75"]

    band_rows.append({
        "feature": feature,
        "BAD": f">= {p75:.4f}",
        "DEGRADING": f"{p50:.4f} to {p75:.4f}",
        "RECOVERY": f"{p25:.4f} to {p50:.4f}",
        "GOOD": f"<= {p25:.4f}"
    })

band_review = pd.DataFrame(band_rows)

display(band_review)

,feature,BAD,DEGRADING,RECOVERY,GOOD
0,Cn0DbHz,<= 28.9000,28.9000 to 33.5999,33.5999 to 37.9151,>= 37.9151
1,Cn0_min_5,<= 26.5584,26.5584 to 31.6000,31.6000 to 36.5000,>= 36.5000
2,Cn0_max_5,<= 30.9841,30.9841 to 35.2000,35.2000 to 39.1000,>= 39.1000
3,Cn0_change,<= -0.7000,-0.7000 to 0.0000,0.0000 to 0.6914,>= 0.6914
4,Cn0_trend,<= -1.3577,-1.3577 to 0.0000,0.0000 to 1.3000,>= 1.3000
5,Cn0_trend_mean,<= -0.4000,-0.4000 to 0.0000,0.0000 to 0.3877,>= 0.3877
6,Cn0_slope,<= -0.3394,-0.3394 to 0.0000,0.0000 to 0.3250,>= 0.3250
7,up_streak,<= 0.0000,0.0000 to 0.0000,0.0000 to 2.0000,>= 2.0000
8,positive_change_count_10,<= 4.0000,4.0000 to 5.0000,5.0000 to 6.0000,>= 6.0000
9,down_streak,>= 2.0000,0.0000 to 2.0000,0.0000 to 0.0000,<= 0.0000
10,negative_change_count_10,>= 6.0000,5.0000 to 6.0000,4.0000 to 5.0000,<= 4.0000
11,Cn0_rolling_std,>= 1.9424,1.0075 to 1.9424,0.4775 to 1.0075,<= 0.4775
12,Cn0_range_5,>= 4.7072,2.4873 to 4.7072,1.1952 to 2.4873,<= 1.1952

In [ ]:
# Find features whose percentile boundaries are duplicated

for feature in core_features:
    values = percentile_table.loc[
        feature, ["P25", "P50", "P75"]
    ].values

    if len(set(values)) < 3:
        print(
            f"{feature}: DEGNERATE boundaries -> "
            f"P25={values[0]}, P50={values[1]}, P75={values[2]}"
        )

In [ ]:
print("Final label mapping:")
dddd
for number, name in enumerate(label_encoder.classes_):
    print(f"{name} -> {number}")

In [ ]:
input_features = [
    "Cn0DbHz",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "down_streak",
    "up_streak",
    "PseudorangeRateMetersPerSecond",
    "PseudorangeRate_change",
    "SvElevationDegrees",
    "Elevation_change",
    "SvAzimuthDegrees",
    "Azimuth_change",
    "Cn0_rolling_std",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10"
]

print("Number of input features:", len(input_features))
print(input_features)

In [ ]:



X_batch, y_batch = next(iter(train_dataset))

print("X batch shape:", X_batch.shape)
print("y batch shape:", y_batch.shape)

print("\nFirst 20 labels:")
print(y_batch[:20].numpy())

In [ ]:
def count_sequences(start_file, end_file):

    total_sequences = 0

    for file_num in range(start_file, end_file + 1):

        file_path = (
            f"{DATA_DIR}/gnss_{file_num:03d}.parquet"
        )

        data = pd.read_parquet(
            file_path,
            columns=["signal_id"]
        )

        for _, signal_df in data.groupby(
            "signal_id",
            sort=False
        ):

            n = len(signal_df)

            possible = (
                n
                - SEQUENCE_LENGTH
                - PREDICTION_HORIZON
                + 1
            )

            if possible > 0:
                total_sequences += possible

    return total_sequences

In [ ]:
train_dataset = tf.data.Dataset.from_generator(
    lambda: batch_generator(1, 137),
    output_signature=output_signature
).repeat().prefetch(tf.data.AUTOTUNE)

validation_dataset = tf.data.Dataset.from_generator(
    lambda: batch_generator(138, 166),
    output_signature=output_signature
).repeat().prefetch(tf.data.AUTOTUNE)

In [ ]:
import math

train_sequence_count = count_sequences(1, 137)
validation_sequence_count = count_sequences(138, 166)

steps_per_epoch = math.ceil(
    train_sequence_count / BATCH_SIZE
)

validation_steps = math.ceil(
    validation_sequence_count / BATCH_SIZE
)

print("Training sequences:", train_sequence_count)
print("Validation sequences:", validation_sequence_count)
print("Steps per epoch:", steps_per_epoch)
print("Validation steps:", validation_steps)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Bidirectional, LSTM, Dropout, Dense

model = Sequential([
    Input(shape=(20, 20)),

    Bidirectional(
        LSTM(64)
    ),

    Dropout(0.3),

    Dense(32, activation="relu"),

    Dense(4, activation="softmax")
])

model.summary()

In [ ]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)


print("Model compiled successfully ")

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=2,
    restore_best_weights=True
)

In [ ]:
DATA_DIR = "/content/gnss_labeled_v2"
SEQUENCE_LENGTH = 20
PREDICTION_HORIZON = 5
BATCH_SIZE = 256

In [ ]:
validation_dataset = tf.data.Dataset.from_generator(
    lambda: batch_generator(138, 166),
    output_signature=output_signature
)

In [ ]:
output_signature = (
    tf.TensorSpec(
        shape=(None, SEQUENCE_LENGTH, len(input_features)),
        dtype=tf.float32
    ),
    tf.TensorSpec(
        shape=(None,),
        dtype=tf.int32
    )
)

In [ ]:
history = model.fit(
    train_dataset,
    validation_data=validation_dataset,
    steps_per_epoch=steps_per_epoch,
    validation_steps=validation_steps,
    epochs=100,
    callbacks=[early_stopping]
)

In [ ]:
import math
import numpy as np
import pandas as pd
import tensorflow as tf

test_dataset = tf.data.Dataset.from_generator(
    lambda: batch_generator(167, 196),
    output_signature=output_signature
)

test_sequence_count = count_sequences(167, 196)
test_steps = math.ceil(test_sequence_count / BATCH_SIZE)

print("Test sequences:", test_sequence_count)
print("Test steps:", test_steps)

test_loss, test_accuracy = model.evaluate(
    test_dataset,
    steps=test_steps,
    verbose=1
)

print("\n===== TEST RESULTS =====")
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)
print("Test Accuracy (%):", test_accuracy * 100)

In [ ]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    balanced_accuracy_score,
    f1_score
)

y_true = []
y_pred = []

test_dataset_predictions = tf.data.Dataset.from_generator(
    lambda: batch_generator(167, 196),
    output_signature=output_signature
)

for X_batch, y_batch in test_dataset_predictions:

    predictions = model.predict(X_batch, verbose=0)

    predicted_classes = np.argmax(predictions, axis=1)

    y_true.extend(y_batch.numpy())
    y_pred.extend(predicted_classes)

y_true = np.array(y_true)
y_pred = np.array(y_pred)


print("Actual labels:", len(y_true))
print("Predicted labels:", len(y_pred))

In [ ]:
class_names = label_encoder.classes_

print("\nCLASSIFICATION REPORT =====")

print(
    classification_report(
        y_true,
        y_pred,
        target_names=class_names,
        digits=4
    )
)

In [ ]:
cm = confusion_matrix(y_true, y_pred)

cm_df = pd.DataFrame(
    cm,
    index=[f"Actual_{name}" for name in class_names],
    columns=[f"Predicted_{name}" for name in class_names]
)

print("\n CONFUSION MATRIX ")
display(cm_df)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted State")
plt.ylabel("Actual State")
plt.title("GNSS Signal State Prediction Confusion Matrix")
plt.show()

In [ ]:
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy",
    marker="o"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy",
    marker="o"
)

plt.plot(
    history.history["loss"],
    label="Training Loss",
    marker="o"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss",
    marker="o"
)

plt.xlabel("Epoch")
plt.ylabel("Value")
plt.title("Training and Validation Accuracy/Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()