<a href="https://colab.research.google.com/github/ammarbadri919-tech/gnss-signal-state-prediction/blob/main/Copy%20_of_main_modeling_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:

import zipfile

zip_path = "/content/drive/MyDrive/Gnns_kaggle_2324/smartphone-decimeter-2023.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    files = z.namelist()


print("Total files:", len(files))
print("\n".join(files[:50]))

Total files: 904
sdc2023/metadata/accumulated_delta_range_state_bit_map.json
sdc2023/metadata/constellation_type_mapping.csv
sdc2023/metadata/raw_state_bit_map.json
sdc2023/sample_submission.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_imu.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/supplemental/gnss_log.txt
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_gnss.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_imu.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/supplemental/gnss_log.txt
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_gnss.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_imu.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/supplemental/gnss_log.txt
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_gnss.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_imu.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/supplemental/gnss_log.txt
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_gnss.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_imu.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/supplemental/gnss_log.txt
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_gnss.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_imu.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/supplemental/gnss_log.txt
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_gnss.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_imu.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/supplemental/gnss_log.txt
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_gnss.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_imu.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/supplemental/gnss_log.txt
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_gnss.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_imu.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_imu.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_imu.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_imu.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_imu.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/supplemental/gnss_log.txt
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_gnss.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_imu.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/supplemental/gnss_log.txt
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_gnss.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_imu.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/supplemental/gnss_log.txt
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_gnss.csv

In [3]:
csv_file = [file for file in files if file.endswith(".csv")]
print("CSV FILE FOUND",len(csv_file))
print("\n".join(csv_file[:50]))

CSV FILE FOUND 550
sdc2023/metadata/constellation_type_mapping.csv
sdc2023/sample_submission.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_imu.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_gnss.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_imu.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_gnss.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_imu.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_gnss.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_imu.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_gnss.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_imu.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_gnss.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_imu.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_gnss.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_imu.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_gnss.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_imu.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_gnss.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_imu.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_imu.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_imu.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_imu.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_imu.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_gnss.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_imu.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_gnss.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_imu.csv
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_gnss.csv
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_imu.csv
sdc2023/test/2022-04-04-16-31-us-ca-lax-x/pixel5/device_gnss.csv
sdc2023/test/2022-04-04-16-31-us-ca-lax-x/pixel5/device_imu.csv
sdc2023/test/2022-04-22-20-11-us-ca-ebf-y/pixel5/device_gnss.csv
sdc2023/test/2022-04-22-20-11-us-ca-ebf-y/pixel5/device_imu.csv
sdc2023/test/2022-04-25-21-04-us-ca-ebf-x/mi8/device_gnss.csv
sdc2023/test/2022-04-25-21-04-us-ca-ebf-x/mi8/device_imu.csv
sdc2023/test/2022-04-25-22-36-us-ca-ebf-z/pixel5/device_gnss.csv
sdc2023/test/2022-04-25-22-36-us-ca-ebf-z/pixel5/device_imu.csv
sdc2023/test/2022-04-27-18-16-us-ca-ebf-zz/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-18-16-us-ca-ebf-zz/pixel5/device_imu.csv
sdc2023/test/2022-04-27-19-23-us-ca-ebf-xx/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-19-23-us-ca-ebf-xx/pixel5/device_imu.csv
sdc2023/test/2022-04-27-21-55-us-ca-ebf-ww/mi8/device_gnss.csv
sdc2023/test/2022-04-27-21-55-us-ca-ebf-ww/mi8/device_imu.csv
sdc2023/test/2022-05-12-20-19-us-ca-mtv-pe1/samsunga325g/device_gnss.csv
sdc2023/test/2022-05-12-20-19-us-ca-mtv-pe1/samsunga325g/device_imu.csv

In [4]:
gnss_files =[file for file in csv_file
             if file.endswith("/device_gnss.csv")]
print("GNSS files found",len(gnss_files))
print("\n".join(gnss_files[:50]))

GNSS files found 196
sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
sdc2023/test/2021-08-17-20-37-us-ca-mtv-g/pixel5/device_gnss.csv
sdc2023/test/2021-08-31-20-37-us-ca-mtv-e/sm-g988b/device_gnss.csv
sdc2023/test/2021-09-14-20-32-us-ca-mtv-k/pixel4/device_gnss.csv
sdc2023/test/2021-09-20-19-03-us-ca-mtv-l/pixel4/device_gnss.csv
sdc2023/test/2021-09-28-21-56-us-ca-mtv-a/mi8/device_gnss.csv
sdc2023/test/2021-11-05-18-28-us-ca-mtv-m/pixel6pro/device_gnss.csv
sdc2023/test/2021-11-30-20-59-us-ca-mtv-m/mi8/device_gnss.csv
sdc2023/test/2022-02-08-22-04-us-ca-sjc-r/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-17-46-us-ca-lax-n/pixel5/device_gnss.csv
sdc2023/test/2022-02-23-22-35-us-ca-lax-m/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-15-10-us-ca-lax-p/pixel5/device_gnss.csv
sdc2023/test/2022-02-24-22-14-us-ca-lax-i/pixel5/device_gnss.csv
sdc2023/test/2022-03-14-19-57-us-ca-mtv-pe1/xiaomimi8/device_gnss.csv
sdc2023/test/2022-03-17-20-16-us-ca-sjc-q/sm-g988b/device_gnss.csv
sdc2023/test/2022-03-22-18-44-us-ca-mtv-pe1/pixel5/device_gnss.csv
sdc2023/test/2022-04-04-16-31-us-ca-lax-x/pixel5/device_gnss.csv
sdc2023/test/2022-04-22-20-11-us-ca-ebf-y/pixel5/device_gnss.csv
sdc2023/test/2022-04-25-21-04-us-ca-ebf-x/mi8/device_gnss.csv
sdc2023/test/2022-04-25-22-36-us-ca-ebf-z/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-18-16-us-ca-ebf-zz/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-19-23-us-ca-ebf-xx/pixel5/device_gnss.csv
sdc2023/test/2022-04-27-21-55-us-ca-ebf-ww/mi8/device_gnss.csv
sdc2023/test/2022-05-12-20-19-us-ca-mtv-pe1/samsunga325g/device_gnss.csv
sdc2023/test/2022-06-22-20-12-us-ca-lax-hh/samsunga325g/device_gnss.csv
sdc2023/test/2022-06-28-20-56-us-ca-sjc-r/samsunga32/device_gnss.csv
sdc2023/test/2022-07-12-18-37-us-ca-mtv-b/sm-a325f/device_gnss.csv
sdc2023/test/2022-10-06-20-46-us-ca-sjc-r/sm-a205u/device_gnss.csv
sdc2023/test/2023-04-27-19-25-us-ca-mtv-pe1/pixel5/device_gnss.csv
sdc2023/test/2023-04-27-20-55-us-ca-sjc-q/pixel5/device_gnss.csv
sdc2023/test/2023-05-02-19-24-us-ca-sjc-we1/pixel7pro/device_gnss.csv
sdc2023/test/2023-05-02-20-33-us-ca-mtv-xe1/pixel7pro/device_gnss.csv
sdc2023/test/2023-05-09-23-10-us-ca-sjc-r/sm-a505u/device_gnss.csv
sdc2023/test/2023-05-23-21-06-us-ca-mtv-de1/pixel5/device_gnss.csv
sdc2023/test/2023-05-23-22-16-us-ca-mtv-ie2/pixel6pro/device_gnss.csv
sdc2023/test/2023-05-25-17-32-us-ca-pao-j/pixel6pro/device_gnss.csv
sdc2023/test/2023-05-25-21-50-us-ca-sjc-ke2/sm-s908b/device_gnss.csv
sdc2023/test/2023-05-26-21-23-us-ca-sjc-be2/pixel5/device_gnss.csv
sdc2023/test/2023-06-06-22-43-us-ca-sjc-he2/pixel5/device_gnss.csv
sdc2023/test/2023-06-15-18-49-us-ca-sjc-ce1/pixel7pro/device_gnss.csv
sdc2023/train/2020-06-25-00-34-us-ca-mtv-sb-101/pixel4/device_gnss.csv
sdc2023/train/2020-06-25-00-34-us-ca-mtv-sb-101/pixel4xl/device_gnss.csv
sdc2023/train/2020-07-08-22-28-us-ca/pixel4/device_gnss.csv
sdc2023/train/2020-07-08-22-28-us-ca/pixel4xl/device_gnss.csv
sdc2023/train/2020-07-17-22-27-us-ca-mtv-sf-280/pixel4/device_gnss.csv
sdc2023/train/2020-07-17-23-13-us-ca-sf-mtv-280/pixel4/device_gnss.csv
sdc2023/train/2020-07-17-23-13-us-ca-sf-mtv-280/pixel4xl/device_gnss.csv
sdc2023/train/2020-08-04-00-19-us-ca-sb-mtv-101/pixel4/device_gnss.csv
sdc2023/train/2020-08-04-00-20-us-ca-sb-mtv-101/pixel4xl/device_gnss.csv
sdc2023/train/2020-08-04-00-20-us-ca-sb-mtv-101/pixel5/device_gnss.csv

In [5]:
import pandas as pd
import zipfile
sample_file = gnss_files[0]
with zipfile.ZipFile(zip_path, "r") as z:
   sample_df = pd.read_csv(z.open(sample_file), nrows=5)
print("Sample file:", sample_file)
print("Columns:", len(sample_df.columns))
display(sample_df.head())

Sample file: sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
Columns: 58

,MessageType,utcTimeMillis,TimeNanos,LeapSecond,TimeUncertaintyNanos,FullBiasNanos,BiasNanos,BiasUncertaintyNanos,DriftNanosPerSecond,DriftUncertaintyNanosPerSecond,...,SvVelocityYEcefMetersPerSecond,SvVelocityZEcefMetersPerSecond,SvClockBiasMeters,SvClockDriftMetersPerSecond,IsrbMeters,IonosphericDelayMeters,TroposphericDelayMeters,WlsPositionXEcefMeters,WlsPositionYEcefMeters,WlsPositionZEcefMeters
0,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-340.093293,-3183.605736,238953.664854,-0.000900,0.0,3.359449,3.872354,-2.710175e+06,-4.278810e+06,3.863761e+06
1,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-2609.046389,-1041.838400,-8170.672094,-0.003174,0.0,2.412421,2.769697,-2.710175e+06,-4.278810e+06,3.863761e+06
2,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-948.201121,2096.337128,-48995.470518,-0.000954,0.0,3.041131,3.626980,-2.710175e+06,-4.278810e+06,3.863761e+06
3,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-616.523320,3010.480790,-90005.243128,-0.001351,0.0,5.619127,15.589435,-2.710175e+06,-4.278810e+06,3.863761e+06
4,Raw,1607715055442,74585173000000,18,NaN,-1291675688269432104,-0.766369,22.548105,230.194956,9.674811,...,-936.390309,3013.610651,-74629.512567,-0.002282,0.0,6.382237,10.248850,-2.710175e+06,-4.278810e+06,3.863761e+06

In [6]:
import zipfile
with zipfile.ZipFile(zip_path, "r") as z:

  for file in gnss_files:
    print("Processing ",file)
    df =pd.read_csv(z.open(file))
    print("shape",df.shape)
    break

Processing  sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
shape (44501, 58)

In [7]:
import zipfile
with zipfile.ZipFile(zip_path, "r") as z:

  for file in gnss_files:
    print("Processing ",file)
    df =pd.read_csv(z.open(file))
    print("shape",df.shape)
    print("Memory used:",df.memory_usage(deep=True).sum() / 1024**2,
              "MB")
    break

Processing  sdc2023/test/2020-12-11-19-30-us-ca-mtv-e/pixel4xl/device_gnss.csv
shape (44501, 58)
Memory used: 23.67861270904541 MB

In [8]:
print("Memory used",df.memory_usage(deep=True).sum() / 1024**2)
print(df.columns.tolist())

Memory used 23.67861270904541
['MessageType', 'utcTimeMillis', 'TimeNanos', 'LeapSecond', 'TimeUncertaintyNanos', 'FullBiasNanos', 'BiasNanos', 'BiasUncertaintyNanos', 'DriftNanosPerSecond', 'DriftUncertaintyNanosPerSecond', 'HardwareClockDiscontinuityCount', 'Svid', 'TimeOffsetNanos', 'State', 'ReceivedSvTimeNanos', 'ReceivedSvTimeUncertaintyNanos', 'Cn0DbHz', 'PseudorangeRateMetersPerSecond', 'PseudorangeRateUncertaintyMetersPerSecond', 'AccumulatedDeltaRangeState', 'AccumulatedDeltaRangeMeters', 'AccumulatedDeltaRangeUncertaintyMeters', 'CarrierFrequencyHz', 'CarrierCycles', 'CarrierPhase', 'CarrierPhaseUncertainty', 'MultipathIndicator', 'SnrInDb', 'ConstellationType', 'AgcDb', 'BasebandCn0DbHz', 'FullInterSignalBiasNanos', 'FullInterSignalBiasUncertaintyNanos', 'SatelliteInterSignalBiasNanos', 'SatelliteInterSignalBiasUncertaintyNanos', 'CodeType', 'ChipsetElapsedRealtimeNanos', 'ArrivalTimeNanosSinceGpsEpoch', 'RawPseudorangeMeters', 'RawPseudorangeUncertaintyMeters', 'SignalType', 'ReceivedSvTimeNanosSinceGpsEpoch', 'SvPositionXEcefMeters', 'SvPositionYEcefMeters', 'SvPositionZEcefMeters', 'SvElevationDegrees', 'SvAzimuthDegrees', 'SvVelocityXEcefMetersPerSecond', 'SvVelocityYEcefMetersPerSecond', 'SvVelocityZEcefMetersPerSecond', 'SvClockBiasMeters', 'SvClockDriftMetersPerSecond', 'IsrbMeters', 'IonosphericDelayMeters', 'TroposphericDelayMeters', 'WlsPositionXEcefMeters', 'WlsPositionYEcefMeters', 'WlsPositionZEcefMeters']

In [9]:
features = [
    "ConstellationType",
    "Svid",
    "SignalType",
    "utcTimeMillis",
    "Cn0DbHz",
    "RawPseudorangeMeters",
    "PseudorangeRateMetersPerSecond",
    "AccumulatedDeltaRangeMeters",
    "SvElevationDegrees",
    "SvAzimuthDegrees"
]
df = df[features].copy()

print("new shape:", df.shape)

new shape: (44501, 10)

In [10]:
##df =df.sort_values(["Svid","utcTimeMillis"]).reset_index(drop=True)

In [11]:
df["signal_id"] = (
    df["ConstellationType"].astype(str)
    + "_"
    + df["Svid"].astype(str)
    + "_"
    + df["SignalType"].astype(str)
)

print(
    df[
        ["ConstellationType", "Svid", "SignalType", "signal_id"]
    ].head(10)
)

   ConstellationType  Svid SignalType       signal_id
0                  1     1  GPS_L1_CA   1_1_GPS_L1_CA
1                  1     3  GPS_L1_CA   1_3_GPS_L1_CA
2                  1     4  GPS_L1_CA   1_4_GPS_L1_CA
3                  1     9  GPS_L1_CA   1_9_GPS_L1_CA
4                  1    16  GPS_L1_CA  1_16_GPS_L1_CA
5                  1    21  GPS_L1_CA  1_21_GPS_L1_CA
6                  1    22  GPS_L1_CA  1_22_GPS_L1_CA
7                  1    31  GPS_L1_CA  1_31_GPS_L1_CA
8                  1    32  GPS_L1_CA  1_32_GPS_L1_CA
9                  3    10  GLO_G1_CA  3_10_GLO_G1_CA

In [12]:
df = df.sort_values(["signal_id","utcTimeMillis"]).reset_index(drop=True)
print(df[["signal_id","utcTimeMillis"]].head(20))

         signal_id  utcTimeMillis
0   1_16_GPS_L1_CA  1607715055442
1   1_16_GPS_L1_CA  1607715056442
2   1_16_GPS_L1_CA  1607715057442
3   1_16_GPS_L1_CA  1607715058442
4   1_16_GPS_L1_CA  1607715059442
5   1_16_GPS_L1_CA  1607715060442
6   1_16_GPS_L1_CA  1607715061442
7   1_16_GPS_L1_CA  1607715062442
8   1_16_GPS_L1_CA  1607715063442
9   1_16_GPS_L1_CA  1607715064442
10  1_16_GPS_L1_CA  1607715065442
11  1_16_GPS_L1_CA  1607715066442
12  1_16_GPS_L1_CA  1607715067442
13  1_16_GPS_L1_CA  1607715068442
14  1_16_GPS_L1_CA  1607715069442
15  1_16_GPS_L1_CA  1607715070442
16  1_16_GPS_L1_CA  1607715071442
17  1_16_GPS_L1_CA  1607715072442
18  1_16_GPS_L1_CA  1607715073442
19  1_16_GPS_L1_CA  1607715074442

In [13]:
numerica_cols =[ "Cn0DbHz",
    "RawPseudorangeMeters",
    "PseudorangeRateMetersPerSecond",
    "AccumulatedDeltaRangeMeters",
    "SvElevationDegrees",
    "SvAzimuthDegrees"
]

In [14]:
df[numerica_cols]=(df.groupby("signal_id")[numerica_cols].transform( lambda x: x.interpolate(
              method="linear",
              limit=2,
              limit_direction="both")))

In [15]:
df = df.dropna(subset= numerica_cols).reset_index(drop=True)

print("new shape:", df.shape)
print("Remaining NaNs:")
print(df[numerica_cols].isna().sum())

new shape: (44276, 11)
Remaining NaNs:
Cn0DbHz                           0
RawPseudorangeMeters              0
PseudorangeRateMetersPerSecond    0
AccumulatedDeltaRangeMeters       0
SvElevationDegrees                0
SvAzimuthDegrees                  0
dtype: int64

Cn0DbHz = signal strength.

In [16]:
def circular_diff_group(group):
    group = group.copy()
    group["Azimuth_change"] = (
        (group["SvAzimuthDegrees"].diff() + 180) % 360
    ) - 180
    return group

df = (
    df.groupby("signal_id", group_keys=False)
      .apply(circular_diff_group)
      .reset_index(drop=True)
)

df["Azimuth_change"] = df["Azimuth_change"].clip(-180, 180)
print("Azimuth circular diff applied successfully!")

Azimuth circular diff applied successfully!

/tmp/ipykernel_1082/4088929506.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(circular_diff_group)

In [17]:
df["Cn0_change"]=(df.groupby("signal_id")["Cn0DbHz"].diff())

In [20]:
#C/N0 rolling mean
df["Cn0_rolling_mean"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).mean()
      )
)

In [26]:
df["Cn0_trend_mean"]=df.groupby("signal_id")["Cn0_change"].transform(lambda x: x.rolling(window=3,min_periods=1).mean())
print("Cn0_trend_mean")

Cn0_trend_mean

In [28]:
df["is_up"]= df["Cn0_trend_mean"]>0
print("is_up")

is_up

In [29]:
df["up_streak"] = (
    df.groupby("signal_id")["is_up"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

print("up_streak created")

up_streak created

In [30]:
df["is_down"]= df["Cn0_trend_mean"]<0
print("is_down")

is_down

In [32]:
df["down_streak"] = (
    df.groupby("signal_id")["is_down"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

print("down_streak created")

down_streak created

In [34]:
df["Cn0_rolling_std"]=(
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).mean()
      )
)
print("Cn0_rolling_std")

Cn0_rolling_std

In [35]:
display( df[ [ "signal_id", "Cn0DbHz", "Cn0_rolling_std" ] ].head(15) )

         signal_id  Cn0DbHz  Cn0_rolling_std
0   1_16_GPS_L1_CA     36.4        36.400000
1   1_16_GPS_L1_CA     36.6        36.500000
2   1_16_GPS_L1_CA     36.1        36.366667
3   1_16_GPS_L1_CA     38.2        36.825000
4   1_16_GPS_L1_CA     39.5        37.360000
5   1_16_GPS_L1_CA     38.9        37.860000
6   1_16_GPS_L1_CA     40.0        38.540000
7   1_16_GPS_L1_CA     38.5        39.020000
8   1_16_GPS_L1_CA     35.1        38.400000
9   1_16_GPS_L1_CA     41.4        38.780000
10  1_16_GPS_L1_CA     43.6        39.720000
11  1_16_GPS_L1_CA     40.2        39.760000
12  1_16_GPS_L1_CA     41.2        40.300000
13  1_16_GPS_L1_CA     41.5        41.580000
14  1_16_GPS_L1_CA     41.4        41.580000

In [37]:
df['cn0_slope']=(df.groupby("signal_id")["Cn0DbHz"].transform(lambda x: x. diff(4)/4))
print("cn0_slope")

cn0_slope

In [38]:
display( df[ [ "signal_id", "Cn0DbHz", "cn0_slope" ] ].head(15) )

         signal_id  Cn0DbHz  cn0_slope
0   1_16_GPS_L1_CA     36.4        NaN
1   1_16_GPS_L1_CA     36.6        NaN
2   1_16_GPS_L1_CA     36.1        NaN
3   1_16_GPS_L1_CA     38.2        NaN
4   1_16_GPS_L1_CA     39.5      0.775
5   1_16_GPS_L1_CA     38.9      0.575
6   1_16_GPS_L1_CA     40.0      0.975
7   1_16_GPS_L1_CA     38.5      0.075
8   1_16_GPS_L1_CA     35.1     -1.100
9   1_16_GPS_L1_CA     41.4      0.625
10  1_16_GPS_L1_CA     43.6      0.900
11  1_16_GPS_L1_CA     40.2      0.425
12  1_16_GPS_L1_CA     41.2      1.525
13  1_16_GPS_L1_CA     41.5      0.025
14  1_16_GPS_L1_CA     41.4     -0.550

In [39]:
zzzz

KeyError: 'Column not found: Cn0_slope'

df["Cn0_acceleration"] = (
    df.groupby("signal_id")["Cn0_slope"]
      .diff()
)

print("Cn0_acceleration created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_slope",
            "Cn0_acceleration"
        ]
    ].head(15)
)

In [ ]:
grmprint(df[["signal_id","utcTimeMillis", "Cn0DbHz" , "Cn0_change"]].head(20))

         signal_id  utcTimeMillis  Cn0DbHz  Cn0_change
0   1_16_GPS_L1_CA  1607715055442     36.4         NaN
1   1_16_GPS_L1_CA  1607715056442     36.6         0.2
2   1_16_GPS_L1_CA  1607715057442     36.1        -0.5
3   1_16_GPS_L1_CA  1607715058442     38.2         2.1
4   1_16_GPS_L1_CA  1607715059442     39.5         1.3
5   1_16_GPS_L1_CA  1607715060442     38.9        -0.6
6   1_16_GPS_L1_CA  1607715061442     40.0         1.1
7   1_16_GPS_L1_CA  1607715062442     38.5        -1.5
8   1_16_GPS_L1_CA  1607715063442     35.1        -3.4
9   1_16_GPS_L1_CA  1607715064442     41.4         6.3
10  1_16_GPS_L1_CA  1607715065442     43.6         2.2
11  1_16_GPS_L1_CA  1607715066442     40.2        -3.4
12  1_16_GPS_L1_CA  1607715067442     41.2         1.0
13  1_16_GPS_L1_CA  1607715068442     41.5         0.3
14  1_16_GPS_L1_CA  1607715069442     41.4        -0.1
15  1_16_GPS_L1_CA  1607715070442     40.8        -0.6
16  1_16_GPS_L1_CA  1607715071442     38.7        -2.1
17  1_16_GPS_L1_CA  1607715072442     42.0         3.3
18  1_16_GPS_L1_CA  1607715073442     43.7         1.7
19  1_16_GPS_L1_CA  1607715074442     41.2        -2.5

In [ ]:
df["time_gap"] = (
    df.groupby("signal_id")["utcTimeMillis"].diff()
)

print(
    df[
        ["signal_id", "utcTimeMillis", "time_gap"]
    ].head(20)
)

         signal_id  utcTimeMillis  time_gap
0   1_16_GPS_L1_CA  1607715055442       NaN
1   1_16_GPS_L1_CA  1607715056442    1000.0
2   1_16_GPS_L1_CA  1607715057442    1000.0
3   1_16_GPS_L1_CA  1607715058442    1000.0
4   1_16_GPS_L1_CA  1607715059442    1000.0
5   1_16_GPS_L1_CA  1607715060442    1000.0
6   1_16_GPS_L1_CA  1607715061442    1000.0
7   1_16_GPS_L1_CA  1607715062442    1000.0
8   1_16_GPS_L1_CA  1607715063442    1000.0
9   1_16_GPS_L1_CA  1607715064442    1000.0
10  1_16_GPS_L1_CA  1607715065442    1000.0
11  1_16_GPS_L1_CA  1607715066442    1000.0
12  1_16_GPS_L1_CA  1607715067442    1000.0
13  1_16_GPS_L1_CA  1607715068442    1000.0
14  1_16_GPS_L1_CA  1607715069442    1000.0
15  1_16_GPS_L1_CA  1607715070442    1000.0
16  1_16_GPS_L1_CA  1607715071442    1000.0
17  1_16_GPS_L1_CA  1607715072442    1000.0
18  1_16_GPS_L1_CA  1607715073442    1000.0
19  1_16_GPS_L1_CA  1607715074442    1000.0

In [ ]:
df["Pseudorange_change"]=(df.groupby("signal_id")["RawPseudorangeMeters"].diff())
print(
    df[
        ["signal_id", "utcTimeMillis","RawPseudorangeMeters","Pseudorange_change"]
    ].head(20)
)

         signal_id  utcTimeMillis  RawPseudorangeMeters  Pseudorange_change
0   1_16_GPS_L1_CA  1607715055442          2.418345e+07                 NaN
1   1_16_GPS_L1_CA  1607715056442          2.418287e+07         -579.199029
2   1_16_GPS_L1_CA  1607715057442          2.418229e+07         -573.802765
3   1_16_GPS_L1_CA  1607715058442          2.418172e+07         -568.706293
4   1_16_GPS_L1_CA  1607715059442          2.418116e+07         -568.406500
5   1_16_GPS_L1_CA  1607715060442          2.418058e+07         -578.599444
6   1_16_GPS_L1_CA  1607715061442          2.418001e+07         -571.704217
7   1_16_GPS_L1_CA  1607715062442          2.417943e+07         -572.603595
8   1_16_GPS_L1_CA  1607715063442          2.417885e+07         -580.997784
9   1_16_GPS_L1_CA  1607715064442          2.417827e+07         -576.800689
10  1_16_GPS_L1_CA  1607715065442          2.417770e+07         -578.899236
11  1_16_GPS_L1_CA  1607715066442          2.417712e+07         -577.100482
12  1_16_GPS_L1_CA  1607715067442          2.417656e+07         -563.609821
13  1_16_GPS_L1_CA  1607715068442          2.417598e+07         -577.400274
14  1_16_GPS_L1_CA  1607715069442          2.417540e+07         -576.800689
15  1_16_GPS_L1_CA  1607715070442          2.417483e+07         -569.905463
16  1_16_GPS_L1_CA  1607715071442          2.417425e+07         -582.796538
17  1_16_GPS_L1_CA  1607715072442          2.417367e+07         -579.498821
18  1_16_GPS_L1_CA  1607715073442          2.417309e+07         -579.498821
19  1_16_GPS_L1_CA  1607715074442          2.417252e+07         -571.404425

In [ ]:
df["PseudorangeRate_change"]=(df.groupby("signal_id")["PseudorangeRateMetersPerSecond"].diff())

In [ ]:
df["Elevation_change"] = (
    df.groupby("signal_id")["SvElevationDegrees"].diff()
)

print(
    df[
        [
            "signal_id",
            "utcTimeMillis",
            "SvElevationDegrees",
            "Elevation_change"
        ]
    ].head(20)
)

         signal_id  utcTimeMillis  SvElevationDegrees  Elevation_change
0   1_16_GPS_L1_CA  1607715055442           13.900605               NaN
1   1_16_GPS_L1_CA  1607715056442           13.906558          0.005952
2   1_16_GPS_L1_CA  1607715057442           13.912509          0.005952
3   1_16_GPS_L1_CA  1607715058442           13.918452          0.005943
4   1_16_GPS_L1_CA  1607715059442           13.924405          0.005953
5   1_16_GPS_L1_CA  1607715060442           13.930350          0.005946
6   1_16_GPS_L1_CA  1607715061442           13.936303          0.005952
7   1_16_GPS_L1_CA  1607715062442           13.942265          0.005962
8   1_16_GPS_L1_CA  1607715063442           13.948238          0.005973
9   1_16_GPS_L1_CA  1607715064442           13.954199          0.005961
10  1_16_GPS_L1_CA  1607715065442           13.960156          0.005957
11  1_16_GPS_L1_CA  1607715066442           13.966096          0.005940
12  1_16_GPS_L1_CA  1607715067442           13.972024          0.005928
13  1_16_GPS_L1_CA  1607715068442           13.977974          0.005950
14  1_16_GPS_L1_CA  1607715069442           13.983932          0.005959
15  1_16_GPS_L1_CA  1607715070442           13.989877          0.005945
16  1_16_GPS_L1_CA  1607715071442           13.995852          0.005975
17  1_16_GPS_L1_CA  1607715072442           14.001817          0.005965
18  1_16_GPS_L1_CA  1607715073442           14.007796          0.005979
19  1_16_GPS_L1_CA  1607715074442           14.013761          0.005965

In [ ]:
df["Azimuth_change"] = (
    df.groupby("signal_id")["SvAzimuthDegrees"].diff()
)

print(
    df[
        [
            "signal_id",
            "utcTimeMillis",
            "SvAzimuthDegrees",
            "Azimuth_change"
        ]
    ].head(20)
)

         signal_id  utcTimeMillis  SvAzimuthDegrees  Azimuth_change
0   1_16_GPS_L1_CA  1607715055442        146.369269             NaN
1   1_16_GPS_L1_CA  1607715056442        146.364709       -0.004561
2   1_16_GPS_L1_CA  1607715057442        146.360131       -0.004578
3   1_16_GPS_L1_CA  1607715058442        146.355562       -0.004569
4   1_16_GPS_L1_CA  1607715059442        146.351011       -0.004552
5   1_16_GPS_L1_CA  1607715060442        146.346451       -0.004559
6   1_16_GPS_L1_CA  1607715061442        146.341907       -0.004544
7   1_16_GPS_L1_CA  1607715062442        146.337359       -0.004548
8   1_16_GPS_L1_CA  1607715063442        146.332837       -0.004522
9   1_16_GPS_L1_CA  1607715064442        146.328280       -0.004556
10  1_16_GPS_L1_CA  1607715065442        146.323744       -0.004536
11  1_16_GPS_L1_CA  1607715066442        146.319193       -0.004551
12  1_16_GPS_L1_CA  1607715067442        146.314620       -0.004574
13  1_16_GPS_L1_CA  1607715068442        146.310061       -0.004559
14  1_16_GPS_L1_CA  1607715069442        146.305497       -0.004564
15  1_16_GPS_L1_CA  1607715070442        146.300930       -0.004567
16  1_16_GPS_L1_CA  1607715071442        146.296357       -0.004573
17  1_16_GPS_L1_CA  1607715072442        146.291796       -0.004561
18  1_16_GPS_L1_CA  1607715073442        146.287215       -0.004580
19  1_16_GPS_L1_CA  1607715074442        146.282652       -0.004564

In [ ]:
print(
    df[
        [
            "Cn0_change",
            "time_gap",
            "Pseudorange_change",
            "PseudorangeRate_change",
            "Elevation_change",
            "Azimuth_change"
        ]
    ].isna().sum()
)

Cn0_change                43
time_gap                  43
Pseudorange_change        43
PseudorangeRate_change    43
Elevation_change          43
Azimuth_change            43
dtype: int64

In [ ]:
print(df["Cn0DbHz"].describe())

count    44276.000000
mean        35.110518
std          5.912629
min         20.000000
25%         31.000000
50%         35.700000
75%         39.600000
max         48.800000
Name: Cn0DbHz, dtype: float64

In [ ]:
print(
    df[
        ["signal_id", "utcTimeMillis", "Cn0DbHz", "Cn0_change"]
    ]
    .sort_values("Cn0DbHz")
    .head(20)
)

             signal_id  utcTimeMillis  Cn0DbHz  Cn0_change
34124   6_26_GAL_E5A_Q  1607715182442     20.0        -1.3
16664     1_9_GPS_L5_Q  1607715493442     20.0        -2.6
32364   6_21_GAL_E5A_Q  1607715543442     20.0        -5.3
14256    1_6_GPS_L1_CA  1607715097442     20.0         NaN
28047   6_12_GAL_E5A_Q  1607715382442     20.0        -0.9
3722    1_21_GPS_L1_CA  1607715333442     20.0       -14.6
793     1_16_GPS_L1_CA  1607715909442     20.0        -0.5
7667     1_26_GPS_L5_Q  1607715835442     20.1        -4.9
4220    1_21_GPS_L1_CA  1607715838442     20.1        -1.0
13736     1_4_GPS_L5_Q  1607715692442     20.1        -2.2
16884     1_9_GPS_L5_Q  1607715763442     20.1        -9.2
21342   3_23_GLO_G1_CA  1607715624442     20.1        -4.4
32383   6_21_GAL_E5A_Q  1607715573442     20.1        -2.7
2702      1_1_GPS_L5_Q  1607715497442     20.1        -1.3
22312   3_24_GLO_G1_CA  1607715437442     20.1        -4.1
36319   6_27_GAL_E5A_Q  1607715250442     20.1        -1.0
28339   6_12_GAL_E5A_Q  1607715765442     20.1        -2.8
27224  6_12_GAL_E1_C_P  1607715682442     20.1        -3.5
30725   6_19_GAL_E5A_Q  1607716162442     20.1        -5.4
28279   6_12_GAL_E5A_Q  1607715678442     20.1        -0.1

In [ ]:
signal = "1_21_GPS_L1_CA"

print(
    df[df["signal_id"] == signal][
        ["utcTimeMillis", "Cn0DbHz", "Cn0_change"]
    ].head(30)
)

      utcTimeMillis  Cn0DbHz  Cn0_change
3447  1607715055442     26.8         NaN
3448  1607715056442     29.0         2.2
3449  1607715057442     29.2         0.2
3450  1607715058442     29.8         0.6
3451  1607715059442     32.4         2.6
3452  1607715060442     27.9        -4.5
3453  1607715061442     33.5         5.6
3454  1607715062442     39.2         5.7
3455  1607715063442     41.9         2.7
3456  1607715064442     44.0         2.1
3457  1607715065442     37.6        -6.4
3458  1607715066442     32.4        -5.2
3459  1607715067442     32.3        -0.1
3460  1607715068442     31.6        -0.7
3461  1607715069442     28.5        -3.1
3462  1607715070442     25.4        -3.1
3463  1607715071442     27.6         2.2
3464  1607715072442     33.5         5.9
3465  1607715073442     30.6        -2.9
3466  1607715074442     37.9         7.3
3467  1607715075442     40.6         2.7
3468  1607715076442     40.5        -0.1
3469  1607715077442     42.3         1.8
3470  1607715078442     40.4        -1.9
3471  1607715079442     41.0         0.6
3472  1607715080442     40.8        -0.2
3473  1607715081442     37.0        -3.8
3474  1607715082442     37.9         0.9
3475  1607715083442     41.1         3.2
3476  1607715084442     34.6        -6.5

In [40]:
df['Cn0_rolling_mean'] = df.groupby('signal_id')['Cn0DbHz'].transform(lambda x: x.rolling(window=5, min_periods=1).mean())

In [42]:
# ============================================================
# EXISTING TEMPORAL FEATURES
# ============================================================

# 1. C/N0 Rolling Mean
df["Cn0_rolling_mean"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).mean()
      )
)

# 2. C/N0 Trend
# Current C/N0 - C/N0 from 4 observations ago
df["Cn0_trend"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.diff(4)
      )
)

# 3. C/N0 Trend Mean
# Average of recent 3 C/N0 changes
df["Cn0_trend_mean"] = (
    df.groupby("signal_id")["Cn0_change"]
      .transform(
          lambda x: x.rolling(
              window=3,
              min_periods=1
          ).mean()
      )
)

# 4. Is the signal going UP?
df["is_up"] = (
    df["Cn0_trend_mean"] > 0
)

# 5. Consecutive UP observations
df["up_streak"] = (
    df.groupby("signal_id")["is_up"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

# 6. Is the signal going DOWN?
df["is_down"] = (
    df["Cn0_trend_mean"] < 0
)

# 7. Consecutive DOWN observations
df["down_streak"] = (
    df.groupby("signal_id")["is_down"]
      .transform(
          lambda x:
              x.astype(int)
               .groupby((x != x.shift()).cumsum())
               .cumsum()
      )
)

print("All existing temporal features created successfully.")

All existing temporal features created successfully.

In [47]:
df["Cn0_acceleration"] = (
    df.groupby("signal_id")["Cn0_slope"]
      .diff()
)

In [48]:
df["Cn0_slope"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(lambda x: x.diff(4) / 4)
)

print("Cn0_slope created")

Cn0_slope created

In [50]:
print("Cn0_slope"in df.columns)

True

In [41]:
df["Cn0_trend"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(lambda x: x.diff(4))
)

print("Cn0_trend created")

Cn0_trend created

In [52]:
# Feature 4: Minimum C/N0 in recent 5 observations

df["Cn0_min_5"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).min()
      )
)

print("Cn0_min_5 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_min_5"
        ]
    ].head(15)
)

Cn0_min_5 created

         signal_id  Cn0DbHz  Cn0_min_5
0   1_16_GPS_L1_CA     36.4       36.4
1   1_16_GPS_L1_CA     36.6       36.4
2   1_16_GPS_L1_CA     36.1       36.1
3   1_16_GPS_L1_CA     38.2       36.1
4   1_16_GPS_L1_CA     39.5       36.1
5   1_16_GPS_L1_CA     38.9       36.1
6   1_16_GPS_L1_CA     40.0       36.1
7   1_16_GPS_L1_CA     38.5       38.2
8   1_16_GPS_L1_CA     35.1       35.1
9   1_16_GPS_L1_CA     41.4       35.1
10  1_16_GPS_L1_CA     43.6       35.1
11  1_16_GPS_L1_CA     40.2       35.1
12  1_16_GPS_L1_CA     41.2       35.1
13  1_16_GPS_L1_CA     41.5       40.2
14  1_16_GPS_L1_CA     41.4       40.2

In [53]:
# Feature 5: Maximum C/N0 in recent 5 observations

df["Cn0_max_5"] = (
    df.groupby("signal_id")["Cn0DbHz"]
      .transform(
          lambda x: x.rolling(
              window=5,
              min_periods=1
          ).max()
      )
)

print("Cn0_max_5 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_min_5",
            "Cn0_max_5"
        ]
    ].head(15)
)

Cn0_max_5 created

         signal_id  Cn0DbHz  Cn0_min_5  Cn0_max_5
0   1_16_GPS_L1_CA     36.4       36.4       36.4
1   1_16_GPS_L1_CA     36.6       36.4       36.6
2   1_16_GPS_L1_CA     36.1       36.1       36.6
3   1_16_GPS_L1_CA     38.2       36.1       38.2
4   1_16_GPS_L1_CA     39.5       36.1       39.5
5   1_16_GPS_L1_CA     38.9       36.1       39.5
6   1_16_GPS_L1_CA     40.0       36.1       40.0
7   1_16_GPS_L1_CA     38.5       38.2       40.0
8   1_16_GPS_L1_CA     35.1       35.1       40.0
9   1_16_GPS_L1_CA     41.4       35.1       41.4
10  1_16_GPS_L1_CA     43.6       35.1       43.6
11  1_16_GPS_L1_CA     40.2       35.1       43.6
12  1_16_GPS_L1_CA     41.2       35.1       43.6
13  1_16_GPS_L1_CA     41.5       40.2       43.6
14  1_16_GPS_L1_CA     41.4       40.2       43.6

In [54]:
# Feature 6: C/N0 range in recent 5 observations

df["Cn0_range_5"] = (
    df["Cn0_max_5"] - df["Cn0_min_5"]
)

print("Cn0_range_5 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_min_5",
            "Cn0_max_5",
            "Cn0_range_5"
        ]
    ].head(15)
)

Cn0_range_5 created

         signal_id  Cn0DbHz  Cn0_min_5  Cn0_max_5  Cn0_range_5
0   1_16_GPS_L1_CA     36.4       36.4       36.4          0.0
1   1_16_GPS_L1_CA     36.6       36.4       36.6          0.2
2   1_16_GPS_L1_CA     36.1       36.1       36.6          0.5
3   1_16_GPS_L1_CA     38.2       36.1       38.2          2.1
4   1_16_GPS_L1_CA     39.5       36.1       39.5          3.4
5   1_16_GPS_L1_CA     38.9       36.1       39.5          3.4
6   1_16_GPS_L1_CA     40.0       36.1       40.0          3.9
7   1_16_GPS_L1_CA     38.5       38.2       40.0          1.8
8   1_16_GPS_L1_CA     35.1       35.1       40.0          4.9
9   1_16_GPS_L1_CA     41.4       35.1       41.4          6.3
10  1_16_GPS_L1_CA     43.6       35.1       43.6          8.5
11  1_16_GPS_L1_CA     40.2       35.1       43.6          8.5
12  1_16_GPS_L1_CA     41.2       35.1       43.6          8.5
13  1_16_GPS_L1_CA     41.5       40.2       43.6          3.4
14  1_16_GPS_L1_CA     41.4       40.2       43.6          3.4

In [55]:
# Feature 7: Number of C/N0 decreases in recent 10 observations

df["negative_change_count_10"] = (
    df.groupby("signal_id")["Cn0_change"]
      .transform(
          lambda x: (
              (x < 0)
              .rolling(
                  window=10,
                  min_periods=1
              )
              .sum()
          )
      )
)

print("negative_change_count_10 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_change",
            "negative_change_count_10"
        ]
    ].head(15)
)

negative_change_count_10 created

         signal_id  Cn0DbHz  Cn0_change  negative_change_count_10
0   1_16_GPS_L1_CA     36.4         NaN                       0.0
1   1_16_GPS_L1_CA     36.6         0.2                       0.0
2   1_16_GPS_L1_CA     36.1        -0.5                       1.0
3   1_16_GPS_L1_CA     38.2         2.1                       1.0
4   1_16_GPS_L1_CA     39.5         1.3                       1.0
5   1_16_GPS_L1_CA     38.9        -0.6                       2.0
6   1_16_GPS_L1_CA     40.0         1.1                       2.0
7   1_16_GPS_L1_CA     38.5        -1.5                       3.0
8   1_16_GPS_L1_CA     35.1        -3.4                       4.0
9   1_16_GPS_L1_CA     41.4         6.3                       4.0
10  1_16_GPS_L1_CA     43.6         2.2                       4.0
11  1_16_GPS_L1_CA     40.2        -3.4                       5.0
12  1_16_GPS_L1_CA     41.2         1.0                       4.0
13  1_16_GPS_L1_CA     41.5         0.3                       4.0
14  1_16_GPS_L1_CA     41.4        -0.1                       5.0

In [56]:
# Feature 8: Number of C/N0 increases in recent 10 observations

df["positive_change_count_10"] = (
    df.groupby("signal_id")["Cn0_change"]
      .transform(
          lambda x: (
              (x > 0)
              .rolling(
                  window=10,
                  min_periods=1
              )
              .sum()
          )
      )
)

print("positive_change_count_10 created")

display(
    df[
        [
            "signal_id",
            "Cn0DbHz",
            "Cn0_change",
            "positive_change_count_10"
        ]
    ].head(15)
)

positive_change_count_10 created

         signal_id  Cn0DbHz  Cn0_change  positive_change_count_10
0   1_16_GPS_L1_CA     36.4         NaN                       0.0
1   1_16_GPS_L1_CA     36.6         0.2                       1.0
2   1_16_GPS_L1_CA     36.1        -0.5                       1.0
3   1_16_GPS_L1_CA     38.2         2.1                       2.0
4   1_16_GPS_L1_CA     39.5         1.3                       3.0
5   1_16_GPS_L1_CA     38.9        -0.6                       3.0
6   1_16_GPS_L1_CA     40.0         1.1                       4.0
7   1_16_GPS_L1_CA     38.5        -1.5                       4.0
8   1_16_GPS_L1_CA     35.1        -3.4                       4.0
9   1_16_GPS_L1_CA     41.4         6.3                       5.0
10  1_16_GPS_L1_CA     43.6         2.2                       6.0
11  1_16_GPS_L1_CA     40.2        -3.4                       5.0
12  1_16_GPS_L1_CA     41.2         1.0                       6.0
13  1_16_GPS_L1_CA     41.5         0.3                       6.0
14  1_16_GPS_L1_CA     41.4        -0.1                       5.0

In [57]:
input_features = [
    # Existing 12
    "Cn0DbHz",
    "Cn0_change",
    "Cn0_trend",
    "Cn0_trend_mean",
    "down_streak",
    "up_streak",
    "PseudorangeRateMetersPerSecond",
    "PseudorangeRate_change",
    "SvElevationDegrees",
    "Elevation_change",
    "SvAzimuthDegrees",
    "Azimuth_change",

    # New 8
    "Cn0_rolling_std",
    "Cn0_slope",
    "Cn0_acceleration",
    "Cn0_min_5",
    "Cn0_max_5",
    "Cn0_range_5",
    "negative_change_count_10",
    "positive_change_count_10"
]

print("Total input features:", len(input_features))
print(input_features)

Total input features: 20
['Cn0DbHz', 'Cn0_change', 'Cn0_trend', 'Cn0_trend_mean', 'down_streak', 'up_streak', 'PseudorangeRateMetersPerSecond', 'PseudorangeRate_change', 'SvElevationDegrees', 'Elevation_change', 'SvAzimuthDegrees', 'Azimuth_change', 'Cn0_rolling_std', 'Cn0_slope', 'Cn0_acceleration', 'Cn0_min_5', 'Cn0_max_5', 'Cn0_range_5', 'negative_change_count_10', 'positive_change_count_10']